// packages/components/src/components/base-chat-bubble/base-chat-bubble.vue
<script lang="ts" setup>
  /**
   * `BaseChatBubble` — a single message bubble within a {@link BaseChatArea}.
   *
   * Lays out an optional avatar alongside a speech bubble that holds the
   * message body (default slot). The `side` prop anchors the bubble to the
   * start (incoming) or end (outgoing) of the conversation and flips the
   * avatar/bubble order accordingly, while `variant` tints an outgoing bubble
   * with the primary colour. Optional `author` and `timestamp` render a meta
   * line, and a `pending` flag dims the bubble for optimistic / not-yet-sent
   * messages.
   *
   * Each bubble renders as a semantic `<li>` so a stack of them reads as a
   * single conversation list inside the chat area's log.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { computed } from 'vue';

  import BaseAvatar from '../base-avatar/base-avatar.vue';
  import BaseTypography from '../base-typography/base-typography.vue';

  /** Which side of the conversation the bubble is anchored to. */
  export type ChatBubbleSide = 'start' | 'end';

  /** Bubble colour treatment. */
  export type ChatBubbleVariant = 'default' | 'primary';

  const props = withDefaults(
    defineProps<{
      /** Conversation side: `start` (incoming) or `end` (outgoing). Defaults to `start`. */
      side?: ChatBubbleSide;
      /** Bubble colour. `primary` is typically used for the current user's messages. */
      variant?: ChatBubbleVariant;
      /** Display name shown in the meta line above the bubble. */
      author?: string;
      /** Timestamp / status label shown in the meta line. */
      timestamp?: string;
      /** Avatar image source. Falls back to the `avatar` slot, then to initials. */
      avatar?: string;
      /** Alt text / initials source for the avatar. */
      avatarAlt?: string;
      /** Dim the bubble to indicate an optimistic / unsent message. */
      pending?: boolean;
    }>(),
    {
      side: 'start',
      variant: 'default',
      author: undefined,
      timestamp: undefined,
      avatar: undefined,
      avatarAlt: undefined,
      pending: false,
    },
  );

  defineSlots<{
    /** Replaces the avatar entirely. */
    avatar(props: Record<string, never>): unknown;
    /** The message body. */
    default(props: Record<string, never>): unknown;
    /** Extra content rendered below the bubble (e.g. reactions, attachments). */
    footer(props: Record<string, never>): unknown;
  }>();

  const hasAvatar = computed(() => Boolean(props.avatar || props.avatarAlt));
  const hasMeta = computed(() => Boolean(props.author || props.timestamp));
</script>

<template>
  <li
    :class="[
      'base-chat-bubble',
      `base-chat-bubble--${side}`,
      `base-chat-bubble--${variant}`,
      { 'base-chat-bubble--pending': pending },
    ]"
  >
    <div
      v-if="$slots.avatar || hasAvatar"
      class="base-chat-bubble__avatar"
    >
      <slot name="avatar">
        <BaseAvatar
          :alt="avatarAlt"
          :initials="avatarAlt"
          :src="avatar"
          size="sm"
        />
      </slot>
    </div>
    <div class="base-chat-bubble__column">
      <div
        v-if="hasMeta"
        class="base-chat-bubble__meta"
      >
        <BaseTypography
          v-if="author"
          as="span"
          color="primary"
          variant="caption"
          weight="semibold"
        >
          {{ author }}
        </BaseTypography>
        <BaseTypography
          v-if="timestamp"
          as="span"
          color="tertiary"
          variant="caption"
        >
          {{ timestamp }}
        </BaseTypography>
      </div>
      <div class="base-chat-bubble__body">
        <slot />
      </div>
      <div
        v-if="$slots.footer"
        class="base-chat-bubble__footer"
      >
        <slot name="footer" />
      </div>
    </div>
  </li>
</template>

<style lang="scss" scoped>
  .base-chat-bubble {
    display: flex;
    gap: var(--mp-spacing-2);
    max-width: 100%;
    align-items: flex-end;
    list-style: none;

    &--start {
      flex-direction: row;
      align-self: flex-start;
    }

    &--end {
      flex-direction: row-reverse;
      align-self: flex-end;
    }

    &--pending {
      opacity: 0.6;
    }

    &__avatar {
      flex-shrink: 0;
    }

    &__column {
      display: flex;
      flex-direction: column;
      gap: var(--mp-spacing-1);
      min-width: 0;
      max-width: min(36rem, 75%);
    }

    &--end &__column {
      align-items: flex-end;
    }

    &__meta {
      display: flex;
      gap: var(--mp-spacing-2);
      align-items: baseline;
      padding-inline: var(--mp-spacing-1);
    }

    &__body {
      padding: var(--mp-spacing-2) var(--mp-spacing-3);
      background-color: var(--mp-color-bg-sunken);
      color: var(--mp-color-text-primary);
      border-radius: var(--mp-radius-lg);
      font-family: var(--mp-font-family-sans);
      font-size: var(--mp-size-font-sm);
      line-height: var(--mp-line-height-normal, 1.5);
      overflow-wrap: anywhere;
    }

    &--start &__body {
      border-end-start-radius: var(--mp-radius-xs, 4px);
    }

    &--end &__body {
      border-end-end-radius: var(--mp-radius-xs, 4px);
    }

    &--primary &__body {
      background-color: var(--mp-color-primary-default);
      color: var(--mp-color-primary-on, #fff);
    }

    &__footer {
      padding-inline: var(--mp-spacing-1);
    }
  }
</style>

// packages/components/src/components/base-chat-bubble/base-chat-bubble.tsx
import { h, hasSlot, Slot, type MpChild, type MpElement, type MpProperties } from '@mission-platform/jsx';

import { BaseAvatar } from '../base-avatar';
import { BaseTypography } from '../base-typography';
import sizeStyles from '../size.module.scss';

import styles from './base-chat-bubble.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type ChatBubbleSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** Which side of the conversation the bubble is anchored to. */
export type ChatBubbleSide = 'start' | 'end';

/** Bubble colour treatment. */
export type ChatBubbleVariant = 'default' | 'primary';

export interface ChatBubbleProperties extends MpProperties {
  /** Conversation side: `start` (incoming) or `end` (outgoing). Defaults to `start`. */
  side?: ChatBubbleSide;
  /** Bubble colour. `primary` is typically used for the current user's messages. */
  variant?: ChatBubbleVariant;
  /** Size token controlling the bubble's scale. Defaults to `'md'`. */
  size?: ChatBubbleSize;
  /** Display name shown in the meta line above the bubble. */
  author?: string;
  /** Timestamp / status label shown in the meta line. */
  timestamp?: string;
  /** Avatar image source. */
  avatar?: string;
  /** Alt text / initials source for the avatar. */
  avatarAlt?: string;
  /** Custom avatar content, replacing the default `BaseAvatar` (the `avatarContent` named slot). */
  avatarContent?: MpChild;
  /** Extra content rendered below the bubble (the `footer` named slot). */
  footer?: MpChild;
  /** Dim the bubble to indicate an optimistic / unsent message. */
  pending?: boolean;
}

/**
 * `BaseChatBubble` — a single message bubble authored once in the neutral JSX
 * dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * Lays out an optional avatar alongside a speech bubble holding the message body
 * (default slot). `side` anchors the bubble to the start (incoming) or end
 * (outgoing) of the conversation, `variant` tints an outgoing bubble, and
 * optional `author`/`timestamp` render a meta line. Each bubble is a semantic
 * `<li>`. It owns its styling through the co-located CSS Module
 * `base-chat-bubble.module.scss` and composes the neutral {@link BaseAvatar}
 * and {@link BaseTypography}.
 *
 * Substitutions from the original Vue SFC: the `avatar`/`footer` SFC slots
 * become the `avatarContent`/`footer` named slots (`<Slot>`), with their
 * presence detected through the framework-neutral {@link hasSlot} helper.
 */
export function BaseChatBubble(properties: Readonly<ChatBubbleProperties>): MpElement {
  const {
    side = 'start',
    variant = 'default',
    author,
    timestamp,
    avatar,
    avatarAlt,
    pending = false,
    size = 'md',
  } = properties;

  const hasAvatar = Boolean(avatar || avatarAlt) || hasSlot('avatarContent');
  const hasMeta = Boolean(author || timestamp);

  return (
    <li
      className={[
        styles['base-chat-bubble'],
        styles[`base-chat-bubble--${side}`],
        styles[`base-chat-bubble--${variant}`],
        sizeStyles[`base-size--${size}`],
        { [styles['base-chat-bubble--pending']]: pending },
      ]}
    >
      {hasAvatar ? (
        <div className={styles['base-chat-bubble__avatar']}>
          <Slot name="avatarContent">
            <BaseAvatar
              alt={avatarAlt}
              initials={avatarAlt}
              size="sm"
              src={avatar}
            />
          </Slot>
        </div>
      ) : undefined}
      <div className={styles['base-chat-bubble__column']}>
        {hasMeta ? (
          <div className={styles['base-chat-bubble__meta']}>
            {author ? (
              <BaseTypography
                as="span"
                color="primary"
                variant="caption"
                weight="semibold"
              >
                {author}
              </BaseTypography>
            ) : undefined}
            {timestamp ? (
              <BaseTypography
                as="span"
                color="tertiary"
                variant="caption"
              >
                {timestamp}
              </BaseTypography>
            ) : undefined}
          </div>
        ) : undefined}
        <div className={styles['base-chat-bubble__body']}>{properties.children}</div>
        {hasSlot('footer') ? (
          <div className={styles['base-chat-bubble__footer']}>
            <Slot name="footer" />
          </div>
        ) : undefined}
      </div>
    </li>
  );
}
