// packages/components/src/components/base-calendar/base-calendar.vue
<script lang="ts" setup>
  import { IconChevron } from '@mission-platform/icons';
  import { DateTime } from 'luxon';
  import { computed, ref, watch } from 'vue';

  import BaseTypography from '../base-typography/base-typography.vue';

  export type CalendarSize = 'sm' | 'md' | 'lg';

  const props = withDefaults(
    defineProps<{
      /** ISO date string (YYYY-MM-DD) – the selected date. */
      modelValue?: string;
      /** Earliest selectable ISO date (YYYY-MM-DD). */
      min?: string;
      /** Latest selectable ISO date (YYYY-MM-DD). */
      max?: string;
      /** Array of ISO date strings (YYYY-MM-DD) that should be un-selectable. */
      disabledDates?: string[];
      /** Visual size of the calendar. */
      size?: CalendarSize;
      /** IANA timezone string used for rendering (e.g. "America/New_York"). Defaults to the local timezone. */
      timezone?: string;
    }>(),
    {
      modelValue: undefined,
      min: undefined,
      max: undefined,
      disabledDates: () => [],
      size: 'md',
      timezone: undefined,
    },
  );

  const emit = defineEmits<{
    'update:modelValue': [value: string];
    change: [value: string];
  }>();

  // ── Helpers ──────────────────────────────────────────────────────────────────

  function zone() {
    return props.timezone ?? 'local';
  }

  function parseISO(iso: string): DateTime | null {
    if (!iso) return null;
    const dt = DateTime.fromISO(iso, { zone: zone() });
    return dt.isValid ? dt : null;
  }

  function todayISO(): string {
    return DateTime.now().setZone(zone()).toISODate() ?? '';
  }

  // ── View state ────────────────────────────────────────────────────────────────

  const initialView = (() => {
    const selected = props.modelValue ? parseISO(props.modelValue) : null;
    const base = selected ?? DateTime.now().setZone(zone());
    return base.startOf('month');
  })();

  const viewYear = ref(initialView.year);
  const viewMonth = ref(initialView.month); // 1-12 (Luxon convention)

  const MONTHS = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];
  const DAYS = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'];

  // ── Computed constraints ──────────────────────────────────────────────────────

  const minDt = computed(() => (props.min ? parseISO(props.min) : null));
  const maxDt = computed(() => (props.max ? parseISO(props.max) : null));
  const disabledSet = computed(() => new Set(props.disabledDates ?? []));

  // ── Calendar grid ─────────────────────────────────────────────────────────────

  interface CalendarCell {
    day: number | null;
    iso: string | null;
    disabled: boolean;
  }

  const calendarDays = computed((): CalendarCell[] => {
    const firstOfMonth = DateTime.fromObject(
      { year: viewYear.value, month: viewMonth.value, day: 1 },
      { zone: zone() },
    );
    // Sunday-first offset: Luxon weekday is 1(Mon)–7(Sun); JS getDay is 0(Sun)–6(Sat)
    const startOffset = firstOfMonth.toJSDate().getDay(); // 0 = Sunday
    const daysInMonth = firstOfMonth.daysInMonth ?? 30;

    const cells: CalendarCell[] = [];

    // Leading empty cells
    for (let i = 0; i < startOffset; i++) {
      cells.push({ day: null, iso: null, disabled: true });
    }

    for (let d = 1; d <= daysInMonth; d++) {
      const dt = firstOfMonth.set({ day: d });
      const iso = dt.toISODate() ?? '';
      let disabled = false;
      if (minDt.value && dt < minDt.value.startOf('day')) disabled = true;
      if (maxDt.value && dt > maxDt.value.startOf('day')) disabled = true;
      if (disabledSet.value.has(iso)) disabled = true;
      cells.push({ day: d, iso, disabled });
    }

    return cells;
  });

  // ── Calendar weeks ─────────────────────────────────────────────────────────

  const calendarWeeks = computed((): CalendarCell[][] => {
    const cells = calendarDays.value;
    const weeks: CalendarCell[][] = [];
    for (let i = 0; i < cells.length; i += 7) {
      weeks.push(cells.slice(i, i + 7));
    }
    return weeks;
  });

  // ── Navigation ────────────────────────────────────────────────────────────────

  function prevMonth() {
    const prev = DateTime.fromObject({ year: viewYear.value, month: viewMonth.value }, { zone: zone() }).minus({
      months: 1,
    });
    viewYear.value = prev.year;
    viewMonth.value = prev.month;
  }

  function nextMonth() {
    const next = DateTime.fromObject({ year: viewYear.value, month: viewMonth.value }, { zone: zone() }).plus({
      months: 1,
    });
    viewYear.value = next.year;
    viewMonth.value = next.month;
  }

  // ── Selection ─────────────────────────────────────────────────────────────────

  function selectDate(iso: string | null, disabled: boolean) {
    if (!iso || disabled) return;
    emit('update:modelValue', iso);
    emit('change', iso);
  }

  // ── State helpers ─────────────────────────────────────────────────────────────

  const today = todayISO();

  function isSelected(iso: string | null): boolean {
    return !!iso && iso === props.modelValue;
  }

  function isToday(iso: string | null): boolean {
    return !!iso && iso === today;
  }

  // ── Sync view when modelValue changes externally ──────────────────────────────

  watch(
    () => props.modelValue,
    (val) => {
      if (!val) return;
      const dt = parseISO(val);
      if (dt) {
        viewYear.value = dt.year;
        viewMonth.value = dt.month;
      }
    },
  );
</script>

<template>
  <div
    :aria-label="`Calendar, ${MONTHS[viewMonth - 1]} ${viewYear}`"
    :class="['base-calendar', `base-calendar--${size}`]"
    role="application"
  >
    <!-- Month / year navigation -->
    <div class="base-calendar__header">
      <button
        aria-label="Previous month"
        class="base-calendar__nav-btn"
        type="button"
        @click="prevMonth"
      >
        <IconChevron
          direction="left"
          size="xs"
        />
      </button>

      <BaseTypography
        as="span"
        class="base-calendar__month-label"
        color="primary"
        variant="label"
      >
        {{ MONTHS[viewMonth - 1] }} {{ viewYear }}
      </BaseTypography>

      <button
        aria-label="Next month"
        class="base-calendar__nav-btn"
        type="button"
        @click="nextMonth"
      >
        <IconChevron
          direction="right"
          size="xs"
        />
      </button>
    </div>

    <!-- Day grid -->
    <div
      :aria-label="`${MONTHS[viewMonth - 1]} ${viewYear}`"
      class="base-calendar__grid"
      role="grid"
    >
      <!-- Weekday header row -->
      <div
        class="base-calendar__row"
        role="row"
      >
        <span
          v-for="d in DAYS"
          :key="d"
          :aria-label="d"
          class="base-calendar__weekday"
          role="columnheader"
        >
          {{ d }}
        </span>
      </div>

      <!-- Week rows -->
      <div
        v-for="(week, wi) in calendarWeeks"
        :key="wi"
        class="base-calendar__row"
        role="row"
      >
        <button
          v-for="(cell, i) in week"
          :key="i"
          :aria-current="isToday(cell.iso) ? 'date' : undefined"
          :aria-label="cell.iso ?? undefined"
          :aria-selected="isSelected(cell.iso)"
          :class="[
            'base-calendar__day',
            {
              'base-calendar__day--empty': !cell.day,
              'base-calendar__day--selected': isSelected(cell.iso),
              'base-calendar__day--today': isToday(cell.iso) && !isSelected(cell.iso),
              'base-calendar__day--disabled': cell.disabled && !!cell.day,
            },
          ]"
          :disabled="!cell.day || cell.disabled"
          role="gridcell"
          type="button"
          @click="selectDate(cell.iso, cell.disabled)"
        >
          {{ cell.day ?? '' }}
        </button>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
  @use '@mission-platform/tokens/scss/mixins' as mp;

  .base-calendar {
    display: inline-flex;
    flex-direction: column;
    background: var(--mp-color-bg-surface);
    border: 1px solid var(--mp-color-border-default);
    border-radius: var(--mp-radius-lg);
    box-shadow: var(--mp-shadow-md);
    user-select: none;

    /* ── Sizes ─────────────────────────────────────────────────────────────────── */

    &--sm {
      padding: var(--mp-spacing-2);
      min-width: 240px;

      .base-calendar__weekday,
      .base-calendar__day {
        height: 28px;

        @include mp.mp-font-caption;
      }
    }

    &--md {
      padding: var(--mp-spacing-3);
      min-width: 280px;

      .base-calendar__weekday,
      .base-calendar__day {
        height: 32px;

        @include mp.mp-font-body-sm;
      }
    }

    &--lg {
      padding: var(--mp-spacing-4);
      min-width: 320px;

      .base-calendar__weekday,
      .base-calendar__day {
        height: 40px;

        @include mp.mp-font-body-md;
      }
    }

    /* ── Header ────────────────────────────────────────────────────────────────── */

    &__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: var(--mp-spacing-2);
    }

    &__month-label {
      flex: 1;
      text-align: center;
    }

    &__nav-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 28px;
      height: 28px;
      flex-shrink: 0;
      border: none;
      background: transparent;
      border-radius: var(--mp-radius-sm);
      cursor: pointer;
      color: var(--mp-color-text-secondary);
      transition:
        background-color 150ms ease,
        color 150ms ease;

      &:hover {
        background-color: var(--mp-color-bg-muted);
        color: var(--mp-color-text-primary);
      }

      &:focus-visible {
        outline: 2px solid var(--mp-color-border-focus);
        outline-offset: 2px;
      }
    }

    /* ── Grid ──────────────────────────────────────────────────────────────────── */

    &__grid {
      display: grid;
      grid-template-columns: repeat(7, 1fr);
      gap: 2px;
    }

    &__row {
      display: grid;
      grid-column: 1 / -1;
      grid-template-columns: subgrid;
    }

    &__weekday {
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: var(--mp-font-weight-medium);
      color: var(--mp-color-text-tertiary);
    }

    /* ── Day cells ─────────────────────────────────────────────────────────────── */

    &__day {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
      border: none;
      background: transparent;
      border-radius: var(--mp-radius-sm);
      cursor: pointer;
      color: var(--mp-color-text-primary);
      transition:
        background-color 150ms ease,
        color 150ms ease;

      &--empty {
        pointer-events: none;
      }

      &--selected {
        background-color: var(--mp-color-primary-default);
        color: var(--mp-color-text-on-primary);
        font-weight: var(--mp-font-weight-semibold);
      }

      &--today {
        background-color: color-mix(in srgb, var(--mp-color-primary-default) 12%, transparent);
        color: var(--mp-color-primary-default);
        font-weight: var(--mp-font-weight-semibold);
      }

      &--disabled {
        opacity: 0.3;
        cursor: not-allowed;
        pointer-events: none;
      }

      &:focus-visible {
        outline: 2px solid var(--mp-color-border-focus);
        outline-offset: 2px;
      }

      &:hover:not(:disabled, .base-calendar__day--selected) {
        background-color: var(--mp-color-bg-muted);
      }
    }
  }
</style>

// packages/components/src/components/base-calendar/base-calendar.tsx
import { IconChevron } from '@mission-platform/icons';
import {
  h,
  useEffect,
  useMemo,
  useState,
  type MpChild,
  type MpElement,
  type MpProperties,
} from '@mission-platform/jsx';
import { DateTime } from 'luxon';

import { BaseTypography } from '../base-typography';

import styles from './base-calendar.module.scss';

/** Visual size of the calendar, matching the shared size scale. */
export type CalendarSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface CalendarProperties extends MpProperties {
  /** ISO date string (YYYY-MM-DD) — the selected date. */
  modelValue?: string;
  /** Earliest selectable ISO date (YYYY-MM-DD). */
  min?: string;
  /** Latest selectable ISO date (YYYY-MM-DD). */
  max?: string;
  /** ISO date strings (YYYY-MM-DD) that should be un-selectable. */
  disabledDates?: string[];
  /**
   * ISO date (YYYY-MM-DD) marking the **start** of a selected range. When set
   * (together with {@link CalendarProperties.rangeEnd}) the grid highlights the
   * whole range — start/end caps plus the days in between — instead of a single
   * selected day.
   */
  rangeStart?: string;
  /** ISO date (YYYY-MM-DD) marking the **end** of a selected range. */
  rangeEnd?: string;
  /**
   * ISO date (YYYY-MM-DD) acting as a **tentative** range end while the user is
   * still choosing it (typically the day under the cursor). When a
   * {@link CalendarProperties.rangeStart} is set but no
   * {@link CalendarProperties.rangeEnd} is yet, the grid previews the range from
   * the start to this date with a lighter highlight, so the range being picked
   * is visible before the second click.
   */
  previewEnd?: string;
  /**
   * Remove the calendar's own surface (border, shadow, background) so it sits
   * flush inside an already-bordered container such as a dropdown panel,
   * avoiding a doubled outline. Defaults to `false`.
   */
  flat?: boolean;
  /** Visual size of the calendar. Defaults to `'md'`. */
  size?: CalendarSize;
  /** IANA timezone string used for rendering (e.g. `"America/New_York"`). Defaults to the local timezone. */
  timezone?: string;
  /** Fired with the next selected ISO date (the controlled `v-model` update). */
  onUpdateModelValue?: (value: string) => void;
  /** Fired with the next selected ISO date whenever it changes. */
  onChange?: (value: string) => void;
  /**
   * Fired with the ISO date of the day under the cursor (and `undefined` when
   * the pointer leaves the grid). Lets a parent range picker feed the hovered
   * day back as {@link CalendarProperties.previewEnd} to preview the range.
   */
  onHoverDate?: (value: string | undefined) => void;
}

/** A single cell in the month grid. */
interface CalendarCell {
  day: number | undefined;
  iso: string | undefined;
  disabled: boolean;
}

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
const MONTHS_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const DAYS = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'];

/** The secondary picker shown in place of the day grid. */
type CalendarView = 'days' | 'months' | 'years';

/** Resolve the configured timezone, falling back to the local zone. */
function resolveZone(timezone: string | undefined): string {
  return timezone ?? 'local';
}

/** Parse an ISO date in the given zone, or `undefined` when invalid/empty. */
function parseISO(iso: string | undefined, timezone: string | undefined): DateTime | undefined {
  if (!iso) {
    return undefined;
  }
  const dateTime = DateTime.fromISO(iso, { zone: resolveZone(timezone) });
  return dateTime.isValid ? dateTime : undefined;
}

/** Today's ISO date in the configured zone. */
function todayISO(timezone: string | undefined): string {
  return DateTime.now().setZone(resolveZone(timezone)).toISODate() ?? '';
}

/** Build the Sunday-first month grid for the given year/month. */
function buildCells(
  viewYear: number,
  viewMonth: number,
  timezone: string | undefined,
  minDate: DateTime | undefined,
  maxDate: DateTime | undefined,
  disabledSet: Set<string>,
): CalendarCell[] {
  const firstOfMonth = DateTime.fromObject(
    { year: viewYear, month: viewMonth, day: 1 },
    { zone: resolveZone(timezone) },
  );
  // Sunday-first offset: JS getDay is 0(Sun)–6(Sat).
  const startOffset = firstOfMonth.toJSDate().getDay();
  const daysInMonth = firstOfMonth.daysInMonth ?? 30;

  const cells: CalendarCell[] = [];
  for (let index = 0; index < startOffset; index++) {
    cells.push({ day: undefined, iso: undefined, disabled: true });
  }
  for (let day = 1; day <= daysInMonth; day++) {
    const dateTime = firstOfMonth.set({ day });
    const iso = dateTime.toISODate() ?? '';
    let disabled = false;
    if (minDate && dateTime < minDate.startOf('day')) {
      disabled = true;
    }
    if (maxDate && dateTime > maxDate.startOf('day')) {
      disabled = true;
    }
    if (disabledSet.has(iso)) {
      disabled = true;
    }
    cells.push({ day, iso, disabled });
  }
  return cells;
}

/**
 * `BaseCalendar` — a month-grid date picker authored once in the neutral JSX
 * dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * It renders a navigable month grid (Sunday-first) of selectable days, honouring
 * `min`/`max` bounds and an explicit `disabledDates` list, with IANA-timezone
 * aware rendering via `luxon`. Clicking the month label swaps the day grid for a
 * twelve-month grid, and clicking the year swaps it for a decade year grid that
 * pages in groups of ten (2026 → 2020–2029), so distant dates are a couple of
 * clicks away. It can also highlight a selected range (`rangeStart`/`rangeEnd`),
 * preview a tentative range from the start to the hovered day (`previewEnd`,
 * fed back via `onHoverDate`), and drop its own surface via `flat` when nested
 * inside an already-bordered container such as a dropdown panel. It composes the
 * migrated
 * {@link BaseTypography} for the labels and owns its styling through the
 * co-located CSS Module `base-calendar.module.scss`.
 *
 * Substitutions from the original Vue SFC: the `ref` view state becomes
 * {@link useState}; the `computed` grid becomes {@link useMemo}; the
 * external-sync `watch` becomes a {@link useEffect}; the
 * `@mission-platform/icons` chevrons become text glyphs; and the `v-model` +
 * `change` emits become the `onUpdateModelValue`/`onChange` callback props.
 */
export function BaseCalendar(properties: CalendarProperties): MpElement {
  const {
    modelValue,
    min,
    max,
    disabledDates = [],
    rangeStart,
    rangeEnd,
    previewEnd,
    flat = false,
    size = 'md',
    timezone,
  } = properties;

  const initialBase = parseISO(modelValue, timezone) ?? DateTime.now().setZone(resolveZone(timezone));
  const initialView = initialBase.startOf('month');

  const [viewYear, setViewYear] = useState<number>(initialView.year);
  const [viewMonth, setViewMonth] = useState<number>(initialView.month);
  const [view, setView] = useState<CalendarView>('days');

  // Sync the visible month when the selected value changes externally.
  useEffect(() => {
    const dateTime = parseISO(modelValue, timezone);
    if (dateTime) {
      setViewYear(dateTime.year);
      setViewMonth(dateTime.month);
    }
  }, [modelValue]);

  const minDate = useMemo(() => parseISO(min, timezone), [min, timezone]);
  const maxDate = useMemo(() => parseISO(max, timezone), [max, timezone]);
  const disabledSet = useMemo(() => new Set(disabledDates), [disabledDates]);

  const weeks = useMemo<CalendarCell[][]>(() => {
    const cells = buildCells(viewYear, viewMonth, timezone, minDate, maxDate, disabledSet);
    const grouped: CalendarCell[][] = [];
    for (let index = 0; index < cells.length; index += 7) {
      grouped.push(cells.slice(index, index + 7));
    }
    return grouped;
  }, [viewYear, viewMonth, timezone, minDate, maxDate, disabledSet]);

  const today = todayISO(timezone);

  const goToPreviousMonth = (): void => {
    const previous = DateTime.fromObject({ year: viewYear, month: viewMonth }, { zone: resolveZone(timezone) }).minus({
      months: 1,
    });
    setViewYear(previous.year);
    setViewMonth(previous.month);
  };

  const goToNextMonth = (): void => {
    const next = DateTime.fromObject({ year: viewYear, month: viewMonth }, { zone: resolveZone(timezone) }).plus({
      months: 1,
    });
    setViewYear(next.year);
    setViewMonth(next.month);
  };

  const selectDate = (iso: string | undefined, disabled: boolean): void => {
    if (!iso || disabled) {
      return;
    }
    properties.onUpdateModelValue?.(iso);
    properties.onChange?.(iso);
  };

  // Report the day under the cursor (or `undefined` on leave) so a parent range
  // picker can preview the tentative range; skipped for empty/disabled cells.
  const hoverDate = (iso: string | undefined, disabled: boolean): void => {
    if (disabled) {
      return;
    }
    properties.onHoverDate?.(iso);
  };

  const rangeActive = !!(rangeStart || rangeEnd);
  // Order the two ISO endpoints lexicographically (which is chronological for
  // `YYYY-MM-DD`); a single endpoint becomes the lone cap with no span.
  const [rangeLo, rangeHi] =
    rangeStart && rangeEnd
      ? rangeStart <= rangeEnd
        ? [rangeStart, rangeEnd]
        : [rangeEnd, rangeStart]
      : [rangeStart || rangeEnd || '', ''];

  const isSelected = (iso: string | undefined): boolean => !!iso && iso === modelValue;
  const isToday = (iso: string | undefined): boolean => !!iso && iso === today;
  const isRangeStart = (iso: string | undefined): boolean => rangeActive && !!iso && !!rangeLo && iso === rangeLo;
  const isRangeEnd = (iso: string | undefined): boolean => rangeActive && !!iso && !!rangeHi && iso === rangeHi;
  const isInRange = (iso: string | undefined): boolean =>
    rangeActive && !!iso && !!rangeLo && !!rangeHi && iso > rangeLo && iso < rangeHi;

  // While a start is chosen but no end yet, the hovered day previews the range:
  // order the start and the hovered day so the span renders either direction.
  const previewActive = !!(previewEnd && rangeStart && !rangeEnd);
  const [previewLo, previewHi] =
    previewActive && previewEnd ? (rangeStart <= previewEnd ? [rangeStart, previewEnd] : [previewEnd, rangeStart]) : ['', ''];

  const isPreviewEnd = (iso: string | undefined): boolean =>
    previewActive && !!iso && iso === previewEnd && iso !== rangeStart;
  const isInPreview = (iso: string | undefined): boolean =>
    previewActive && !!iso && !!previewLo && !!previewHi && iso > previewLo && iso < previewHi;

  const monthLabel = `${MONTHS[viewMonth - 1]} ${viewYear}`;

  // First year of the decade containing the view year (2026 → 2020); the grid
  // also shows the trailing year of the previous decade and the leading year of
  // the next, both rendered muted, so paging by ±10 stays oriented.
  const decadeStart = Math.floor(viewYear / 10) * 10;
  const decadeYears = Array.from({ length: 12 }, (_unused, index) => decadeStart - 1 + index);
  const decadeLabel = `${decadeStart} \u2013 ${decadeStart + 9}`;

  // The header's previous/next buttons page by month (day grid), year (month
  // grid) or decade (year grid) depending on the active secondary view.
  const goPrevious = (): void => {
    if (view === 'months') {
      setViewYear(viewYear - 1);
    } else if (view === 'years') {
      setViewYear(viewYear - 10);
    } else {
      goToPreviousMonth();
    }
  };

  const goNext = (): void => {
    if (view === 'months') {
      setViewYear(viewYear + 1);
    } else if (view === 'years') {
      setViewYear(viewYear + 10);
    } else {
      goToNextMonth();
    }
  };

  const selectMonth = (month: number): void => {
    setViewMonth(month);
    setView('days');
  };

  const selectYear = (year: number): void => {
    setViewYear(year);
    setView('days');
  };

  const weekdayHeader: MpChild = (
    <div
      classNames={styles['base-calendar__row']}
      role="row"
    >
      {DAYS.map((day) => (
        <span
          key={day}
          aria-label={day}
          classNames={styles['base-calendar__weekday']}
          role="columnheader"
        >
          {day}
        </span>
      ))}
    </div>
  );

  const weekRows: MpChild[] = weeks.map((week, weekIndex) => (
    <div
      key={weekIndex}
      classNames={styles['base-calendar__row']}
      role="row"
    >
      {week.map((cell, cellIndex) => (
        <button
          key={cellIndex}
          aria-current={isToday(cell.iso) ? 'date' : undefined}
          aria-label={cell.iso ?? undefined}
          aria-selected={rangeActive ? isRangeStart(cell.iso) || isRangeEnd(cell.iso) : isSelected(cell.iso)}
          classNames={[styles['base-calendar__day'], {
            [styles['base-calendar__day--empty']]: !cell.day,
            [styles['base-calendar__day--selected']]: !rangeActive && isSelected(cell.iso),
            [styles['base-calendar__day--range-start']]: isRangeStart(cell.iso),
            [styles['base-calendar__day--range-end']]: isRangeEnd(cell.iso),
            [styles['base-calendar__day--in-range']]: isInRange(cell.iso),
            [styles['base-calendar__day--preview-end']]: isPreviewEnd(cell.iso),
            [styles['base-calendar__day--in-preview']]: isInPreview(cell.iso),
            [styles['base-calendar__day--today']]:
              isToday(cell.iso) && !isSelected(cell.iso) && !isRangeStart(cell.iso) && !isRangeEnd(cell.iso),
            [styles['base-calendar__day--disabled']]: cell.disabled && !!cell.day,
          }]}
          disabled={!cell.day || cell.disabled}
          role="gridcell"
          type="button"
          onClick={() => selectDate(cell.iso, cell.disabled)}
          onMouseenter={() => hoverDate(cell.iso, cell.disabled)}
        >
          {cell.day ?? ''}
        </button>
      ))}
    </div>
  ));

  return (
    <div
      aria-label={`Calendar, ${monthLabel}`}
      classNames={[styles['base-calendar'], styles[`base-calendar--${size}`], {
        [styles['base-calendar--flat']]: flat,
      }]}
      role="application"
    >
      <div classNames={styles['base-calendar__header']}>
        <button
          aria-label={view === 'days' ? 'Previous month' : view === 'months' ? 'Previous year' : 'Previous decade'}
          classNames={styles['base-calendar__nav-btn']}
          type="button"
          onClick={goPrevious}
        >
          <IconChevron
            direction="left"
            size="sm"
          />
        </button>
        <span classNames={styles['base-calendar__month-label']}>
          {view === 'years' ? (
            <BaseTypography
              as="span"
              color="primary"
              variant="label"
            >
              {decadeLabel}
            </BaseTypography>
          ) : view === 'months' ? (
            <button
              aria-label="Select year"
              classNames={styles['base-calendar__label-btn']}
              type="button"
              onClick={() => setView('years')}
            >
              <BaseTypography
                as="span"
                color="primary"
                variant="label"
              >
                {viewYear}
              </BaseTypography>
            </button>
          ) : (
            <span classNames={styles['base-calendar__label-group']}>
              <button
                aria-label="Select month"
                classNames={styles['base-calendar__label-btn']}
                type="button"
                onClick={() => setView('months')}
              >
                <BaseTypography
                  as="span"
                  color="primary"
                  variant="label"
                >
                  {MONTHS[viewMonth - 1]}
                </BaseTypography>
              </button>
              <button
                aria-label="Select year"
                classNames={styles['base-calendar__label-btn']}
                type="button"
                onClick={() => setView('years')}
              >
                <BaseTypography
                  as="span"
                  color="primary"
                  variant="label"
                >
                  {viewYear}
                </BaseTypography>
              </button>
            </span>
          )}
        </span>
        <button
          aria-label={view === 'days' ? 'Next month' : view === 'months' ? 'Next year' : 'Next decade'}
          classNames={styles['base-calendar__nav-btn']}
          type="button"
          onClick={goNext}
        >
          <IconChevron
            direction="right"
            size="sm"
          />
        </button>
      </div>

      {view === 'days' ? (
        <div
          aria-label={monthLabel}
          classNames={styles['base-calendar__grid']}
          role="grid"
          onMouseleave={() => hoverDate(undefined, false)}
        >
          {[weekdayHeader, ...weekRows]}
        </div>
      ) : view === 'months' ? (
        <div
          aria-label={`Select month, ${viewYear}`}
          classNames={styles['base-calendar__months']}
          role="grid"
        >
          {MONTHS_SHORT.map((monthName, index) => (
            <button
              key={monthName}
              aria-label={MONTHS[index]}
              aria-selected={index + 1 === viewMonth}
              classNames={[styles['base-calendar__cell'], {
                [styles['base-calendar__cell--current']]: index + 1 === viewMonth,
              }]}
              type="button"
              onClick={() => selectMonth(index + 1)}
            >
              {monthName}
            </button>
          ))}
        </div>
      ) : (
        <div
          aria-label={`Select year, ${decadeLabel}`}
          classNames={styles['base-calendar__years']}
          role="grid"
        >
          {decadeYears.map((year) => (
            <button
              key={year}
              aria-label={`${year}`}
              aria-selected={year === viewYear}
              classNames={[styles['base-calendar__cell'], {
                [styles['base-calendar__cell--current']]: year === viewYear,
                [styles['base-calendar__cell--outside']]: year < decadeStart || year > decadeStart + 9,
              }]}
              type="button"
              onClick={() => selectYear(year)}
            >
              {year}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
