// packages/components/src/components/base-button/base-button.tsx
import { classNames, h, type MpElement, type MpProperties } from '@mission-platform/jsx';

import spacingStyles from '../spacing.module.scss';

import styles from './base-button.module.scss';

/** Visual treatment of the button. Mirrors the `@mission-platform/components` `BaseButton`. */
export type ButtonVariant =
  'neutral' | 'primary' | 'secondary' | 'tertiary' | 'success' | 'warning' | 'info' | 'error' | 'critical' | 'ghost';
/** Size token applied to padding and font-size — canonical 2xs → 2xl scale. */
export type ButtonSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
/** Named `padding`/`margin` scale; each step maps to a named `--mp-spacing-*` design token. */
export type SpacingScale = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface ButtonProperties extends MpProperties {
  /** Visual treatment. Defaults to `'primary'`. */
  variant?: ButtonVariant;
  /** Size token controlling padding and font-size. Defaults to `'md'`. */
  size?: ButtonSize;
  /** Native button `type`. Defaults to `'button'`. */
  type?: 'button' | 'submit' | 'reset';
  /** Whether the button is non-interactive. Suppresses `click` and applies the native `disabled` attribute. */
  disabled?: boolean;
  /** Shows the spinner, sets `aria-busy`, and suppresses `click`. */
  loading?: boolean;
  /** Accessible label for the loading spinner. Defaults to `'Loading…'`. */
  loadingLabel?: string;
  /** Click handler forwarded to the underlying `<button>`. Suppressed while `disabled` or `loading`. */
  onClick?: (event: unknown) => void;
  /** Outer margin (named `2xs … 2xl` scale), mapped to a `--mp-spacing-*` token. Overrides the size's intrinsic margin. */
  margin?: SpacingScale;
  /** Inner padding (named `2xs … 2xl` scale), mapped to a `--mp-spacing-*` token. Overrides the size's intrinsic padding. */
  padding?: SpacingScale;
}

/**
 * `BaseButton` — a button authored once in the neutral JSX dialect and compiled
 * straight to React or Vue by `@mission-platform/vite-plugin-jsx`.
 *
 * It mirrors the `@mission-platform/components` `BaseButton`: the canonical
 * colour variants plus a transparent `ghost` treatment, the canonical
 * `2xs → 2xl` size scale, focus-visible outlines, and a
 * built-in accessible loading spinner that sets `aria-busy` and suppresses the
 * click while active. The original Vue SFC sourced the spinner's label from
 * `@mission-platform/i18n`; the neutral version (i18n is not part of this
 * library) defaults `loadingLabel` to `'Loading…'`.
 *
 * It owns its styling through the co-located CSS Module `base-button.module.scss`
 * (carried onto every framework by the two-stage compiler, so the component
 * ships its own `@layer mp.components` CSS). The hashed module class names are
 * assembled with the framework-neutral {@link classNames} helper, including its
 * `{ className: boolean }` object form for the conditional loading modifier.
 */
export function BaseButton(properties: ButtonProperties): MpElement {
  const variant = properties.variant ?? 'primary';
  const size = properties.size ?? 'md';
  const disabled = properties.disabled ?? false;
  const loading = properties.loading ?? false;

  // Optional `padding`/`margin` (named `2xs … 2xl` scale) resolve to the shared
  // token-driven spacing classes (overriding the size's intrinsic box) rather
  // than inline styles.
  const className = classNames(
    styles['base-button'],
    styles[`base-button--${variant}`],
    styles[`base-button--${size}`],
    { [styles['base-button--loading']]: loading },
    properties.padding ? spacingStyles[`base-spacing--padding-${properties.padding}`] : undefined,
    properties.margin ? spacingStyles[`base-spacing--margin-${properties.margin}`] : undefined,
  );

  const handleClick = (event: unknown): void => {
    if (!disabled && !loading) {
      properties.onClick?.(event);
    }
  };

  return (
    <button
      classNames={className}
      type={properties.type ?? 'button'}
      disabled={disabled || loading}
      aria-busy={loading}
      onClick={handleClick}
    >
      {loading ? (
        <span
          classNames={styles['base-button__spinner']}
          role="status"
          aria-label={properties.loadingLabel ?? 'Loading…'}
          aria-live="off"
          aria-atomic="false"
        />
      ) : undefined}
      {properties.children}
    </button>
  );
}

// packages/components/src/components/base-button/base-button.vue
<script lang="ts" setup>
  /**
   * `BaseButton` is the foundational interactive element of the Mission Platform UI.
   *
   * It renders a native `<button>` with consistent theming, sizing, focus-visible
   * outlines, disabled / loading states, and a built-in accessible loading spinner.
   * Use the default slot for the button label and/or leading/trailing icons.
   *
   * Accessibility:
   * - Sets `aria-busy` while `loading` is true.
   * - The spinner exposes an `aria-label` localised via `vue-i18n` (`loading` key).
   * - When `disabled` or `loading`, the native `disabled` attribute is applied and
   *   click events are suppressed.
   *
   * @example
   * ```html
   * <BaseButton variant="primary" size="md" @click="onSave">Save</BaseButton>
   * ```
   */
  import { useI18n } from '@mission-platform/i18n';

  /** Visual treatment of the button. */
  export type ButtonVariant =
    | 'primary'
    | 'secondary'
    | 'tertiary'
    | 'default'
    | 'success'
    | 'warning'
    | 'information'
    | 'error'
    | 'critical';
  /** Size token applied to padding and font-size. */
  export type ButtonSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

  const props = withDefaults(
    defineProps<{
      /** Visual treatment. Defaults to `'primary'`. */
      variant?: ButtonVariant;
      /** Size token controlling padding and font-size. Defaults to `'md'`. */
      size?: ButtonSize;
      /** Whether the button is non-interactive. Suppresses `click` and applies the native `disabled` attribute. */
      disabled?: boolean;
      /** Shows the spinner, sets `aria-busy`, and suppresses `click`. */
      loading?: boolean;
      /** Native `type` attribute. Defaults to `'button'` to avoid accidental form submissions. */
      type?: 'button' | 'submit' | 'reset';
    }>(),
    {
      variant: 'primary',
      size: 'md',
      disabled: false,
      loading: false,
      type: 'button',
    },
  );

  const emit = defineEmits<{
    /** Emitted on a real user click. Suppressed while `disabled` or `loading`. */
    click: [event: MouseEvent];
  }>();

  /**
   * Default slot — button label and/or icon content.
   * @slot default
   */
  defineSlots<{
    default(props: Record<string, never>): unknown;
  }>();

  const { t } = useI18n({ useScope: 'local' });

  function handleClick(event: MouseEvent) {
    if (!props.disabled && !props.loading) {
      emit('click', event);
    }
  }
</script>

<template>
  <button
    :aria-busy="loading"
    :class="['base-button', `base-button--${variant}`, `base-button--${size}`, { 'base-button--loading': loading }]"
    :disabled="disabled || loading"
    :type="type"
    @click="handleClick"
  >
    <span
      v-if="loading"
      :aria-label="t('loading')"
      aria-atomic="false"
      aria-live="off"
      class="base-button__spinner"
      role="status"
    />
    <slot />
  </button>
</template>

<style lang="scss" scoped>
  .base-button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: var(--mp-spacing-2);
    border: 1px solid transparent;
    border-radius: var(--mp-radius-md);
    font-family: var(--mp-font-family-sans);
    font-weight: var(--mp-font-weight-medium);
    line-height: var(--mp-line-height-tight);
    cursor: pointer;
    transition:
      background-color 150ms ease,
      border-color 150ms ease,
      box-shadow 150ms ease,
      opacity 150ms ease;
    white-space: nowrap;
    user-select: none;

    &:focus-visible {
      outline: none;
      box-shadow: var(--mp-shadow-focus-primary);
    }

    &:disabled {
      cursor: not-allowed;
      opacity: 0.5;
    }

    /* Sizes — canonical 2xs → 2xl scale driven by the shared size tokens. */
    @each $size in '2xs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl' {
      &--#{$size} {
        padding: var(--mp-size-pad-block-#{$size}) var(--mp-size-pad-inline-#{$size});
        font-size: var(--mp-size-font-#{$size});
      }
    }

    /* Variants */

    /* Solid fill (high emphasis) for brand / intent treatments. */
    @mixin solid($family) {
      background-color: var(--mp-color-#{$family}-default);
      color: var(--mp-color-text-on-primary);

      &:hover:not(:disabled) {
        background-color: var(--mp-color-#{$family}-hover);
      }

      &:active:not(:disabled) {
        background-color: var(--mp-color-#{$family}-active, var(--mp-color-#{$family}-hover));
      }
    }

    &--primary {
      @include solid('primary');
    }

    &--default {
      @include solid('default');
    }

    &--success {
      @include solid('success');
    }

    &--warning {
      @include solid('warning');
    }

    &--information {
      @include solid('information');
    }

    &--error {
      @include solid('error');

      &:focus-visible {
        box-shadow: var(--mp-shadow-focus-danger);
      }
    }

    &--critical {
      @include solid('critical');

      &:focus-visible {
        box-shadow: var(--mp-shadow-focus-danger);
      }
    }

    /* Secondary — outlined (medium emphasis). */
    &--secondary {
      background-color: var(--mp-color-bg-surface);
      border-color: var(--mp-color-border-default);
      color: var(--mp-color-text-primary);

      &:hover:not(:disabled) {
        background-color: var(--mp-color-bg-muted);
        border-color: var(--mp-color-border-strong);
      }

      &:active:not(:disabled) {
        background-color: var(--mp-color-bg-sunken);
      }
    }

    /* Tertiary — ghost / transparent (low emphasis). */
    &--tertiary {
      background-color: transparent;
      color: var(--mp-color-text-primary);

      &:hover:not(:disabled) {
        background-color: var(--mp-color-bg-muted);
      }

      &:active:not(:disabled) {
        background-color: var(--mp-color-bg-sunken);
      }
    }

    /* Loading spinner */
    &--loading {
      pointer-events: none;
    }

    &__spinner {
      width: 1em;
      height: 1em;
      border: 2px solid currentcolor;
      border-top-color: transparent;
      border-radius: var(--mp-radius-full);
      animation: mp-spin 0.6s linear infinite;
      flex-shrink: 0;
    }
  }

  @keyframes mp-spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>

<i18n lang="yaml">
en:
  loading: Loading…
</i18n>
