// packages/map/src/components/MapSource/MapSource.vue
<script lang="ts" setup>
  import { computed } from 'vue';

  import { useMap } from '../../composables/use-map';
  import { useSource } from '../../composables/use-source';

  import type { SourceSpecification } from 'maplibre-gl';

  export interface MapSourceProps {
    /** Unique ID for this source. Referenced by `<MapLayer>` via its `source` field. */
    id: string;
    /** MapLibre source specification. Reactively replaced when changed. */
    source: SourceSpecification;
  }

  const props = defineProps<MapSourceProps>();

  const { map } = useMap();
  const sourceRef = computed(() => props.source);

  useSource(map, { id: props.id, source: sourceRef });
</script>

<template>
  <slot />
</template>

// packages/map/src/components/molecules/map-source/map-source.tsx
import { h, type MpElement, type MpProperties, Slot } from '@mission-platform/forge';

import { useMap } from '../../../composables/use-map';
import { useSource } from '../../../composables/use-source';

import type { SourceSpecification } from 'maplibre-gl';

export interface MapSourceProperties extends MpProperties {
  /** Unique ID for this source. Referenced by `<MapLayer>` via its `source` field. */
  id: string;
  /** MapLibre source specification. Replaced (or `setData`-swapped) when changed. */
  source: SourceSpecification;
}

/**
 * `BaseMapSource` — registers a MapLibre data source on the nearest `<MapLibre>`
 * ancestor's map and renders its default slot (typically the `<MapLayer>`s that
 * reference this source). Authored once in the neutral JSX dialect.
 */
export function BaseMapSource(properties: Readonly<MapSourceProperties>): MpElement {
  const map = useMap();
  useSource(map, { id: properties.id, source: properties.source });

  return <Slot />;
}
