// packages/components/src/components/base-separator/base-separator.vue
<script lang="ts" setup>
  /**
   * `BaseSeparator` — Visual separator / divider for the Mission Platform UI.
   *
   * Renders a horizontal or vertical rule used to separate groups of content.
   * When the default slot is used (horizontal only) the separator renders a
   * centred label between two lines.
   *
   * Accessibility:
   * - By default exposes `role="separator"` with the appropriate
   *   `aria-orientation`.
   * - Set `decorative` to mark the separator as purely presentational
   *   (`role="none"`), removing it from the accessibility tree.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { computed, useSlots } from 'vue';

  /** Layout direction of the separator. */
  export type SeparatorOrientation = 'horizontal' | 'vertical';
  /** Line style. */
  export type SeparatorVariant = 'solid' | 'dashed' | 'dotted';
  /** Spacing applied as margin around the separator. */
  export type SeparatorSpacing = 'none' | 'sm' | 'md' | 'lg' | 'xl';

  const props = withDefaults(
    defineProps<{
      /** Layout direction. Defaults to `'horizontal'`. */
      orientation?: SeparatorOrientation;
      /** Line style. Defaults to `'solid'`. */
      variant?: SeparatorVariant;
      /** Margin applied along the main axis. Defaults to `'md'`. */
      spacing?: SeparatorSpacing;
      /** When `true`, removes the separator from the accessibility tree. */
      decorative?: boolean;
    }>(),
    {
      orientation: 'horizontal',
      variant: 'solid',
      spacing: 'md',
      decorative: false,
    },
  );

  /**
   * Optional default slot — a centred label rendered between two lines.
   * Only honoured when `orientation` is `'horizontal'`.
   * @slot default
   */
  defineSlots<{
    default?: (props: Record<string, never>) => unknown;
  }>();

  const slots = useSlots();

  const hasLabel = computed(() => props.orientation === 'horizontal' && !!slots.default);
</script>

<template>
  <div
    v-if="hasLabel"
    :aria-orientation="decorative ? undefined : 'horizontal'"
    :class="[
      'base-separator',
      'base-separator--labelled',
      `base-separator--${variant}`,
      `base-separator--spacing-${spacing}`,
    ]"
    :role="decorative ? 'none' : 'separator'"
  >
    <span class="base-separator__line" />
    <span class="base-separator__label">
      <slot />
    </span>
    <span class="base-separator__line" />
  </div>
  <hr
    v-else
    :aria-orientation="decorative ? undefined : orientation"
    :class="[
      'base-separator',
      `base-separator--${orientation}`,
      `base-separator--${variant}`,
      `base-separator--spacing-${spacing}`,
    ]"
    :role="decorative ? 'none' : 'separator'"
  />
</template>

<style lang="scss" scoped>
  @layer mp.components {
    .base-separator {
      border: 0;
      background: transparent;
      color: var(--mp-color-text-tertiary);

      &--horizontal {
        width: 100%;
        border-top-width: 1px;
        border-top-color: var(--mp-color-border-default);

        &.base-separator--solid {
          border-top-style: solid;
        }

        &.base-separator--dashed {
          border-top-style: dashed;
        }

        &.base-separator--dotted {
          border-top-style: dotted;
        }
      }

      &--vertical {
        align-self: stretch;
        height: auto;
        min-height: 1em;
        margin-inline: var(--mp-separator-spacing, var(--mp-spacing-4));
        border-left-width: 1px;
        border-left-color: var(--mp-color-border-default);

        &.base-separator--solid {
          border-left-style: solid;
        }

        &.base-separator--dashed {
          border-left-style: dashed;
        }

        &.base-separator--dotted {
          border-left-style: dotted;
        }
      }

      &--labelled {
        display: flex;
        align-items: center;
        gap: var(--mp-spacing-3);
        width: 100%;
      }

      &__line {
        flex: 1 1 auto;
        border-top-width: 1px;
        border-top-color: var(--mp-color-border-default);
      }

      &--labelled.base-separator--solid &__line {
        border-top-style: solid;
      }

      &--labelled.base-separator--dashed &__line {
        border-top-style: dashed;
      }

      &--labelled.base-separator--dotted &__line {
        border-top-style: dotted;
      }

      &__label {
        flex: 0 0 auto;
        font-family: var(--mp-font-family-sans);
        font-size: var(--mp-size-font-sm);
        line-height: var(--mp-line-height-tight);
        color: var(--mp-color-text-secondary);
        white-space: nowrap;
      }

      /* Spacing — applied along the main axis for the relevant orientation. */
      $spacing-map: (
        'none': var(--mp-spacing-0),
        'sm': var(--mp-spacing-2),
        'md': var(--mp-spacing-4),
        'lg': var(--mp-spacing-6),
        'xl': var(--mp-spacing-8),
      );

      @each $name, $value in $spacing-map {
        &--spacing-#{$name} {
          --mp-separator-spacing: #{$value};
        }
      }

      &--horizontal,
      &--labelled {
        margin-block: var(--mp-separator-spacing, var(--mp-spacing-4));
      }
    }
  }
</style>

// packages/components/src/components/base-separator/base-separator.tsx
import { h, type MpElement, type MpProperties } from '@mission-platform/jsx';

import sizeStyles from '../size.module.scss';
import spacingStyles from '../spacing.module.scss';

import styles from './base-separator.module.scss';

/** Layout direction of the separator. */
export type SeparatorOrientation = 'horizontal' | 'vertical';
/** Line style. */
export type SeparatorVariant = 'solid' | 'dashed' | 'dotted';
/** Spacing applied as margin around the separator. */
export type SeparatorSpacing = 'none' | 'sm' | 'md' | 'lg' | 'xl';
/** Size token — canonical 2xs → 2xl scale (scales the optional label). */
export type SeparatorSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
/** Named `padding`/`margin` scale; each step maps to a named `--mp-spacing-*` design token. */
export type SpacingScale = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface SeparatorProperties extends MpProperties {
  /** Layout direction. Defaults to `'horizontal'`. */
  orientation?: SeparatorOrientation;
  /** Line style. Defaults to `'solid'`. */
  variant?: SeparatorVariant;
  /** Margin applied along the main axis. Defaults to `'md'`. */
  spacing?: SeparatorSpacing;
  /** When `true`, removes the separator from the accessibility tree. */
  decorative?: boolean;
  /** Size token (scales the optional label). Defaults to `'md'`. */
  size?: SeparatorSize;
  /** Outer margin (named `2xs … 2xl` scale), mapped to a `--mp-spacing-*` token. Overrides `spacing` when set. */
  margin?: SpacingScale;
  /** Inner padding (named `2xs … 2xl` scale), mapped to a `--mp-spacing-*` token. */
  padding?: SpacingScale;
}

/**
 * `BaseSeparator` — a visual separator / divider authored once in the neutral
 * JSX dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * Renders a horizontal or vertical rule (`<hr>`) used to separate groups of
 * content. When default-slot content is provided (horizontal only) it renders
 * a centred label between two lines instead. By default it exposes
 * `role="separator"` with the appropriate `aria-orientation`; set `decorative`
 * to mark it purely presentational (`role="none"`).
 *
 * It owns its styling through the co-located CSS Module
 * `base-separator.module.scss` (carried onto every framework by the two-stage
 * compiler, so the component ships its own `@layer mp.components` CSS). The
 * hashed module class names are assembled with the framework-neutral
 * {@link classNames} helper.
 */
export function BaseSeparator(properties: SeparatorProperties): MpElement {
  const {
    orientation = 'horizontal',
    variant = 'solid',
    spacing = 'md',
    decorative = false,
    size = 'md',
    padding,
    margin,
  } = properties;
  const sizeClass = sizeStyles[`base-size--${size}`];

  const role = decorative ? 'none' : 'separator';
  const hasLabel = orientation === 'horizontal' && properties.children !== undefined;
  // Optional `padding`/`margin` (named `2xs … 2xl` scale) resolve to the shared
  // token-driven spacing classes (a set `margin` overrides `spacing`).
  const paddingClass = padding ? spacingStyles[`base-spacing--padding-${padding}`] : undefined;
  const marginClass = margin ? spacingStyles[`base-spacing--margin-${margin}`] : undefined;

  return hasLabel ? (
    <div
      classNames={[
        styles['base-separator'],
        styles['base-separator--labelled'],
        styles[`base-separator--${variant}`],
        styles[`base-separator--spacing-${spacing}`],
        sizeClass,
        paddingClass,
        marginClass,
      ]}
      role={role}
      aria-orientation={decorative ? undefined : 'horizontal'}
    >
      <span classNames={styles['base-separator__line']} />
      <span classNames={styles['base-separator__label']}>{properties.children}</span>
      <span classNames={styles['base-separator__line']} />
    </div>
  ) : (
    <hr
      classNames={[
        styles['base-separator'],
        styles[`base-separator--${orientation}`],
        styles[`base-separator--${variant}`],
        styles[`base-separator--spacing-${spacing}`],
        sizeClass,
        paddingClass,
        marginClass,
      ]}
      role={role}
      aria-orientation={decorative ? undefined : orientation}
    />
  );
}
