// packages/components/src/components/base-markdown-input/base-markdown-input.tsx
import {
  h,
  useEffect,
  useMemo,
  useRef,
  useState,
  type MpChild,
  type MpElement,
  type MpProperties,
} from '@mission-platform/jsx';
import { marked } from 'marked';

import { BaseTypography } from '../base-typography';
import { nextFieldId } from '../field-id';

import styles from './base-markdown-input.module.scss';

/** Field size token — canonical 2xs → 2xl scale. */
export type MarkdownInputSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
/** Which editor tab is active. */
export type MarkdownInputTab = 'write' | 'preview';

interface ToolbarItem {
  key: string;
  label: string;
  glyph: MpChild;
  prefix: string;
  suffix: string;
  defaultText: string;
}

const TOOLBAR: readonly ToolbarItem[] = [
  { key: 'bold', label: 'Bold', glyph: 'B', prefix: '**', suffix: '**', defaultText: 'bold text' },
  { key: 'italic', label: 'Italic', glyph: 'I', prefix: '_', suffix: '_', defaultText: 'italic text' },
  { key: 'heading', label: 'Heading', glyph: 'H', prefix: '## ', suffix: '', defaultText: 'Heading' },
  { key: 'code', label: 'Inline code', glyph: '</>', prefix: '`', suffix: '`', defaultText: 'code' },
  { key: 'link', label: 'Link', glyph: '🔗', prefix: '[', suffix: '](https://)', defaultText: 'link text' },
  { key: 'bulletList', label: 'Bullet list', glyph: '•', prefix: '- ', suffix: '', defaultText: 'list item' },
  { key: 'numberedList', label: 'Numbered list', glyph: '1.', prefix: '1. ', suffix: '', defaultText: 'list item' },
  { key: 'quote', label: 'Quote', glyph: '❝', prefix: '> ', suffix: '', defaultText: 'quoted text' },
];

export interface MarkdownInputProperties extends MpProperties {
  /** Markdown source (controlled via `modelValue`). */
  modelValue?: string;
  /** Visible rows of the textarea. Defaults to `6`. */
  rows?: number;
  /** Field size. Defaults to `'md'`. */
  size?: MarkdownInputSize;
  /** Placeholder text for the write area. */
  placeholder?: string;
  /** Visible label text. */
  label?: string;
  /** Visually hide the label (kept for assistive tech). */
  labelHidden?: boolean;
  /** Helper text shown below the field. */
  hint?: string;
  /** Error message shown below the field (replaces the hint). */
  error?: string;
  /** Disable the field (locks to preview). */
  disabled?: boolean;
  /** Make the field read-only (locks to preview). */
  readonly?: boolean;
  /** Mark the field as required (renders a `*` after the label). */
  required?: boolean;
  /** Explicit id; auto-generated when omitted. */
  id?: string;
  /** Fired with the next markdown source (the controlled `v-model` update). */
  onUpdateModelValue?: (value: string) => void;
  /** Fired with the native `change` event. */
  onChange?: (event: Event) => void;
  /** Fired with the native `blur` event. */
  onBlur?: (event: FocusEvent) => void;
  /** Fired with the native `focus` event. */
  onFocus?: (event: FocusEvent) => void;
}

/**
 * `BaseMarkdownInput` — a Markdown editor with a live preview authored once in
 * the neutral JSX dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * A write/preview tab bar fronts a formatting toolbar + textarea (write) and a
 * rendered preview (preview), with the HTML produced by **`marked`** (kept
 * verbatim). It owns its styling through the co-located CSS Module
 * `base-markdown-input.module.scss`.
 *
 * Substitutions from the original Vue SFC: the `v-html` preview becomes a
 * **`useRef` host + `useEffect` `innerHTML`** assignment (the `BaseWindowPopout`
 * escape-hatch), so the rendered HTML is injected on the client and the SSR
 * markup is the static shell; the `computed` render becomes {@link useMemo}; the
 * active tab `ref` becomes {@link useState}; the `@mission-platform/icons`
 * toolbar SVGs become text glyphs; the `useI18n` labels become plain strings;
 * the `useId` composable becomes `nextFieldId`; and the `v-model` + `change`/
 * `blur`/`focus` emits become the callback props.
 */
export function BaseMarkdownInput(properties: MarkdownInputProperties): MpElement {
  const {
    modelValue = '',
    rows = 6,
    size = 'md',
    placeholder = '',
    label,
    labelHidden = false,
    hint,
    error,
    disabled = false,
    readonly = false,
    required = false,
  } = properties;

  const idReference = useRef<string>(properties.id ?? nextFieldId('mp-markdown-input'));
  const resolvedId = idReference.current;
  const describedBy = error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined;

  const textareaReference = useRef<HTMLTextAreaElement | null>(null);
  const previewReference = useRef<HTMLElement | null>(null);
  const [activeTab, setActiveTab] = useState<MarkdownInputTab>('write');

  const locked = disabled || readonly;
  const effectiveTab: MarkdownInputTab = locked ? 'preview' : activeTab;

  const renderedHtml = useMemo<string>(() => (modelValue ? (marked.parse(modelValue) as string) : ''), [modelValue]);

  // Inject the rendered preview HTML on the client (the neutral dialect models
  // no `v-html`); SSR renders the empty preview shell.
  useEffect(() => {
    if (previewReference.current && effectiveTab === 'preview') {
      previewReference.current.innerHTML = renderedHtml;
    }
  }, [renderedHtml, effectiveTab]);

  const handleInput = (event: Event): void => {
    properties.onUpdateModelValue?.((event.target as HTMLTextAreaElement).value);
  };

  const applyFormat = (item: ToolbarItem): void => {
    const textarea = textareaReference.current;
    if (!textarea) {
      return;
    }
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const selected = textarea.value.slice(start, end) || item.defaultText;
    const replacement = `${item.prefix}${selected}${item.suffix}`;
    const nextValue = textarea.value.slice(0, start) + replacement + textarea.value.slice(end);
    properties.onUpdateModelValue?.(nextValue);
    requestAnimationFrame(() => {
      textarea.focus();
      const cursor = start + item.prefix.length + selected.length + item.suffix.length;
      textarea.setSelectionRange(cursor, cursor);
    });
  };

  return (
    <div
      classNames={[styles['markdown-input'], styles[`markdown-input--${size}`], {
        [styles['markdown-input--error']]: !!error,
        [styles['markdown-input--disabled']]: disabled,
        [styles['markdown-input--readonly']]: readonly,
      }]}
    >
      {label ? (
        <label
          classNames={[styles['markdown-input__label'], {
            [styles['markdown-input__label--hidden']]: labelHidden,
          }]}
          for={resolvedId}
        >
          <BaseTypography
            as="span"
            color="primary"
            variant="label"
          >
            {label}
          </BaseTypography>
          {required ? (
            <span
              aria-hidden="true"
              classNames={styles['markdown-input__required']}
              title="required"
            >
              *
            </span>
          ) : undefined}
        </label>
      ) : undefined}

      <div classNames={styles['markdown-input__editor']}>
        {locked ? undefined : (
          <div
            classNames={styles['markdown-input__tabs']}
            role="tablist"
          >
            <button
              aria-controls={`${resolvedId}-write-panel`}
              aria-selected={effectiveTab === 'write'}
              classNames={[styles['markdown-input__tab'], {
                [styles['markdown-input__tab--active']]: effectiveTab === 'write',
              }]}
              role="tab"
              type="button"
              onClick={() => setActiveTab('write')}
            >
              Write
            </button>
            <button
              aria-controls={`${resolvedId}-preview-panel`}
              aria-selected={effectiveTab === 'preview'}
              classNames={[styles['markdown-input__tab'], {
                [styles['markdown-input__tab--active']]: effectiveTab === 'preview',
              }]}
              role="tab"
              type="button"
              onClick={() => setActiveTab('preview')}
            >
              Preview
            </button>
          </div>
        )}

        {effectiveTab === 'write' ? (
          <div
            aria-label={label ?? 'Markdown toolbar'}
            classNames={styles['markdown-input__toolbar']}
            role="toolbar"
          >
            {TOOLBAR.map((item) => (
              <button
                key={item.key}
                aria-label={item.label}
                classNames={styles['markdown-input__tool']}
                disabled={disabled}
                title={item.label}
                type="button"
                onClick={() => applyFormat(item)}
              >
                <span aria-hidden="true">{item.glyph}</span>
              </button>
            ))}
          </div>
        ) : undefined}

        {effectiveTab === 'write' ? (
          <div
            id={`${resolvedId}-write-panel`}
            classNames={styles['markdown-input__panel']}
          >
            <textarea
              id={resolvedId}
              ref={textareaReference}
              aria-describedby={describedBy}
              aria-invalid={error ? 'true' : undefined}
              classNames={styles['markdown-input__textarea']}
              disabled={disabled}
              placeholder={placeholder}
              readonly={readonly}
              required={required}
              rows={rows}
              value={modelValue}
              onBlur={(event: FocusEvent) => properties.onBlur?.(event)}
              onChange={(event: Event) => properties.onChange?.(event)}
              onFocus={(event: FocusEvent) => properties.onFocus?.(event)}
              onInput={handleInput}
            />
          </div>
        ) : (
          <div
            id={`${resolvedId}-preview-panel`}
            ref={previewReference}
            classNames={styles['markdown-input__preview']}
          />
        )}
      </div>

      {error ? (
        <p
          id={`${resolvedId}-error`}
          classNames={styles['markdown-input__error']}
          role="alert"
        >
          <BaseTypography
            as="span"
            color="inherit"
            variant="caption"
          >
            {error}
          </BaseTypography>
        </p>
      ) : hint ? (
        <p
          id={`${resolvedId}-hint`}
          classNames={styles['markdown-input__hint']}
        >
          <BaseTypography
            as="span"
            color="secondary"
            variant="caption"
          >
            {hint}
          </BaseTypography>
        </p>
      ) : undefined}
    </div>
  );
}

// packages/components/src/components/base-markdown-input/base-markdown-input.vue
<script lang="ts" setup>
  import { useI18n } from '@mission-platform/i18n';
  import {
    IconBlockquote,
    IconBold,
    IconBulletList,
    IconCodeInline,
    IconExternalLink,
    IconHeading,
    IconItalic,
    IconNumberedList,
  } from '@mission-platform/icons';
  import { marked } from 'marked';
  import { computed, ref } from 'vue';

  import { useId } from '../../composables/use-id';
  import BaseTypography from '../base-typography/base-typography.vue';

  export type MarkdownInputSize = 'sm' | 'md' | 'lg';
  export type MarkdownInputTab = 'write' | 'preview';

  const props = withDefaults(
    defineProps<{
      modelValue?: string;
      rows?: number;
      size?: MarkdownInputSize;
      placeholder?: string;
      label?: string;
      labelHidden?: boolean;
      hint?: string;
      error?: string;
      disabled?: boolean;
      readonly?: boolean;
      required?: boolean;
      id?: string;
    }>(),
    {
      modelValue: '',
      rows: 6,
      size: 'md',
      placeholder: '',
      label: undefined,
      labelHidden: false,
      hint: undefined,
      error: undefined,
      disabled: false,
      readonly: false,
      required: false,
      id: undefined,
    },
  );

  const emit = defineEmits<{
    'update:modelValue': [value: string];
    change: [event: Event];
    blur: [event: FocusEvent];
    focus: [event: FocusEvent];
  }>();

  const { t } = useI18n({ useScope: 'local' });

  const { id: resolvedId } = useId(props.id);
  const activeTab = ref<MarkdownInputTab>('write');
  const effectiveTab = computed<MarkdownInputTab>(() =>
    props.disabled || props.readonly ? 'preview' : activeTab.value,
  );
  const textareaRef = ref<HTMLTextAreaElement | null>(null);

  const renderedHtml = computed(() => {
    if (!props.modelValue) return '';
    return marked(props.modelValue) as string;
  });

  function handleInput(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    emit('update:modelValue', target.value);
  }

  /** Insert or wrap text at the current cursor position / selection. */
  function applyFormat(prefix: string, suffix = '', defaultText = '') {
    const textarea = textareaRef.value;
    if (!textarea) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const selected = textarea.value.slice(start, end) || defaultText;
    const replacement = `${prefix}${selected}${suffix}`;
    const newValue = textarea.value.slice(0, start) + replacement + textarea.value.slice(end);

    emit('update:modelValue', newValue);

    // restore cursor after Vue re-renders
    requestAnimationFrame(() => {
      textarea.focus();
      const cursorPos = start + prefix.length + selected.length + suffix.length;
      textarea.setSelectionRange(cursorPos, cursorPos);
    });
  }

  const toolbar: Array<{ key: string; label: () => string; icon: unknown; action: () => void }> = [
    {
      key: 'bold',
      label: () => t('bold'),
      icon: IconBold,
      action: () => applyFormat('**', '**', 'bold text'),
    },
    {
      key: 'italic',
      label: () => t('italic'),
      icon: IconItalic,
      action: () => applyFormat('_', '_', 'italic text'),
    },
    {
      key: 'heading',
      label: () => t('heading'),
      icon: IconHeading,
      action: () => applyFormat('## ', '', 'Heading'),
    },
    {
      key: 'code',
      label: () => t('code'),
      icon: IconCodeInline,
      action: () => applyFormat('`', '`', 'code'),
    },
    {
      key: 'link',
      label: () => t('link'),
      icon: IconExternalLink,
      action: () => applyFormat('[', '](url)', 'link text'),
    },
    {
      key: 'bulletList',
      label: () => t('bulletList'),
      icon: IconBulletList,
      action: () => applyFormat('- ', '', 'list item'),
    },
    {
      key: 'numberedList',
      label: () => t('numberedList'),
      icon: IconNumberedList,
      action: () => applyFormat('1. ', '', 'list item'),
    },
    {
      key: 'quote',
      label: () => t('quote'),
      icon: IconBlockquote,
      action: () => applyFormat('> ', '', 'quoted text'),
    },
  ];
</script>

<template>
  <div
    :class="[
      'markdown-input',
      `markdown-input--${size}`,
      {
        'markdown-input--error': !!error,
        'markdown-input--disabled': disabled,
        'markdown-input--readonly': readonly,
      },
    ]"
  >
    <label
      v-if="label"
      :class="['markdown-input__label', { 'markdown-input__label--hidden': labelHidden }]"
      :for="resolvedId"
    >
      <BaseTypography
        as="span"
        color="primary"
        variant="label"
      >
        {{ label }}
      </BaseTypography>
      <span
        v-if="required"
        :title="t('required')"
        aria-hidden="true"
        class="markdown-input__required"
      >
        *
      </span>
    </label>

    <div class="markdown-input__editor">
      <!-- Tab bar — hidden when component is locked to preview (disabled or readonly) -->
      <div
        v-if="!disabled && !readonly"
        class="markdown-input__tabs"
        role="tablist"
      >
        <button
          :aria-controls="`${resolvedId}-write-panel`"
          :aria-selected="effectiveTab === 'write'"
          :class="['markdown-input__tab', { 'markdown-input__tab--active': effectiveTab === 'write' }]"
          role="tab"
          type="button"
          @click="activeTab = 'write'"
        >
          <BaseTypography
            as="span"
            color="inherit"
            variant="label"
          >
            {{ t('write') }}
          </BaseTypography>
        </button>
        <button
          :aria-controls="`${resolvedId}-preview-panel`"
          :aria-selected="effectiveTab === 'preview'"
          :class="['markdown-input__tab', { 'markdown-input__tab--active': effectiveTab === 'preview' }]"
          role="tab"
          type="button"
          @click="activeTab = 'preview'"
        >
          <BaseTypography
            as="span"
            color="inherit"
            variant="label"
          >
            {{ t('preview') }}
          </BaseTypography>
        </button>
      </div>

      <!-- Toolbar (visible only on write tab) -->
      <div
        v-if="effectiveTab === 'write'"
        :aria-label="label ?? 'Markdown toolbar'"
        class="markdown-input__toolbar"
        role="toolbar"
      >
        <button
          v-for="item in toolbar"
          :key="item.key"
          :aria-label="item.label()"
          :disabled="disabled"
          :title="item.label()"
          class="markdown-input__tool"
          type="button"
          @click="item.action()"
        >
          <component
            :is="item.icon"
            size="sm"
          />
        </button>
      </div>

      <!-- Write panel -->
      <div
        v-show="effectiveTab === 'write'"
        :id="`${resolvedId}-write-panel`"
        class="markdown-input__panel"
        role="tabpanel"
      >
        <textarea
          :id="resolvedId"
          ref="textareaRef"
          :aria-describedby="error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined"
          :aria-invalid="!!error || undefined"
          :disabled="disabled"
          :placeholder="placeholder"
          :readonly="readonly"
          :required="required"
          :rows="rows"
          :value="modelValue"
          class="markdown-input__field"
          @blur="emit('blur', $event)"
          @change="emit('change', $event)"
          @focus="emit('focus', $event)"
          @input="handleInput"
        />
      </div>

      <!-- Preview panel -->
      <div
        v-show="effectiveTab === 'preview'"
        :id="`${resolvedId}-preview-panel`"
        class="markdown-input__panel markdown-input__preview"
        role="tabpanel"
      >
        <!-- eslint-disable vue/no-v-html -->
        <article
          v-if="renderedHtml"
          class="markdown-input__preview-content"
          v-html="renderedHtml"
        />
        <!-- eslint-enable vue/no-v-html -->
        <BaseTypography
          v-else
          as="p"
          class="markdown-input__preview-empty"
          color="tertiary"
          variant="body-sm"
        >
          {{ t('emptyPreview') }}
        </BaseTypography>
      </div>
    </div>

    <BaseTypography
      v-if="error"
      :id="`${resolvedId}-error`"
      as="p"
      class="markdown-input__error"
      color="inherit"
      role="alert"
      variant="caption"
    >
      {{ error }}
    </BaseTypography>
    <BaseTypography
      v-else-if="hint"
      :id="`${resolvedId}-hint`"
      as="p"
      class="markdown-input__hint"
      color="secondary"
      variant="caption"
    >
      {{ hint }}
    </BaseTypography>
  </div>
</template>

<style lang="scss" scoped>
  .markdown-input {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-1);

    &__label {
      &--hidden {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip-path: inset(50%);
        white-space: nowrap;
        border: 0;
      }
    }

    &__required {
      color: var(--mp-color-danger-default);
      margin-left: 2px;
    }

    &__editor {
      display: flex;
      flex-direction: column;
      border: 1px solid var(--mp-color-border-default);
      border-radius: var(--mp-radius-md);
      overflow: hidden;
      transition:
        border-color 150ms ease,
        box-shadow 150ms ease;

      &:focus-within {
        border-color: var(--mp-color-border-focus);
        box-shadow: var(--mp-shadow-focus-primary);
      }
    }

    /* Tabs */
    &__tabs {
      display: flex;
      border-bottom: 1px solid var(--mp-color-border-default);
      background-color: var(--mp-color-bg-subtle, var(--mp-color-bg-muted));
    }

    &__tab {
      display: inline-flex;
      align-items: center;
      padding: var(--mp-spacing-1) var(--mp-spacing-3);
      color: var(--mp-color-text-secondary);
      background: none;
      border: none;
      border-bottom: 2px solid transparent;
      cursor: pointer;
      transition:
        color 150ms ease,
        border-color 150ms ease;

      &--active {
        color: var(--mp-color-text-primary);
        border-bottom-color: var(--mp-color-primary-default);
      }

      &:hover {
        color: var(--mp-color-text-primary);
      }
    }

    /* Toolbar */
    &__toolbar {
      display: flex;
      flex-wrap: wrap;
      gap: var(--mp-spacing-1);
      padding: var(--mp-spacing-1) var(--mp-spacing-2);
      border-bottom: 1px solid var(--mp-color-border-default);
      background-color: var(--mp-color-bg-surface);
    }

    &__tool {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      padding: var(--mp-spacing-1);
      color: var(--mp-color-text-secondary);
      background: none;
      border: 1px solid var(--mp-color-border-default);
      border-radius: var(--mp-radius-sm);
      cursor: pointer;
      transition:
        background-color 150ms ease,
        color 150ms ease;

      &:disabled {
        color: var(--mp-color-text-disabled);
        cursor: not-allowed;
      }

      &:hover:not(:disabled) {
        background-color: var(--mp-color-bg-muted);
        color: var(--mp-color-text-primary);
      }
    }

    /* Panels */
    &__panel {
      flex: 1;
    }

    &__field {
      width: 100%;
      box-sizing: border-box;
      border: none;
      background-color: var(--mp-color-bg-surface);
      color: var(--mp-color-text-primary);
      font-family: var(--mp-font-family-mono, var(--mp-font-family-sans));
      line-height: var(--mp-line-height-normal);
      outline: none;
      resize: vertical;

      &::placeholder {
        color: var(--mp-color-text-tertiary);
      }
    }

    &__preview {
      background-color: var(--mp-color-bg-surface);
    }

    &__preview-content {
      color: var(--mp-color-text-primary);
      line-height: var(--mp-line-height-normal);

      :deep(h1),
      :deep(h2),
      :deep(h3),
      :deep(h4) {
        margin: var(--mp-spacing-2) 0 var(--mp-spacing-1);
        font-weight: var(--mp-font-weight-semibold);
      }

      :deep(p) {
        margin: 0 0 var(--mp-spacing-2);
      }

      :deep(ul),
      :deep(ol) {
        margin: 0 0 var(--mp-spacing-2);
        padding-left: var(--mp-spacing-5);
      }

      :deep(code) {
        font-family: var(--mp-font-family-mono, monospace);
        background-color: var(--mp-color-bg-muted);
        padding: 1px 4px;
        border-radius: var(--mp-radius-sm);
      }

      :deep(pre) {
        background-color: var(--mp-color-bg-muted);
        padding: var(--mp-spacing-3);
        border-radius: var(--mp-radius-md);
        overflow-x: auto;
      }

      :deep(blockquote) {
        margin: 0 0 var(--mp-spacing-2);
        padding-left: var(--mp-spacing-3);
        border-left: 3px solid var(--mp-color-border-default);
        color: var(--mp-color-text-secondary);
      }

      :deep(a) {
        color: var(--mp-color-primary-text);
        text-decoration: underline;
      }
    }

    &__preview-empty {
      margin: 0;
      font-style: italic;
    }

    /* Sizes */
    &--sm {
      .markdown-input__field,
      .markdown-input__preview-content {
        padding: var(--mp-spacing-1) var(--mp-spacing-2);
        font-size: var(--mp-font-size-sm);
      }

      .markdown-input__preview-empty {
        padding: var(--mp-spacing-1) var(--mp-spacing-2);
      }
    }

    &--md {
      .markdown-input__field,
      .markdown-input__preview-content {
        padding: var(--mp-spacing-2) var(--mp-spacing-3);
        font-size: var(--mp-font-size-md);
      }

      .markdown-input__preview-empty {
        padding: var(--mp-spacing-2) var(--mp-spacing-3);
      }
    }

    &--lg {
      .markdown-input__field,
      .markdown-input__preview-content {
        padding: var(--mp-spacing-3) var(--mp-spacing-4);
        font-size: var(--mp-font-size-lg);
      }

      .markdown-input__preview-empty {
        padding: var(--mp-spacing-3) var(--mp-spacing-4);
      }
    }

    /* Error state */
    &--error {
      .markdown-input__editor {
        border-color: var(--mp-color-danger-default);

        &:focus-within {
          box-shadow: var(--mp-shadow-focus-danger);
        }
      }
    }

    /* Disabled state */
    &--disabled {
      pointer-events: none;

      .markdown-input__editor {
        background-color: var(--mp-color-bg-muted);
      }

      .markdown-input__field {
        background-color: var(--mp-color-bg-muted);
        color: var(--mp-color-text-disabled);
        cursor: not-allowed;
      }

      .markdown-input__preview-content {
        color: var(--mp-color-text-disabled);
      }

      .markdown-input__preview-empty {
        color: var(--mp-color-text-disabled);

        :deep(.base-typography) {
          color: var(--mp-color-text-disabled);
        }
      }
    }

    /* Readonly state */
    &--readonly {
      .markdown-input__editor {
        border-color: var(--mp-color-border-default);

        &:focus-within {
          border-color: var(--mp-color-border-default);
          box-shadow: none;
        }
      }
    }

    &__error {
      color: var(--mp-color-danger-text);
      margin: 0;
    }

    &__hint {
      margin: 0;
    }
  }
</style>

<i18n lang="yaml">
en:
  required: required
  write: Write
  preview: Preview
  bold: Bold
  italic: Italic
  heading: Heading
  link: Link
  bulletList: Bullet list
  numberedList: Numbered list
  quote: Blockquote
  code: Inline code
  emptyPreview: Nothing to preview.
</i18n>
