// packages/map/src/components/map-libre/map-libre.tsx
import {
  classNames,
  h,
  Slot,
  useEffect,
  useRef,
  useState,
  type MpElement,
  type MpProperties,
} from '@mission-platform/jsx';
import { LngLat, Map, type MapMouseEvent, type MapOptions } from 'maplibre-gl';

import { centerDiffers, scalarDiffers } from '../../utils/camera';
import { MapContext } from '../map-context';

import styles from './map-libre.module.scss';

export interface MapLibreProperties extends MpProperties {
  /** MapLibre style URL or inline style object. */
  readonly mapStyle: MapOptions['style'];
  /** Initial map center as `[lng, lat]`. Defaults to `[0, 0]`. */
  center?: Required<MapOptions['center']>;
  /** Initial zoom level. Defaults to `1`. */
  zoom?: Required<MapOptions['zoom']>;
  /** Minimum allowed zoom level. */
  minZoom?: Required<MapOptions['minZoom']>;
  /** Maximum allowed zoom level. */
  maxZoom?: Required<MapOptions['maxZoom']>;
  /** Initial bearing (rotation) in degrees. Defaults to `0`. */
  bearing?: Required<MapOptions['bearing']>;
  /** Initial pitch in degrees. Defaults to `0`. */
  pitch?: Required<MapOptions['pitch']>;
  /** Whether to use cooperative gesture handling (requires Ctrl/⌘ + scroll). */
  cooperativeGestures?: Required<MapOptions['cooperativeGestures']>;
  /**
   * Attribution control options. Pass `false` to hide it entirely, or an
   * `AttributionControlOptions` object to customise it.
   */
  attributionControl?: Required<MapOptions['attributionControl']>;
  /** Fired when the map has finished loading its initial style. */
  onLoad?: (map: Map) => void;
  /** Fired whenever the map moves (pan/zoom/rotate). */
  onMove?: (map: Map) => void;
  /** Fired when the user clicks on the map canvas. */
  onClick?: (event: MapMouseEvent) => void;
  /** Fired when the user right-clicks on the map canvas. */
  onContextmenu?: (event: MapMouseEvent) => void;
}

/**
 * `BaseMapLibre` — a MapLibre GL map container authored once in the neutral JSX
 * dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * It creates the MapLibre `Map` after mount, provides the loaded instance to its
 * descendants through {@link MapContext} (only rendering its children — the
 * default slot — once the map has loaded), and reactively syncs the `mapStyle`,
 * `center`, `zoom`, `bearing`, and `pitch` props onto the live map. It owns its
 * styling through the co-located CSS Module `map-libre.module.scss` (its own
 * `@layer mp.map` CSS).
 */
export function BaseMapLibre(properties: Readonly<MapLibreProperties>): MpElement {
  const {
    mapStyle,
    center = [0, 0],
    zoom = 1,
    minZoom,
    maxZoom,
    bearing = 0,
    pitch = 0,
    cooperativeGestures = false,
    attributionControl,
  } = properties;

  const containerReference = useRef<HTMLDivElement | null>(null);
  const mapReference = useRef<Map | undefined>(undefined);
  const [map, setMap] = useState<Map | undefined>(undefined);

  useEffect(() => {
    const container = containerReference.current;
    if (!container) {
      return;
    }

    const instance = new Map({
      container,
      style: mapStyle,
      center,
      zoom,
      minZoom,
      maxZoom,
      bearing,
      pitch,
      cooperativeGestures,
      attributionControl,
    });
    mapReference.current = instance;

    instance.on('load', () => {
      setMap(instance);
      properties.onLoad?.(instance);
    });
    instance.on('move', () => {
      properties.onMove?.(instance);
    });
    instance.on('click', (event) => {
      properties.onClick?.(event);
    });
    instance.on('contextmenu', (event) => {
      properties.onContextmenu?.(event);
    });

    return () => {
      instance.remove();
      mapReference.current = undefined;
      setMap(undefined);
    };
  }, []);

  useEffect(() => {
    if (mapStyle !== undefined) {
      mapReference.current?.setStyle(mapStyle);
    }
  }, [mapStyle]);

  useEffect(() => {
    const instance = mapReference.current;
    // Only re-centre when the target differs from the live centre: re-applying an
    // echoed value (the controlled `onMove` → state → prop round-trip) would emit
    // another `move` and loop, drifting the map north.
    if (instance && center && centerDiffers(instance.getCenter(), LngLat.convert(center))) {
      instance.setCenter(center);
    }
  }, [center]);

  useEffect(() => {
    const instance = mapReference.current;
    if (instance && zoom !== undefined && scalarDiffers(instance.getZoom(), zoom)) {
      instance.setZoom(zoom);
    }
  }, [zoom]);

  useEffect(() => {
    const instance = mapReference.current;
    if (instance && bearing !== undefined && scalarDiffers(instance.getBearing(), bearing)) {
      instance.setBearing(bearing);
    }
  }, [bearing]);

  useEffect(() => {
    const instance = mapReference.current;
    if (instance && pitch !== undefined && scalarDiffers(instance.getPitch(), pitch)) {
      instance.setPitch(pitch);
    }
  }, [pitch]);

  return (
    <div
      ref={containerReference}
      classNames={classNames(styles['map-libre'])}
    >
      {map ? (
        <MapContext.Provider value={map}>
          <Slot />
        </MapContext.Provider>
      ) : undefined}
    </div>
  );
}

// packages/map/src/components/MapLibre/MapLibre.vue
<script setup lang="ts">
import { markRaw, onMounted, onUnmounted, provide, shallowRef, watch } from 'vue'
import { Map, type MapOptions } from 'maplibre-gl'
import type { MapMouseEvent } from 'maplibre-gl'

import { mapKey } from '../../composables/injectionKeys'

export interface MapLibreProps {
  /** MapLibre style URL or inline style object. */
  mapStyle: MapOptions['style']
  /** Initial map center as `[lng, lat]`. Defaults to `[0, 0]`. */
  center?: MapOptions['center']
  /** Initial zoom level. Defaults to `1`. */
  zoom?: MapOptions['zoom']
  /** Minimum allowed zoom level. */
  minZoom?: MapOptions['minZoom']
  /** Maximum allowed zoom level. */
  maxZoom?: MapOptions['maxZoom']
  /** Initial bearing (rotation) in degrees. Defaults to `0`. */
  bearing?: MapOptions['bearing']
  /** Initial pitch in degrees. Defaults to `0`. */
  pitch?: MapOptions['pitch']
  /** Whether to use cooperative gesture handling (requires Ctrl/⌘ + scroll). */
  cooperativeGestures?: MapOptions['cooperativeGestures']
  /**
   * Attribution control options. Pass `false` to hide it entirely, or an
   * `AttributionControlOptions` object to customise it. Defaults to `undefined`
   * (MapLibre shows the default attribution control).
   */
  attributionControl?: MapOptions['attributionControl']
}

const props = withDefaults(defineProps<MapLibreProps>(), {
  center: () => [0, 0],
  zoom: 1,
  minZoom: undefined,
  maxZoom: undefined,
  bearing: 0,
  pitch: 0,
  cooperativeGestures: false,
  attributionControl: undefined,
})

const emit = defineEmits<{
  /** Fired when the map has finished loading its initial style. */
  load: [map: Map]
  /** Fired whenever the map moves (pan/zoom/rotate). */
  move: [map: Map]
  /** Fired when the user clicks on the map canvas. */
  click: [event: MapMouseEvent]
  /** Fired when the user right-clicks on the map canvas. */
  contextmenu: [event: MapMouseEvent]
}>()

const containerRef = shallowRef<HTMLDivElement | null>(null)
const map = shallowRef<Map | null>(null)

provide(mapKey, map)

onMounted(() => {
  if (!containerRef.value) return

  const instance = new Map({
    container: containerRef.value,
    style: props.mapStyle,
    center: props.center,
    zoom: props.zoom,
    minZoom: props.minZoom,
    maxZoom: props.maxZoom,
    bearing: props.bearing,
    pitch: props.pitch,
    cooperativeGestures: props.cooperativeGestures,
    attributionControl: props.attributionControl,
  })

  instance.on('load', () => {
    map.value = markRaw(instance)
    emit('load', instance)
  })

  instance.on('move', () => {
    emit('move', instance)
  })

  instance.on('click', (event) => {
    emit('click', event)
  })

  instance.on('contextmenu', (event) => {
    emit('contextmenu', event)
  })
})

onUnmounted(() => {
  map.value?.remove()
  map.value = null
})

watch(
  () => props.mapStyle,
  (style) => {
    if (style !== undefined) map.value?.setStyle(style)
  },
)

watch(
  () => props.center,
  (center) => {
    if (center) map.value?.setCenter(center)
  },
)

watch(
  () => props.zoom,
  (zoom) => {
    if (zoom !== undefined) map.value?.setZoom(zoom)
  },
)

watch(
  () => props.bearing,
  (bearing) => {
    if (bearing !== undefined) map.value?.setBearing(bearing)
  },
)

watch(
  () => props.pitch,
  (pitch) => {
    if (pitch !== undefined) map.value?.setPitch(pitch)
  },
)
</script>

<template>
  <div ref="containerRef" class="map-libre">
    <template v-if="map">
      <slot />
    </template>
  </div>
</template>

<style scoped>
.map-libre {
  position: relative;
  width: 100%;
  height: 100%;
}
</style>
