// packages/components/src/components/BaseFileInput/BaseFileInput.vue
<script lang="ts" setup>
  import { useI18n } from '@mission-platform/i18n';
  import { IconUpload } from '@mission-platform/icons';
  import { ref } from 'vue';

  import { useId } from '../../composables/use-id';
  import BaseTypography from '../BaseTypography/BaseTypography.vue';

  const props = withDefaults(
    defineProps<{
      modelValue?: File | File[] | null;
      multiple?: boolean;
      accept?: string;
      label?: string;
      labelHidden?: boolean;
      hint?: string;
      error?: string;
      disabled?: boolean;
      required?: boolean;
      id?: string;
      dragDrop?: boolean;
    }>(),
    {
      modelValue: null,
      multiple: false,
      accept: undefined,
      label: undefined,
      labelHidden: false,
      hint: undefined,
      error: undefined,
      disabled: false,
      required: false,
      id: undefined,
      dragDrop: false,
    },
  );

  const emit = defineEmits<{
    'update:modelValue': [value: File | File[] | null];
    change: [files: FileList | null];
  }>();

  const { t } = useI18n({ useScope: 'local' });

  const { id: resolvedId } = useId(props.id);
  const isDragging = ref(false);
  const displayName = ref('');

  function handleFiles(files: FileList | null) {
    if (!files || files.length === 0) {
      emit('update:modelValue', null);
      emit('change', null);
      displayName.value = '';
      return;
    }
    const result = props.multiple ? Array.from(files) : files[0];
    emit('update:modelValue', result);
    emit('change', files);
    displayName.value = props.multiple ? `${files.length} file${files.length > 1 ? 's' : ''} selected` : files[0].name;
  }

  function handleInputChange(event: Event) {
    const input = event.target as HTMLInputElement;
    handleFiles(input.files);
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault();
    isDragging.value = false;
    if (props.disabled) return;
    handleFiles(event.dataTransfer?.files ?? null);
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
    if (!props.disabled) isDragging.value = true;
  }

  function handleDragLeave() {
    isDragging.value = false;
  }
</script>

<template>
  <div :class="['base-file-input', { 'base-file-input--error': !!error, 'base-file-input--disabled': disabled }]">
    <label
      v-if="label"
      :class="['base-file-input__label', { 'base-file-input__label--hidden': labelHidden }]"
      :for="resolvedId"
    >
      <BaseTypography
        as="span"
        color="primary"
        variant="label"
      >{{ label }}</BaseTypography>
      <span
        v-if="required"
        :title="t('required')"
        aria-hidden="true"
        class="base-file-input__required"
      >*</span>
    </label>

    <div
      v-if="dragDrop"
      :class="['base-file-input__dropzone', { 'base-file-input__dropzone--active': isDragging }]"
      role="presentation"
      @dragleave="handleDragLeave"
      @dragover="handleDragOver"
      @drop="handleDrop"
    >
      <IconUpload
        class="base-file-input__icon"
        size="xl"
      />
      <p class="base-file-input__drop-text">
        {{ t('drag') }}
        <label
          :for="resolvedId"
          class="base-file-input__browse-link"
        >{{ t('browse') }}</label>
      </p>
      <p
        v-if="displayName"
        class="base-file-input__file-name"
      >
        {{ displayName }}
      </p>
    </div>

    <div
      v-else
      class="base-file-input__row"
    >
      <label
        :class="{ 'base-file-input__button--disabled': disabled }"
        :for="resolvedId"
        class="base-file-input__button"
      >
        {{ t('browse') }}
      </label>
      <span class="base-file-input__name">{{ displayName || t('noFile') }}</span>
    </div>

    <input
      :id="resolvedId"
      :accept="accept"
      :aria-describedby="error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined"
      :aria-invalid="!!error || undefined"
      :disabled="disabled"
      :multiple="multiple"
      :required="required"
      class="base-file-input__native"
      type="file"
      @change="handleInputChange"
    >
    <BaseTypography
      v-if="error"
      :id="`${resolvedId}-error`"
      as="p"
      class="base-file-input__error"
      color="inherit"
      role="alert"
      variant="caption"
    >
      {{ error }}
    </BaseTypography>
    <BaseTypography
      v-else-if="hint"
      :id="`${resolvedId}-hint`"
      as="p"
      class="base-file-input__hint"
      color="secondary"
      variant="caption"
    >
      {{ hint }}
    </BaseTypography>
  </div>
</template>

<style lang="scss" scoped>
  .base-file-input {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-1);

    &__label {
      /* typography handled by BaseTypography */

      &--hidden {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip-path: inset(50%);
        white-space: nowrap;
        border: 0;
      }
    }

    &__required {
      color: var(--mp-color-danger-default);
      margin-left: 2px;
    }

    &__native {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip-path: inset(50%);
      white-space: nowrap;
      border: 0;
    }

    &__row {
      display: flex;
      align-items: center;
      gap: var(--mp-spacing-3);
    }

    &__button {
      display: inline-flex;
      align-items: center;
      padding: var(--mp-spacing-2) var(--mp-spacing-4);
      font-size: var(--mp-font-size-sm);
      font-weight: var(--mp-font-weight-medium);
      color: var(--mp-color-text-primary);
      background-color: var(--mp-color-bg-surface);
      border: 1px solid var(--mp-color-border-default);
      border-radius: var(--mp-radius-md);
      cursor: pointer;
      white-space: nowrap;
      transition:
        background-color 150ms ease,
        border-color 150ms ease;

      &--disabled {
        background-color: var(--mp-color-bg-muted);
        color: var(--mp-color-text-disabled);
        cursor: not-allowed;
      }

      &:hover:not(&--disabled) {
        background-color: var(--mp-color-bg-muted);
        border-color: var(--mp-color-border-strong);
      }
    }

    &__name {
      font-size: var(--mp-font-size-sm);
      color: var(--mp-color-text-secondary);
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    &__dropzone {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: var(--mp-spacing-2);
      padding: var(--mp-spacing-8) var(--mp-spacing-4);
      border: 2px dashed var(--mp-color-border-default);
      border-radius: var(--mp-radius-lg);
      background-color: var(--mp-color-bg-surface);
      transition:
        border-color 150ms ease,
        background-color 150ms ease;
      cursor: pointer;
      text-align: center;

      &--active {
        border-color: var(--mp-color-primary-default);
        background-color: var(--mp-color-primary-subtle);
      }
    }

    &__icon {
      color: var(--mp-color-text-tertiary);
    }

    &__drop-text {
      margin: 0;
      font-size: var(--mp-font-size-sm);
      color: var(--mp-color-text-secondary);
    }

    &__browse-link {
      color: var(--mp-color-primary-text);
      cursor: pointer;
      font-weight: var(--mp-font-weight-medium);
      text-decoration: underline;

      &:hover {
        color: var(--mp-color-text-primary);
      }
    }

    &__file-name {
      margin: 0;
      font-size: var(--mp-font-size-sm);
      color: var(--mp-color-text-primary);
      font-weight: var(--mp-font-weight-medium);
    }

    &--error {
      .base-file-input__button,
      .base-file-input__dropzone {
        border-color: var(--mp-color-danger-default);
      }
    }

    &--disabled {
      pointer-events: none;

      .base-file-input__label,
      .base-file-input__name,
      .base-file-input__drop-text,
      .base-file-input__file-name {
        color: var(--mp-color-text-disabled);
      }

      .base-file-input__dropzone {
        background-color: var(--mp-color-bg-muted);
        color: var(--mp-color-text-disabled);
        cursor: not-allowed;
      }
    }

    &__error {
      color: var(--mp-color-danger-text);
      margin: 0;
    }

    &__hint {
      margin: 0;
    }
  }
</style>

<i18n lang="yaml">
en:
  required: required
  browse: Browse files
  drag: Drag & drop files here or
  noFile: No file chosen
</i18n>

// packages/components/src/components/base-file-input/base-file-input.tsx
import { IconUpload } from '@mission-platform/icons';
import { h, useId, useState, type MpElement, type MpProperties } from '@mission-platform/jsx';

import { BaseTypography } from '../base-typography';

import styles from './base-file-input.module.scss';

/** Field size token — canonical 2xs → 2xl scale. */
export type FileInputSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface FileInputProperties extends MpProperties {
  /**
   * Selected file(s) (controlled via `modelValue` + `onUpdateModelValue`).
   * @model onUpdateModelValue
   */
  modelValue?: File | File[];
  /** Allow selecting multiple files. */
  multiple?: boolean;
  /** Native `accept` token list (e.g. `'image/*,.pdf'`). */
  accept?: string;
  /** Native `capture` hint (prefer a device camera/microphone). */
  capture?: boolean | 'user' | 'environment';
  /** Field size. Defaults to `'md'`. */
  size?: FileInputSize;
  /** Visible label text. */
  label?: string;
  /** Visually hide the label (kept for assistive tech). */
  labelHidden?: boolean;
  /** Helper text shown below the control. */
  hint?: string;
  /** Error message shown below the control (replaces the hint). */
  error?: string;
  /** Disable the control. */
  disabled?: boolean;
  /** Mark the field as required (renders a `*` after the label). */
  required?: boolean;
  /** Explicit id; auto-generated when omitted. */
  id?: string;
  /** Render a drag-and-drop dropzone instead of the browse button row. */
  dragDrop?: boolean;
  /** "Browse" action label. Defaults to `'Browse files'`. */
  browseLabel?: string;
  /** Dropzone prompt label. Defaults to `'Drag & drop files here or'`. */
  dragLabel?: string;
  /** Empty-state label. Defaults to `'No file chosen'`. */
  noFileLabel?: string;
  /** Fired with the next file selection (the controlled `v-model` update). */
  onUpdateModelValue?: (value?: File | File[]) => void;
  /** Fired with the native `FileList` (omitted when cleared) when the selection changes. */
  onChange?: (files?: FileList) => void;
}

/**
 * `BaseFileInput` — file input authored once in the neutral JSX dialect and
 * compiled straight to React or Vue by `@mission-platform/vite-plugin-jsx`.
 *
 * Wraps a visually-hidden native `<input type="file">` with either a browse
 * button row or a drag-and-drop dropzone (`dragDrop`), plus a label/hint/error
 * trio. It owns its styling through the co-located CSS Module
 * `base-file-input.module.scss` and composes the neutral {@link BaseTypography}.
 *
 * Substitutions from the original Vue SFC: the `useId` composable maps straight
 * to the framework-native `useId` hook; the drag/selection
 * state uses the neutral `useState` hook; the upload icon is the write-once
 * `@mission-platform/icons` `IconUpload` (itself compiled to React/Vue); the
 * `useI18n` labels become plain string props; and the `v-model` + `change` emit
 * become the `onUpdateModelValue`/`onChange` callback props.
 */
export function BaseFileInput(properties: Readonly<FileInputProperties>): MpElement {
  const {
    multiple = false,
    accept,
    capture,
    size = 'md',
    label,
    labelHidden = false,
    hint,
    error,
    disabled = false,
    required = false,
    dragDrop = false,
    browseLabel = 'Browse files',
    dragLabel = 'Drag & drop files here or',
    noFileLabel = 'No file chosen',
  } = properties;

  const generatedId = useId();
  const resolvedId = properties.id ?? generatedId;
  const describedBy = error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined;

  const [isDragging, setIsDragging] = useState(false);
  const [displayName, setDisplayName] = useState('');

  const handleFiles = (files: FileList | null | undefined): void => {
    if (!files || files.length === 0) {
      properties.onUpdateModelValue?.();
      properties.onChange?.();
      setDisplayName('');
      return;
    }
    const result = multiple ? [...files] : files[0];
    properties.onUpdateModelValue?.(result);
    properties.onChange?.(files);
    setDisplayName(multiple ? `${files.length} file${files.length > 1 ? 's' : ''} selected` : files[0].name);
  };

  const handleInputChange = (event: Event): void => {
    handleFiles((event.target as HTMLInputElement).files);
  };

  const handleDrop = (event: DragEvent): void => {
    event.preventDefault();
    setIsDragging(false);
    if (disabled) {
      return;
    }
    handleFiles(event.dataTransfer?.files ?? undefined);
  };

  const handleDragOver = (event: DragEvent): void => {
    event.preventDefault();
    if (!disabled) {
      setIsDragging(true);
    }
  };

  const handleDragLeave = (): void => setIsDragging(false);

  return (
    <div
      className={[
        styles['base-file-input'],
        styles[`base-file-input--${size}`],
        {
          [styles['base-file-input--error']]: !!error,
          [styles['base-file-input--disabled']]: disabled,
        },
      ]}
    >
      {label ? (
        <label
          className={[
            styles['base-file-input__label'],
            {
              [styles['base-file-input__label--hidden']]: labelHidden,
            },
          ]}
          for={resolvedId}
        >
          <BaseTypography
            as="span"
            color="primary"
            variant="label"
          >
            {label}
          </BaseTypography>
          {required ? (
            <span
              aria-hidden="true"
              className={styles['base-file-input__required']}
              title="required"
            >
              *
            </span>
          ) : undefined}
        </label>
      ) : undefined}
      {dragDrop ? (
        <div
          className={[
            styles['base-file-input__dropzone'],
            {
              [styles['base-file-input__dropzone--active']]: isDragging,
            },
          ]}
          role="presentation"
          onDragLeave={handleDragLeave}
          onDragOver={handleDragOver}
          onDrop={handleDrop}
        >
          <span
            aria-hidden="true"
            className={styles['base-file-input__icon']}
          >
            <IconUpload size="lg" />
          </span>
          <p className={styles['base-file-input__drop-text']}>
            <BaseTypography
              as="span"
              color="secondary"
              variant="body-sm"
            >
              {`${dragLabel} `}
            </BaseTypography>
            <label
              className={styles['base-file-input__browse-link']}
              for={resolvedId}
            >
              {browseLabel}
            </label>
          </p>
          {displayName ? (
            <p className={styles['base-file-input__file-name']}>
              <BaseTypography
                as="span"
                variant="body-sm"
                weight="medium"
              >
                {displayName}
              </BaseTypography>
            </p>
          ) : undefined}
        </div>
      ) : (
        <div className={styles['base-file-input__row']}>
          <label
            className={[
              styles['base-file-input__button'],
              {
                [styles['base-file-input__button--disabled']]: disabled,
              },
            ]}
            for={resolvedId}
          >
            {browseLabel}
          </label>
          <span className={styles['base-file-input__name']}>
            <BaseTypography
              as="span"
              color="secondary"
              variant="body-sm"
            >
              {displayName || noFileLabel}
            </BaseTypography>
          </span>
        </div>
      )}
      <input
        id={resolvedId}
        accept={accept}
        aria-describedby={describedBy}
        aria-invalid={error ? 'true' : undefined}
        capture={capture}
        className={styles['base-file-input__native']}
        disabled={disabled}
        multiple={multiple}
        required={required}
        type="file"
        onChange={handleInputChange}
      />
      {error ? (
        <p
          id={`${resolvedId}-error`}
          className={styles['base-file-input__error']}
          role="alert"
        >
          <BaseTypography
            as="span"
            color="inherit"
            variant="caption"
          >
            {error}
          </BaseTypography>
        </p>
      ) : hint ? (
        <p
          id={`${resolvedId}-hint`}
          className={styles['base-file-input__hint']}
        >
          <BaseTypography
            as="span"
            color="secondary"
            variant="caption"
          >
            {hint}
          </BaseTypography>
        </p>
      ) : undefined}
    </div>
  );
}
