// packages/components/src/components/base-qr-code/base-qr-code.vue
<script lang="ts" setup>
  /**
   * `BaseQrCode` — renders a scannable QR Code for the Mission Platform UI.
   *
   * The payload (`value`) is encoded entirely on the client by the bundled,
   * dependency-free {@link encodeQr} encoder (byte mode, automatic version
   * selection, lowest-penalty data mask) and drawn as a crisp, resolution-
   * independent SVG. A single `<path>` is emitted for all dark modules, so the
   * markup stays compact even for large codes.
   *
   * For reliable scanning the dark / light colours default to solid black on
   * white rather than theme tokens, but both are overridable via `color` /
   * `background`. The `margin` prop controls the mandatory quiet-zone border.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { computed } from 'vue';

  import { encodeQr, type QrErrorCorrection } from './qr-encode';

  const props = withDefaults(
    defineProps<{
      /** The data to encode (URL, text, etc.). */
      value: string;
      /** Error-correction level. Higher levels survive more damage. Defaults to `'M'`. */
      errorCorrection?: QrErrorCorrection;
      /** Rendered side length in pixels. Defaults to `160`. */
      size?: number;
      /** Quiet-zone border width, in modules. The spec recommends `4`. */
      margin?: number;
      /** Colour of the dark modules. Defaults to solid black for scannability. */
      color?: string;
      /** Colour of the background / light modules. Defaults to solid white. */
      background?: string;
      /** Accessible label describing the code's destination. */
      ariaLabel?: string;
    }>(),
    {
      errorCorrection: 'M',
      size: 160,
      margin: 4,
      color: '#000000',
      background: '#ffffff',
      ariaLabel: undefined,
    },
  );

  const emit = defineEmits<{
    /** Emitted when `value` cannot be encoded (e.g. it is too long). */
    error: [error: Error];
  }>();

  interface RenderedQr {
    /** Side length of the viewBox, including the quiet-zone margin. */
    dimension: number;
    /** SVG path data covering every dark module. */
    path: string;
  }

  const rendered = computed<RenderedQr | null>(() => {
    try {
      const matrix = encodeQr(props.value, props.errorCorrection);
      const margin = Math.max(0, Math.floor(props.margin));
      const dimension = matrix.size + margin * 2;
      const parts: string[] = [];
      for (let y = 0; y < matrix.size; y++) {
        for (let x = 0; x < matrix.size; x++) {
          if (matrix.modules[y][x]) {
            parts.push(`M${x + margin} ${y + margin}h1v1h-1z`);
          }
        }
      }
      return { dimension, path: parts.join('') };
    } catch (error) {
      emit('error', error instanceof Error ? error : new Error(String(error)));
      return null;
    }
  });
</script>

<template>
  <svg
    v-if="rendered"
    :aria-hidden="ariaLabel ? undefined : true"
    :aria-label="ariaLabel"
    :height="size"
    :role="ariaLabel ? 'img' : undefined"
    :viewBox="`0 0 ${rendered.dimension} ${rendered.dimension}`"
    :width="size"
    class="base-qr-code"
    shape-rendering="crispEdges"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      :fill="background"
      :height="rendered.dimension"
      :width="rendered.dimension"
      class="base-qr-code__background"
      x="0"
      y="0"
    />
    <path
      :d="rendered.path"
      :fill="color"
      class="base-qr-code__modules"
    />
  </svg>
</template>

<style lang="scss" scoped>
  @layer mp.components {
    .base-qr-code {
      display: block;
      max-width: 100%;
      height: auto;
    }
  }
</style>

// packages/qr-code/src/components/molecules/base-qr-code/base-qr-code.tsx
import { BaseButton, BaseTypography } from '@mission-platform/components';
import { IconCheck, IconCopy, IconDownload, IconImage } from '@mission-platform/icons';
import { h, type MpElement, type MpProperties, useEffect, useMemo, useRef, useState } from '@mission-platform/forge';
import { encodeMicroQr, encodeQr, encodeRmqr, type QrErrorCorrection } from '@mission-platform/qr-code';

import styles from './base-qr-code.module.scss';

export type { QrErrorCorrection } from '@mission-platform/qr-code';

/** Shape used to draw each module (or finder pattern) of the code. */
export type QrModuleShape = 'square' | 'rounded' | 'dot';

/**
 * Which QR symbology to encode:
 * - `'qr'` — a standard (square) QR Code, versions 1–40.
 * - `'micro'` — a Micro QR Code (ISO/IEC 18004), the compact square M1–M4.
 * - `'rmqr'` — a Rectangular Micro QR (rMQR) Code (ISO/IEC 23941), a wide,
 *   short symbol.
 */
export type QrVariant = 'qr' | 'micro' | 'rmqr';

/** A two-stop colour gradient applied to the dark modules. */
export interface QrGradient {
  /** Gradient geometry. Defaults to `'linear'`. */
  type?: 'linear' | 'radial';
  /** Colour at offset `0`. */
  from: string;
  /** Colour at offset `1`. */
  to: string;
  /** Rotation of a linear gradient, in degrees (about the centre). Defaults to `0`. */
  rotation?: number;
}

/** A centred logo overlaid on the code (use with `errorCorrection: 'H'` for reliable scanning). */
export interface QrLogo {
  /** Image source — a URL or a `data:` URI. */
  href: string;
  /** Logo edge length as a fraction (`0`–`1`) of the code. Defaults to `0.22`. */
  scale?: number;
  /** Padding around the logo, in modules. Defaults to `1`. */
  padding?: number;
  /** Fill of the plate drawn behind the logo. Defaults to the code `background`. */
  background?: string;
  /** Corner radius of the backing plate, in modules. Defaults to `1`. */
  radius?: number;
}

export interface QrCodeProperties extends MpProperties {
  /** The data to encode (URL, text, etc.). */
  value: string;
  /**
   * Which QR symbology to render. Defaults to `'qr'` (a standard square QR
   * Code). Use `'micro'` for a Micro QR Code or `'rmqr'` for a Rectangular
   * Micro QR (rMQR) Code — both far more compact for short payloads.
   */
  variant?: QrVariant;
  /**
   * Error-correction level. Higher levels survive more damage. Defaults to
   * `'M'`. Note the compact variants restrict the available levels: Micro QR
   * supports `L`/`M`/`Q` (not `H`), and rMQR supports only `M` and `H`.
   */
  errorCorrection?: QrErrorCorrection;
  /** Rendered side length in pixels. Defaults to `160`. */
  size?: number;
  /** Quiet-zone border width, in modules. The spec recommends `4`. */
  margin?: number;
  /** Colour of the dark modules. Defaults to solid black for scannability. */
  color?: string;
  /** Colour of the background / light modules. Defaults to solid white. */
  background?: string;
  /** Shape of the data modules. Defaults to `'square'` for maximum scannability. */
  moduleShape?: QrModuleShape;
  /** Shape of the three finder (eye) patterns. Defaults to {@link moduleShape}. */
  finderShape?: QrModuleShape;
  /**
   * A colour gradient for the dark modules. When set it overrides `color`.
   * High-contrast stops keep the code scannable.
   */
  gradient?: QrGradient;
  /** A logo overlaid at the centre of the code. Pair with `errorCorrection: 'H'`. */
  logo?: QrLogo;
  /** Accessible label describing the code's destination. */
  ariaLabel?: string;
  /**
   * Show the whole action toolbar (save as image, copy image, copy value). Acts
   * as the default for the individual `show*Button` props below. Defaults to
   * `false`.
   */
  showActions?: boolean;
  /** Show the "save as image" (PNG download) button. Defaults to {@link showActions}. */
  showDownloadButton?: boolean;
  /** Show the "copy image to clipboard" button. Defaults to {@link showActions}. */
  showCopyImageButton?: boolean;
  /** Show the "copy value to clipboard" button. Defaults to {@link showActions}. */
  showCopyValueButton?: boolean;
  /** File name used when saving the QR code as an image. Defaults to `'qr-code.png'`. */
  downloadFileName?: string;
  /** Fired when `value` cannot be encoded, or an action (save/copy) fails. */
  onError?: (error: Error) => void;
}

/** The result of encoding the payload into an SVG path. */
interface RenderedQr {
  /** Width of the viewBox, in modules, including the quiet-zone margin. */
  viewWidth: number;
  /** Height of the viewBox, in modules, including the quiet-zone margin. */
  viewHeight: number;
  /** SVG path data covering every dark module. */
  path: string;
  /** Width of the matrix itself, in modules (excludes the quiet zone). */
  matrixWidth: number;
  /** Height of the matrix itself, in modules (excludes the quiet zone). */
  matrixHeight: number;
  /** Quiet-zone border width, in modules, added on every side. */
  quietZone: number;
}

/** A rectangular module grid, the shared shape of every encoded variant. */
interface EncodedMatrix {
  width: number;
  height: number;
  modules: boolean[][];
}

/**
 * Encode `value` with the encoder matching `variant`, normalising the square
 * full-QR result into the same rectangular `{ width, height, modules }` shape
 * the compact encoders already return.
 */
function encodeVariant(variant: QrVariant, value: string, errorCorrection: QrErrorCorrection): EncodedMatrix {
  if (variant === 'micro') {
    return encodeMicroQr(value, errorCorrection);
  }
  if (variant === 'rmqr') {
    return encodeRmqr(value, errorCorrection);
  }
  const matrix = encodeQr(value, errorCorrection);
  return { width: matrix.size, height: matrix.size, modules: matrix.modules };
}

/** Which action last completed, so its button can flash a confirmation tick. */
type CompletedAction = '' | 'download' | 'image' | 'value';

/**
 * SVG path data for a single dark module of the given `shape`, positioned with
 * its top-left corner at `(x, y)` in module units (each module is `1×1`).
 */
function modulePath(shape: QrModuleShape, x: number, y: number): string {
  if (shape === 'dot') {
    // A full-cell circle, drawn as two half-arcs from the left-most point.
    return `M${x} ${y + 0.5}a0.5 0.5 0 1 0 1 0a0.5 0.5 0 1 0 -1 0z`;
  }
  if (shape === 'rounded') {
    // A squircle with a 0.25-module corner radius (straight runs are 0.5).
    return (
      `M${x + 0.25} ${y}h0.5a0.25 0.25 0 0 1 0.25 0.25v0.5` +
      `a0.25 0.25 0 0 1 -0.25 0.25h-0.5a0.25 0.25 0 0 1 -0.25 -0.25v-0.5` +
      `a0.25 0.25 0 0 1 0.25 -0.25z`
    );
  }
  return `M${x} ${y}h1v1h-1z`;
}

/**
 * Whether module `(x, y)` lies inside a finder (eye) pattern, so it can be drawn
 * with the dedicated `finderShape`. The finder layout depends on the symbology:
 * a full QR Code has three 7×7 finders (top-left, top-right, bottom-left); a
 * Micro QR Code has a single 7×7 finder in the top-left; and an rMQR Code has a
 * 7×7 finder in the top-left and a 5×5 finder sub-pattern in the bottom-right.
 */
function isFinderModule(x: number, y: number, width: number, height: number, variant: QrVariant): boolean {
  const inTop = y < 7;
  const inLeft = x < 7;
  const topLeft = inTop && inLeft;
  if (variant === 'micro') {
    return topLeft;
  }
  if (variant === 'rmqr') {
    const bottomRight = x >= width - 5 && y >= height - 5;
    return topLeft || bottomRight;
  }
  const inTopRight = inTop && x >= width - 7;
  const inBottomLeft = y >= height - 7 && inLeft;
  return topLeft || inTopRight || inBottomLeft;
}

/**
 * A short, deterministic id derived from `seed`, so a gradient definition gets a
 * stable `id` that differs between distinct gradients but is reproducible for
 * SSR (identical markup on the server and client).
 */
function stableId(prefix: string, seed: string): string {
  let hash = 2166136261;
  for (let index = 0; index < seed.length; index++) {
    hash ^= seed.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return `${prefix}-${(hash >>> 0).toString(36)}`;
}

/**
 * `BaseQrCode` — renders a scannable QR Code, authored once in the neutral JSX
 * dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-forge`.
 *
 * The payload (`value`) is encoded entirely on the client by the
 * `@mission-platform/qr-code` encoders — dependency-free encoders written in
 * Rust and compiled to WebAssembly (automatic version selection, lowest-penalty
 * data mask) — and drawn as a crisp, resolution-independent SVG. The `variant`
 * prop chooses the symbology: a standard square QR Code ({@link encodeQr},
 * `'qr'`, the default), a compact square Micro QR Code
 * ({@link encodeMicroQr}, `'micro'`), or a wide Rectangular Micro QR / rMQR Code
 * ({@link encodeRmqr}, `'rmqr'`). A single `<path>` is emitted for all dark
 * modules, so the markup stays compact even for large codes. For reliable
 * scanning the dark / light colours default to solid black on white rather than
 * theme tokens, but both are overridable via `color` / `background`.
 *
 * Modules and finder (eye) patterns can be drawn as squares, rounded squares,
 * or dots (`moduleShape` / `finderShape`); the dark fill accepts a two-stop
 * linear or radial `gradient`; and an optional centre `logo` is overlaid on a
 * backing plate (pair it with `errorCorrection: 'H'` so the code still scans).
 *
 * An optional action toolbar (enabled via `showActions` or the individual
 * `show*Button` props) lets users **save the code as a PNG image**, **copy the
 * image to the clipboard**, and **copy the encoded value to the clipboard**. The
 * PNG is rasterised on the client by drawing the rendered SVG onto a canvas.
 *
 * Substitutions from the original Vue SFC: the `computed` render becomes the
 * neutral {@link useMemo}; the `error` emit becomes the `onError` callback prop
 * (invoked when encoding fails, mirroring the original's emit from inside the
 * computed). It owns its styling through the co-located CSS Module
 * `base-qr-code.module.scss`.
 */
export function BaseQrCode(properties: Readonly<QrCodeProperties>): MpElement {
  const {
    value,
    variant = 'qr',
    errorCorrection = 'M',
    size = 160,
    margin = 4,
    color = '#000000',
    background = '#ffffff',
    moduleShape = 'square',
    finderShape,
    gradient,
    logo,
    ariaLabel,
    showActions = false,
    showDownloadButton,
    showCopyImageButton,
    showCopyValueButton,
    downloadFileName = 'qr-code.png',
  } = properties;

  // Each individual button falls back to `showActions` when not set explicitly.
  // The fallback is resolved in the body (rather than as a destructuring default)
  // so the Vue codegen doesn't emit a `withDefaults` entry referencing a sibling
  // prop, which isn't in scope in the generated single-file component.
  const showDownload = showDownloadButton ?? showActions;
  const showCopyImage = showCopyImageButton ?? showActions;
  const showCopyValue = showCopyValueButton ?? showActions;

  // Finder patterns fall back to the module shape when not set explicitly.
  const resolvedFinderShape = finderShape ?? moduleShape;

  const svgReference = useRef<SVGSVGElement | null>(null);
  const [completed, setCompleted] = useState<CompletedAction>('');
  const resetTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  // Clear any pending confirmation-tick timer when the component unmounts.
  useEffect(() => {
    return () => {
      if (resetTimer.current !== undefined) {
        clearTimeout(resetTimer.current);
      }
    };
  }, []);

  const result = useMemo<{ rendered: RenderedQr | undefined; error: Error | undefined }>(() => {
    try {
      const matrix = encodeVariant(variant, value, errorCorrection);
      const quietZone = Math.max(0, Math.floor(margin));
      const viewWidth = matrix.width + quietZone * 2;
      const viewHeight = matrix.height + quietZone * 2;
      const parts: string[] = [];
      for (let y = 0; y < matrix.height; y++) {
        for (let x = 0; x < matrix.width; x++) {
          if (matrix.modules[y][x]) {
            const shape = isFinderModule(x, y, matrix.width, matrix.height, variant)
              ? resolvedFinderShape
              : moduleShape;
            parts.push(modulePath(shape, x + quietZone, y + quietZone));
          }
        }
      }
      return {
        rendered: {
          viewWidth,
          viewHeight,
          path: parts.join(''),
          matrixWidth: matrix.width,
          matrixHeight: matrix.height,
          quietZone,
        },
        error: undefined,
      };
    } catch (error) {
      return { rendered: undefined, error: error instanceof Error ? error : new Error(String(error)) };
    }
  }, [variant, value, errorCorrection, margin, moduleShape, resolvedFinderShape]);

  if (result.error) {
    properties.onError?.(result.error);
  }

  if (!result.rendered) {
    return (
      <svg
        aria-hidden="true"
        className={styles['base-qr-code']}
        height="0"
        width="0"
        xmlns="http://www.w3.org/2000/svg"
      />
    );
  }

  const { viewWidth, viewHeight, path, matrixWidth, matrixHeight } = result.rendered;

  // `size` sets the rendered pixel width; the height follows the symbol's aspect
  // ratio so rectangular rMQR codes are not distorted (square codes stay square).
  const pixelWidth = size;
  const pixelHeight = Math.round((size * viewHeight) / viewWidth);

  // Non-square shapes need antialiasing; keep pixel-crisp edges for plain squares.
  const shapeRendering =
    moduleShape === 'square' && resolvedFinderShape === 'square' ? 'crispEdges' : 'geometricPrecision';

  // A gradient (when set) overrides the flat `color`; it needs a `<defs>` entry
  // referenced by a stable id, plus the module fill pointing at it.
  const gradientType = gradient?.type ?? 'linear';
  const gradientId = gradient
    ? stableId('mp-qr-gradient', `${gradientType}:${gradient.from}:${gradient.to}:${gradient.rotation ?? 0}`)
    : '';
  const moduleFill = gradient ? `url(#${gradientId})` : color;

  // Centre-logo geometry, in module units (matching the viewBox coordinate space).
  // The logo is sized off the shorter matrix edge so it never overflows a
  // rectangular (rMQR) symbol, and centred in the full viewBox.
  const logoLayout = logo
    ? (() => {
        const logoSize = Math.min(matrixWidth, matrixHeight) * (logo.scale ?? 0.22);
        const plate = logoSize + (logo.padding ?? 1) * 2;
        return { logoSize, plate, centreX: viewWidth / 2, centreY: viewHeight / 2, radius: logo.radius ?? 1 };
      })()
    : undefined;

  const reportError = (error: unknown): void => {
    properties.onError?.(error instanceof Error ? error : new Error(String(error)));
  };

  const flashCompleted = (action: CompletedAction): void => {
    setCompleted(action);
    if (resetTimer.current !== undefined) {
      clearTimeout(resetTimer.current);
    }
    resetTimer.current = setTimeout(() => setCompleted(''), 2000);
  };

  /** Rasterise the rendered SVG onto a canvas and resolve a PNG blob. */
  const toPngBlob = async (): Promise<Blob> => {
    const svgElement = svgReference.current;
    if (!svgElement) {
      throw new Error('The QR code has not been rendered yet.');
    }
    const serialized = new XMLSerializer().serializeToString(svgElement);
    const image = new Image();
    image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(serialized)}`;
    await image.decode();

    // Rasterise at a whole-module multiple so exported pixels stay crisp,
    // preserving the symbol's aspect ratio for rectangular codes.
    const exportWidth = Math.max(pixelWidth, viewWidth * 4);
    const exportHeight = Math.round((exportWidth * viewHeight) / viewWidth);
    const canvas = document.createElement('canvas');
    canvas.width = exportWidth;
    canvas.height = exportHeight;
    const context = canvas.getContext('2d');
    if (!context) {
      throw new Error('A 2D canvas context is unavailable in this environment.');
    }
    context.drawImage(image, 0, 0, exportWidth, exportHeight);

    return await new Promise<Blob>((resolve, reject) => {
      canvas.toBlob(
        (blob) => (blob ? resolve(blob) : reject(new Error('Could not rasterise the QR code to an image.'))),
        'image/png',
      );
    });
  };

  const saveImage = (): void => {
    void (async () => {
      try {
        const blob = await toPngBlob();
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.download = downloadFileName;
        anchor.rel = 'noopener';
        document.body.append(anchor);
        anchor.click();
        anchor.remove();
        URL.revokeObjectURL(url);
        flashCompleted('download');
      } catch (error) {
        reportError(error);
      }
    })();
  };

  const copyImage = (): void => {
    void (async () => {
      try {
        const blob = await toPngBlob();
        await navigator.clipboard.write([new ClipboardItem({ [blob.type]: blob })]);
        flashCompleted('image');
      } catch (error) {
        reportError(error);
      }
    })();
  };

  const copyValue = (): void => {
    void (async () => {
      try {
        await navigator.clipboard.writeText(value);
        flashCompleted('value');
      } catch (error) {
        reportError(error);
      }
    })();
  };

  const qrSvg = (
    <svg
      ref={svgReference}
      aria-hidden={ariaLabel ? undefined : 'true'}
      aria-label={ariaLabel}
      className={styles['base-qr-code']}
      height={pixelHeight}
      role={ariaLabel ? 'img' : undefined}
      shape-rendering={shapeRendering}
      viewBox={`0 0 ${viewWidth} ${viewHeight}`}
      width={pixelWidth}
      xmlns="http://www.w3.org/2000/svg"
    >
      {gradient ? (
        <defs>
          {gradientType === 'radial' ? (
            <radialGradient id={gradientId}>
              <stop
                offset="0"
                stop-color={gradient.from}
              />
              <stop
                offset="1"
                stop-color={gradient.to}
              />
            </radialGradient>
          ) : (
            <linearGradient
              gradientTransform={`rotate(${gradient.rotation ?? 0} 0.5 0.5)`}
              id={gradientId}
              x1="0"
              x2="1"
              y1="0"
              y2="0"
            >
              <stop
                offset="0"
                stop-color={gradient.from}
              />
              <stop
                offset="1"
                stop-color={gradient.to}
              />
            </linearGradient>
          )}
        </defs>
      ) : null}
      <rect
        className={styles['base-qr-code__background']}
        fill={background}
        height={viewHeight}
        width={viewWidth}
        x="0"
        y="0"
      />
      <path
        className={styles['base-qr-code__modules']}
        d={path}
        fill={moduleFill}
      />
      {logo && logoLayout ? (
        <rect
          className={styles['base-qr-code__logo-plate']}
          fill={logo.background ?? background}
          height={logoLayout.plate}
          rx={logoLayout.radius}
          ry={logoLayout.radius}
          width={logoLayout.plate}
          x={logoLayout.centreX - logoLayout.plate / 2}
          y={logoLayout.centreY - logoLayout.plate / 2}
        />
      ) : null}
      {logo && logoLayout ? (
        <image
          className={styles['base-qr-code__logo']}
          height={logoLayout.logoSize}
          href={logo.href}
          preserveAspectRatio="xMidYMid meet"
          width={logoLayout.logoSize}
          x={logoLayout.centreX - logoLayout.logoSize / 2}
          y={logoLayout.centreY - logoLayout.logoSize / 2}
        />
      ) : null}
    </svg>
  );

  const actions: {
    key: CompletedAction;
    label: string;
    doneLabel: string;
    icon: MpElement;
    onClick: () => void;
    visible: boolean;
  }[] = [
    {
      key: 'download',
      label: 'Save image',
      doneLabel: 'Saved',
      icon: <IconDownload size="xs" />,
      onClick: saveImage,
      visible: showDownload,
    },
    {
      key: 'image',
      label: 'Copy image',
      doneLabel: 'Copied',
      icon: <IconImage size="xs" />,
      onClick: copyImage,
      visible: showCopyImage,
    },
    {
      key: 'value',
      label: 'Copy value',
      doneLabel: 'Copied',
      icon: <IconCopy size="xs" />,
      onClick: copyValue,
      visible: showCopyValue,
    },
  ];

  const visibleActions = actions.filter((action) => action.visible);
  if (visibleActions.length === 0) {
    return qrSvg;
  }

  return (
    <div className={styles['base-qr-code-figure']}>
      {qrSvg}
      <div className={styles['base-qr-code__actions']}>
        {visibleActions.map((action) => {
          const isDone = completed === action.key;
          return (
            <BaseButton
              key={action.key}
              size="sm"
              type="button"
              variant="secondary"
              onClick={action.onClick}
            >
              {isDone ? <IconCheck size="xs" /> : action.icon}
              <BaseTypography
                as="span"
                color="inherit"
                variant="caption"
              >
                {isDone ? action.doneLabel : action.label}
              </BaseTypography>
            </BaseButton>
          );
        })}
      </div>
    </div>
  );
}
