// packages/components/src/components/base-carousel/base-carousel.tsx
import {
  h,
  Slot,
  useEffect,
  useRef,
  useState,
  type MpChild,
  type MpElement,
  type MpProperties,
  type MpRenderProperty,
} from '@mission-platform/jsx';

import sizeStyles from '../size.module.scss';

import styles from './base-carousel.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type CarouselSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** Colour tone of the carousel — the canonical colour set (`neutral` is the plain treatment). */
export type CarouselVariant =
  | 'neutral'
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'success'
  | 'warning'
  | 'info'
  | 'error'
  | 'critical';

/** A single slide descriptor. */
export interface CarouselSlide {
  /** Stable unique identifier (used as the list key). */
  id: string;
  /** Image URL rendered as the default slide content. */
  image?: string;
  /** Alt text for the image. */
  alt?: string;
  /** Text content rendered when no `image` is given. */
  content?: string;
}

/** The scope passed to the scoped `slide` slot. */
export interface CarouselSlideScope {
  /** The slide being rendered. */
  slide: CarouselSlide;
  /** The slide's index. */
  index: number;
}

export interface CarouselProperties extends MpProperties {
  /** Size token controlling the carousel's scale. Defaults to `'md'`. */
  size?: CarouselSize;
  /** Ordered list of slides. */
  slides: CarouselSlide[];
  /** Index of the initially visible slide. */
  modelValue?: number;
  /** Show previous/next navigation controls. Defaults to `true`. */
  controls?: boolean;
  /** Show indicator dots below the carousel. Defaults to `true`. */
  indicators?: boolean;
  /** Colour tone of the controls/indicators. Defaults to `'neutral'`. */
  variant?: CarouselVariant;
  /** Allow the index to wrap past the first/last slide. Defaults to `true`. */
  loop?: boolean;
  /** Accessible label for the carousel region. */
  ariaLabel?: string;
  /** Automatically advance slides at a regular interval. */
  autoplay?: boolean;
  /** Autoplay interval in milliseconds. Defaults to `5000`. */
  interval?: number;
  /** Pause autoplay while the pointer hovers the carousel. Defaults to `true`. */
  pauseOnHover?: boolean;
  /** Minimum horizontal pointer movement (px) to register a swipe. Defaults to `40`. */
  swipeThreshold?: number;
  /** Renders a slide; receives `{ slide, index }`. Falls back to the slide's image/content. */
  slide?: MpRenderProperty<CarouselSlideScope>;
  /** Fired with the new index (the controlled `v-model` update). */
  onUpdateModelValue?: (index: number) => void;
  /** Fired with the new index whenever the active slide changes. */
  onChange?: (index: number) => void;
}

/**
 * `BaseCarousel` — a horizontally-scrollable slide deck authored once in the
 * neutral JSX dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * It shows one slide at a time with optional previous/next controls, indicator
 * dots, keyboard (Arrow/Home/End) navigation, pointer-swipe, and optional
 * autoplay with a WCAG 2.2.2 pause/play control. It owns its styling through the
 * co-located CSS Module `base-carousel.module.scss`.
 *
 * Substitutions from the original Vue SFC: the slides came from the default slot
 * and the count was derived by introspecting slot VNodes — which the neutral
 * dialect cannot do — so the slides are driven by a `slides` array (with a
 * scoped `slide` slot for custom content), the same flattening the migrated
 * {@link BaseTabs} used. The Composition-API `ref`/`watch`/`onBeforeUnmount`
 * autoplay plumbing becomes `useState` + a `useEffect` interval (keyed on the
 * active index so it advances without a stale closure); the `useReducedMotion`
 * composable becomes an inline `matchMedia` check inside the effect; the pointer
 * start coordinates become a `useRef`; `defineExpose` is dropped; and the
 * `v-model` + emits become callback props.
 */
export function BaseCarousel(properties: CarouselProperties): MpElement {
  const {
    slides,
    modelValue = 0,
    controls = true,
    indicators = true,
    loop = true,
    ariaLabel = 'Carousel',
    autoplay = false,
    interval = 5000,
    pauseOnHover = true,
    swipeThreshold = 40,
    variant = 'neutral',
    size = 'md',
  } = properties;

  const slideCount = slides.length;

  const [currentIndex, setCurrentIndex] = useState<number>(modelValue);
  const [isPaused, setIsPaused] = useState<boolean>(false);
  const [userPaused, setUserPaused] = useState<boolean>(false);
  const pointerStart = useRef<{ x: number; y: number } | undefined>(undefined);

  const commit = (index: number): void => {
    setCurrentIndex(index);
    properties.onUpdateModelValue?.(index);
    properties.onChange?.(index);
  };

  const goTo = (index: number): void => {
    if (slideCount === 0) {
      return;
    }
    const next = loop ? ((index % slideCount) + slideCount) % slideCount : Math.max(0, Math.min(slideCount - 1, index));
    commit(next);
  };

  const previous = (): void => goTo(currentIndex - 1);
  const next = (): void => goTo(currentIndex + 1);

  useEffect(() => {
    if (!autoplay || isPaused || userPaused || slideCount <= 1) {
      return;
    }
    if (
      globalThis.window !== undefined &&
      typeof globalThis.matchMedia === 'function' &&
      globalThis.matchMedia('(prefers-reduced-motion: reduce)').matches
    ) {
      return;
    }
    const timer = setInterval(
      () => {
        const upcoming = loop ? (currentIndex + 1) % slideCount : Math.min(slideCount - 1, currentIndex + 1);
        commit(upcoming);
      },
      Math.max(1000, interval),
    );
    return () => clearInterval(timer);
  }, [autoplay, interval, isPaused, userPaused, slideCount, currentIndex, loop]);

  const handleKeydown = (event: KeyboardEvent): void => {
    switch (event.key) {
      case 'ArrowLeft': {
        event.preventDefault();
        previous();
        break;
      }
      case 'ArrowRight': {
        event.preventDefault();
        next();
        break;
      }
      case 'Home': {
        event.preventDefault();
        goTo(0);
        break;
      }
      case 'End': {
        event.preventDefault();
        goTo(slideCount - 1);
        break;
      }
      default: {
        break;
      }
    }
  };

  const handlePointerDown = (event: PointerEvent): void => {
    if (event.pointerType === 'mouse' && event.button !== 0) {
      return;
    }
    pointerStart.current = { x: event.clientX, y: event.clientY };
    if (pauseOnHover) {
      setIsPaused(true);
    }
  };

  const handlePointerUp = (event: PointerEvent): void => {
    const start = pointerStart.current;
    pointerStart.current = undefined;
    if (event.pointerType !== 'mouse' && pauseOnHover) {
      setIsPaused(false);
    }
    if (!start) {
      return;
    }
    const deltaX = event.clientX - start.x;
    const deltaY = event.clientY - start.y;
    if (Math.abs(deltaX) < swipeThreshold || Math.abs(deltaX) < Math.abs(deltaY)) {
      return;
    }
    if (deltaX < 0) {
      next();
    } else {
      previous();
    }
  };

  const handlePointerCancel = (): void => {
    pointerStart.current = undefined;
    if (pauseOnHover) {
      setIsPaused(false);
    }
  };

  const showAutoplayToggle = autoplay && slideCount > 1;

  const indicatorButtons: MpChild[] = slides.map((slideItem, index) => (
    <button
      key={slideItem.id}
      aria-label={`Go to slide ${index + 1}`}
      aria-selected={currentIndex === index}
      classNames={[styles['base-carousel__indicator'], {
        [styles['base-carousel__indicator--active']]: currentIndex === index,
      }]}
      role="tab"
      type="button"
      onClick={() => goTo(index)}
    />
  ));

  const slideNodes: MpChild[] = slides.map((slideItem, index) => (
    <div
      key={slideItem.id}
      aria-hidden={currentIndex === index ? undefined : 'true'}
      aria-label={`${index + 1} of ${slideCount}`}
      aria-roledescription="slide"
      classNames={styles['base-carousel__slide']}
      role="group"
    >
      <Slot
        name="slide"
        index={index}
        slide={slideItem}
      >
        {slideItem.image ? (
          <img
            alt={slideItem.alt ?? ''}
            classNames={styles['base-carousel__image']}
            src={slideItem.image}
          />
        ) : (
          slideItem.content
        )}
      </Slot>
    </div>
  ));

  return (
    <section
      aria-label={ariaLabel}
      aria-roledescription="carousel"
      classNames={[styles['base-carousel'], styles[`base-carousel--${variant}`], sizeStyles[`base-size--${size}`]]}
      tabindex={0}
      onKeydown={handleKeydown}
      onMouseenter={() => {
        if (pauseOnHover) {
          setIsPaused(true);
        }
      }}
      onMouseleave={() => {
        if (pauseOnHover) {
          setIsPaused(false);
        }
      }}
    >
      <div
        classNames={styles['base-carousel__viewport']}
        onPointercancel={handlePointerCancel}
        onPointerdown={handlePointerDown}
        onPointerleave={handlePointerCancel}
        onPointerup={handlePointerUp}
      >
        <div
          classNames={styles['base-carousel__track']}
          style={{ transform: `translateX(-${currentIndex * 100}%)` }}
        >
          {slideNodes}
        </div>
      </div>

      {controls && slideCount > 1 ? (
        <button
          aria-label="Previous slide"
          classNames={[styles['base-carousel__control'], styles['base-carousel__control--prev']]}
          disabled={!loop && currentIndex === 0}
          type="button"
          onClick={previous}
        >
          <span aria-hidden="true">‹</span>
        </button>
      ) : undefined}
      {controls && slideCount > 1 ? (
        <button
          aria-label="Next slide"
          classNames={[styles['base-carousel__control'], styles['base-carousel__control--next']]}
          disabled={!loop && currentIndex === slideCount - 1}
          type="button"
          onClick={next}
        >
          <span aria-hidden="true">›</span>
        </button>
      ) : undefined}

      {indicators && slideCount > 1 ? (
        <div
          classNames={styles['base-carousel__indicators']}
          role="tablist"
        >
          {indicatorButtons}
        </div>
      ) : undefined}

      {showAutoplayToggle ? (
        <button
          aria-label={userPaused ? 'Start automatic slide rotation' : 'Pause automatic slide rotation'}
          aria-pressed={userPaused}
          classNames={styles['base-carousel__autoplay']}
          type="button"
          onClick={() => setUserPaused(!userPaused)}
        >
          <span aria-hidden="true">{userPaused ? '▶' : '❙❙'}</span>
        </button>
      ) : undefined}
    </section>
  );
}

// packages/components/src/components/base-carousel/base-carousel.vue
<script lang="ts" setup>
  /* eslint-disable vuejs-accessibility/no-static-element-interactions */
  /**
   * `BaseCarousel` — Carousel component for the Mission Platform UI.
   *
   * Displays a horizontally-scrollable list of slides one (or more) at a
   * time, with optional previous/next controls and indicator dots. Each
   * slide is provided via the default slot, typically using the
   * `<BaseCarouselSlide>` helper, but any child element works.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { computed, onBeforeUnmount, ref, useSlots, watch } from 'vue';

  import { useReducedMotion } from '../../composables/use-reduced-motion';

  const properties = withDefaults(
    defineProps<{
      /** Index of the initially visible slide. */
      modelValue?: number;
      /** Show previous/next navigation controls. */
      controls?: boolean;
      /** Show indicator dots below the carousel. */
      indicators?: boolean;
      /** Allow the index to wrap when navigating past the first/last slide. */
      loop?: boolean;
      /** Accessible label for the carousel region. */
      ariaLabel?: string;
      /** Automatically advance slides at a regular interval. */
      autoplay?: boolean;
      /** Autoplay interval in milliseconds. */
      interval?: number;
      /** Pause autoplay when the pointer hovers or the carousel has keyboard focus. */
      pauseOnHover?: boolean;
      /** Minimum horizontal pointer movement (in px) required to register a swipe. */
      swipeThreshold?: number;
    }>(),
    {
      modelValue: 0,
      controls: true,
      indicators: true,
      loop: true,
      ariaLabel: 'Carousel',
      autoplay: false,
      interval: 5000,
      pauseOnHover: true,
      swipeThreshold: 40,
    },
  );

  const emit = defineEmits<{
    (event: 'update:modelValue', index: number): void;
    (event: 'change', index: number): void;
  }>();

  const internalIndex = ref(properties.modelValue);
  // Sync internal index whenever the parent updates the controlled `modelValue`.
  watch(
    () => properties.modelValue,
    (value) => {
      if (typeof value === 'number') internalIndex.value = value;
    },
  );
  const currentIndex = computed({
    get: () => internalIndex.value,
    set: (value: number) => {
      internalIndex.value = value;
      emit('update:modelValue', value);
      emit('change', value);
    },
  });

  const slots = useSlots();
  const slideCount = computed(() => {
    const defaultSlot = slots.default?.();
    if (!defaultSlot) return 0;
    // Flatten fragments (e.g. v-for emits a single VNode containing children).
    let count = 0;
    for (const node of defaultSlot) {
      if (Array.isArray(node.children)) {
        count += node.children.length;
      } else {
        count += 1;
      }
    }
    return count;
  });

  function goTo(index: number): void {
    if (slideCount.value === 0) return;
    currentIndex.value = properties.loop
      ? ((index % slideCount.value) + slideCount.value) % slideCount.value
      : Math.max(0, Math.min(slideCount.value - 1, index));
  }

  function previous(): void {
    goTo(currentIndex.value - 1);
  }

  function next(): void {
    goTo(currentIndex.value + 1);
  }

  const trackStyle = computed(() => ({
    transform: `translateX(-${currentIndex.value * 100}%)`,
  }));

  // ── Autoplay ────────────────────────────────────────────────────────────────
  let autoplayTimer: ReturnType<typeof setInterval> | null = null;
  // Transient pause from hover / focus.
  const isPaused = ref(false);
  // Explicit pause requested by the user via the pause/play control (WCAG 2.2.2).
  const userPaused = ref(false);
  // Respect the user's reduced-motion preference: never auto-rotate when set.
  const reducedMotion = useReducedMotion();

  function stopAutoplay(): void {
    if (autoplayTimer !== null) {
      clearInterval(autoplayTimer);
      autoplayTimer = null;
    }
  }

  function startAutoplay(): void {
    stopAutoplay();
    if (
      !properties.autoplay ||
      isPaused.value ||
      userPaused.value ||
      reducedMotion.value ||
      slideCount.value <= 1
    ) {
      return;
    }
    autoplayTimer = setInterval(
      () => {
        next();
      },
      Math.max(1000, properties.interval),
    );
  }

  /** Whether the user-facing pause/play control should be shown. */
  const showAutoplayToggle = computed(
    () => properties.autoplay && slideCount.value > 1 && !reducedMotion.value,
  );

  /** Toggles the explicit, user-controlled autoplay pause (WCAG 2.2.2). */
  function toggleAutoplayPaused(): void {
    userPaused.value = !userPaused.value;
  }

  watch(
    () => [
      properties.autoplay,
      properties.interval,
      isPaused.value,
      userPaused.value,
      reducedMotion.value,
      slideCount.value,
    ],
    () => startAutoplay(),
    { immediate: true },
  );

  onBeforeUnmount(() => {
    stopAutoplay();
  });

  function handleMouseEnter(): void {
    if (properties.pauseOnHover) isPaused.value = true;
  }
  function handleMouseLeave(): void {
    if (properties.pauseOnHover) isPaused.value = false;
  }
  function handleFocusIn(): void {
    if (properties.pauseOnHover) isPaused.value = true;
  }
  function handleFocusOut(event: FocusEvent): void {
    if (!properties.pauseOnHover) return;
    const root = event.currentTarget as HTMLElement | null;
    const nextTarget = event.relatedTarget as Node | null;
    if (!root || !nextTarget || !root.contains(nextTarget)) {
      isPaused.value = false;
    }
  }

  // ── Keyboard ────────────────────────────────────────────────────────────────
  function handleKeydown(event: KeyboardEvent): void {
    switch (event.key) {
      case 'ArrowLeft': {
        event.preventDefault();
        previous();
        break;
      }
      case 'ArrowRight': {
        event.preventDefault();
        next();
        break;
      }
      case 'Home': {
        event.preventDefault();
        goTo(0);
        break;
      }
      case 'End': {
        event.preventDefault();
        goTo(slideCount.value - 1);
        break;
      }
      default: {
        break;
      }
    }
  }

  // ── Touch / pointer swipe ───────────────────────────────────────────────────
  const pointerStartX = ref<number | null>(null);
  const pointerStartY = ref<number | null>(null);
  const pointerId = ref<number | null>(null);

  function handlePointerDown(event: PointerEvent): void {
    if (event.pointerType === 'mouse' && event.button !== 0) return;
    pointerStartX.value = event.clientX;
    pointerStartY.value = event.clientY;
    pointerId.value = event.pointerId;
    if (properties.pauseOnHover) isPaused.value = true;
  }

  function handlePointerUp(event: PointerEvent): void {
    if (pointerStartX.value === null || pointerStartY.value === null) return;
    const deltaX = event.clientX - pointerStartX.value;
    const deltaY = event.clientY - pointerStartY.value;
    pointerStartX.value = null;
    pointerStartY.value = null;
    pointerId.value = null;
    if (event.pointerType !== 'mouse' && properties.pauseOnHover) {
      isPaused.value = false;
    }
    // Only treat as a swipe if horizontal movement dominates and exceeds the threshold.
    if (Math.abs(deltaX) < properties.swipeThreshold) return;
    if (Math.abs(deltaX) < Math.abs(deltaY)) return;
    if (deltaX < 0) {
      next();
    } else {
      previous();
    }
  }

  function handlePointerCancel(): void {
    pointerStartX.value = null;
    pointerStartY.value = null;
    pointerId.value = null;
    if (properties.pauseOnHover) isPaused.value = false;
  }

  defineExpose({ previous, next, goTo });
</script>

<template>
  <section
    class="base-carousel"
    :aria-label="ariaLabel"
    aria-roledescription="carousel"
    tabindex="0"
    @keydown="handleKeydown"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
    @focusin="handleFocusIn"
    @focusout="handleFocusOut"
  >
    <div
      class="base-carousel__viewport"
      @pointerdown="handlePointerDown"
      @pointerup="handlePointerUp"
      @pointercancel="handlePointerCancel"
      @pointerleave="handlePointerCancel"
    >
      <div
        class="base-carousel__track"
        :style="trackStyle"
      >
        <slot />
      </div>
    </div>

    <button
      v-if="controls && slideCount > 1"
      type="button"
      class="base-carousel__control base-carousel__control--prev"
      aria-label="Previous slide"
      :disabled="!loop && currentIndex === 0"
      @click="previous"
    >
      <span aria-hidden="true">‹</span>
    </button>
    <button
      v-if="controls && slideCount > 1"
      type="button"
      class="base-carousel__control base-carousel__control--next"
      aria-label="Next slide"
      :disabled="!loop && currentIndex === slideCount - 1"
      @click="next"
    >
      <span aria-hidden="true">›</span>
    </button>

    <div
      v-if="indicators && slideCount > 1"
      class="base-carousel__indicators"
      role="tablist"
    >
      <button
        v-for="index in slideCount"
        :key="index - 1"
        type="button"
        role="tab"
        :aria-label="`Go to slide ${index}`"
        :aria-selected="currentIndex === index - 1"
        :class="['base-carousel__indicator', { 'base-carousel__indicator--active': currentIndex === index - 1 }]"
        @click="goTo(index - 1)"
      />
    </div>

    <button
      v-if="showAutoplayToggle"
      type="button"
      class="base-carousel__autoplay"
      :aria-label="userPaused ? 'Start automatic slide rotation' : 'Pause automatic slide rotation'"
      :aria-pressed="userPaused"
      @click="toggleAutoplayPaused"
    >
      <span aria-hidden="true">{{ userPaused ? '▶' : '❙❙' }}</span>
    </button>
  </section>
</template>

<style lang="scss" scoped>
  .base-carousel {
    position: relative;
    width: 100%;

    &:focus {
      outline: none;
    }

    &:focus-visible {
      outline: 2px solid var(--mp-color-primary-default);
      outline-offset: 2px;
      border-radius: var(--mp-radius-lg);
    }

    &__viewport {
      overflow: hidden;
      border-radius: var(--mp-radius-lg);
      touch-action: pan-y;
      user-select: none;
    }

    &__track {
      display: flex;
      width: 100%;
      transition: transform 400ms ease;

      > :deep(*) {
        flex: 0 0 100%;
        min-width: 0;
        box-sizing: border-box;
      }
    }

    &__control {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      width: 40px;
      height: 40px;
      border-radius: 50%;
      border: 1px solid var(--mp-color-border-default);
      background: var(--mp-color-bg-surface);
      color: var(--mp-color-text-default);
      font-size: 24px;
      line-height: 1;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      box-shadow: var(--mp-shadow-sm);

      &--prev {
        left: var(--mp-spacing-2);
      }

      &--next {
        right: var(--mp-spacing-2);
      }

      &:disabled {
        opacity: 0.4;
        cursor: not-allowed;
      }

      &:hover:not(:disabled) {
        background: var(--mp-color-bg-base-alt);
      }
    }

    &__indicators {
      display: flex;
      justify-content: center;
      gap: var(--mp-spacing-2);
      margin-top: var(--mp-spacing-3);
    }

    &__indicator {
      /* Keep the visible dot small while guaranteeing a >=24x24px hit area
         so the control satisfies WCAG 2.2 SC 2.5.8 (Target Size, Minimum). */
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 24px;
      height: 24px;
      padding: 0;
      border: none;
      border-radius: 50%;
      background: transparent;
      cursor: pointer;

      &::before {
        content: '';
        width: 10px;
        height: 10px;
        border-radius: 50%;
        background: var(--mp-color-border-default);
        transition: background 200ms ease;
      }

      &--active::before {
        background: var(--mp-color-primary-default);
      }

      &:focus-visible {
        outline: 2px solid var(--mp-color-primary-default);
        outline-offset: 2px;
      }
    }

    &__autoplay {
      /* Always-available pause/play control for autoplaying carousels
         (WCAG 2.2.2 Pause, Stop, Hide). Sized to meet the 24px target min. */
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 28px;
      height: 28px;
      margin: var(--mp-spacing-2) auto 0;
      padding: 0;
      border: 1px solid var(--mp-color-border-default);
      border-radius: 50%;
      background: var(--mp-color-bg-surface);
      color: var(--mp-color-text-default);
      font-size: 12px;
      line-height: 1;
      cursor: pointer;
      box-shadow: var(--mp-shadow-sm);

      &:hover {
        background: var(--mp-color-bg-base-alt);
      }

      &:focus-visible {
        outline: 2px solid var(--mp-color-primary-default);
        outline-offset: 2px;
      }
    }
  }
</style>
