// packages/components/src/components/base-toast/base-toast-container.vue
<script lang="ts" setup>
  /**
   * `BaseToastContainer` — Renders the toasts held in the `useToast` store.
   *
   * Mount a single instance near the root of your application. It teleports a
   * fixed-position stack to `<body>`, anchors it to one of six screen
   * positions, animates entry/exit, and dismisses toasts on user request.
   *
   * Accessibility:
   * - The stack is a `role="region"` with a configurable `aria-label`; each
   *   `BaseToast` carries its own `role="status"` / `role="alert"`.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { computed } from 'vue';

  import { useToast } from '../../composables/use-toast';
  import { useZIndex } from '../../composables/use-z-index';

  import BaseToast from './base-toast.vue';

  import type { ToastPosition } from '../../composables/use-toast';

  const props = withDefaults(
    defineProps<{
      /** Anchor position of the stack. Defaults to `'top-right'`. */
      position?: ToastPosition;
      /** Accessible label for the region. Defaults to `'Notifications'`. */
      ariaLabel?: string;
      /** Render into `<body>` via Teleport. Disable for tests. Defaults to `true`. */
      teleport?: boolean;
    }>(),
    {
      position: 'top-right',
      ariaLabel: 'Notifications',
      teleport: true,
    },
  );

  const { toasts, dismiss } = useToast();
  const { zIndex } = useZIndex('notification');

  // Bottom-anchored stacks render newest-first (closest to the edge).
  const orderedToasts = computed(() => (props.position.startsWith('bottom') ? [...toasts].reverse() : toasts));
</script>

<template>
  <Teleport
    :disabled="!teleport"
    to="body"
  >
    <div
      :aria-label="ariaLabel"
      :class="['base-toast-container', `base-toast-container--${position}`]"
      :style="{ zIndex }"
      role="region"
    >
      <TransitionGroup name="base-toast">
        <BaseToast
          v-for="toast in orderedToasts"
          :key="toast.id"
          :dismissible="toast.dismissible"
          :message="toast.message"
          :title="toast.title"
          :variant="toast.variant"
          @dismiss="dismiss(toast.id)"
        />
      </TransitionGroup>
    </div>
  </Teleport>
</template>

<style lang="scss" scoped>
  @layer mp.components {
    .base-toast-container {
      position: fixed;
      display: flex;
      flex-direction: column;
      gap: var(--mp-spacing-3);
      width: min(24rem, calc(100vw - 2 * var(--mp-spacing-4)));
      padding: 0;
      margin: 0;
      pointer-events: none;

      &--top-left {
        top: var(--mp-spacing-4);
        left: var(--mp-spacing-4);
      }

      &--top-center {
        top: var(--mp-spacing-4);
        left: 50%;
        transform: translateX(-50%);
        align-items: center;
      }

      &--top-right {
        top: var(--mp-spacing-4);
        right: var(--mp-spacing-4);
      }

      &--bottom-left {
        bottom: var(--mp-spacing-4);
        left: var(--mp-spacing-4);
      }

      &--bottom-center {
        bottom: var(--mp-spacing-4);
        left: 50%;
        transform: translateX(-50%);
        align-items: center;
      }

      &--bottom-right {
        bottom: var(--mp-spacing-4);
        right: var(--mp-spacing-4);
      }
    }

    /* Enter / leave transitions */
    .base-toast-enter-active,
    .base-toast-leave-active {
      transition:
        opacity 200ms ease,
        transform 200ms ease;
    }

    .base-toast-enter-from,
    .base-toast-leave-to {
      opacity: 0;
      transform: translateY(-0.5rem);
    }

    .base-toast-leave-active {
      position: absolute;
      width: 100%;
    }

    @media (prefers-reduced-motion: reduce) {
      .base-toast-enter-active,
      .base-toast-leave-active {
        transition: none;
      }
    }
  }
</style>

// packages/components/src/components/base-toast-container/base-toast-container.tsx
import {
  h,
  Teleport,
  TransitionGroup,
  useEffect,
  useState,
  type MpElement,
  type MpProperties,
} from '@mission-platform/jsx';

import { BaseToast } from '../base-toast';
import sizeStyles from '../size.module.scss';
import { dismissToast, getToastsSnapshot, subscribeToasts, type ToastPosition } from '../toast-store';


import styles from './base-toast-container.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type ToastContainerSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface ToastContainerProperties extends MpProperties {
  /** Size token controlling the stack's font scale. Defaults to `'md'`. */
  size?: ToastContainerSize;
  /** Anchor position of the stack. Defaults to `'top-right'`. */
  position?: ToastPosition;
  /** Accessible label for the region. Defaults to `'Notifications'`. */
  ariaLabel?: string;
  /** Render into `<body>` via the neutral `<Teleport>`. Disable for tests. Defaults to `true`. */
  teleport?: boolean;
}

/**
 * `BaseToastContainer` — renders the toasts held in the shared `toast-store`,
 * authored once in the neutral JSX dialect and compiled straight to React or Vue
 * by `@mission-platform/vite-plugin-jsx`.
 *
 * Mount a single instance near the root of your application. It teleports a
 * fixed-position stack to `<body>` (through the framework-neutral
 * **`<Teleport>`** portal), anchors it to one of six screen positions, and
 * dismisses toasts on user request. The component subscribes to the shared
 * observable store with the neutral {@link useState}/{@link useEffect} hooks
 * (the substitute for the Vue `useToast` reactive store), so a single authored
 * source stays reactive on both frameworks.
 *
 * Accessibility:
 * - The stack is a `role="region"` with a configurable `aria-label`; each
 *   `BaseToast` carries its own `role="status"` / `role="alert"`.
 *
 * Enter/leave animation matches the Vue SFC via the neutral
 * **`<TransitionGroup>`** primitive, which compiles to Vue's built-in
 * `<TransitionGroup>` and the `@mission-platform/jsx/react` CSS-class group
 * driver. The four styled enter/leave phase classes are passed as **hashed
 * CSS-Module classes** (via the `<TransitionGroup>` class props), so the
 * animation styling stays component-scoped instead of relying on global
 * `:global(.base-toast-*)` rules — matching the `scoped` `<style>` of the
 * original Vue SFC. On Vue the toast root receives those classes natively; on
 * React the driver orchestrates mount/unmount through the leave phase (the
 * classes are applied to DOM-element children — `BaseToast` being a component,
 * the React build degrades to the SSR-in-place baseline for the class toggling,
 * like the single `<Transition>`).
 *
 * Substitutions from the original Vue SFC: the reactive `useToast` store →
 * the shared observable `toast-store` singleton; `<Teleport to="body">` → the
 * neutral `<Teleport>` portal primitive; the `useZIndex('notification')`
 * composable → the static `notification` z-index layer applied in CSS.
 */
export function BaseToastContainer(properties: ToastContainerProperties): MpElement {
  const { position = 'top-right', ariaLabel = 'Notifications', teleport = true, size = 'md' } = properties;

  const [toasts, setToasts] = useState(getToastsSnapshot());
  useEffect(() => {
    const update = (): void => setToasts(getToastsSnapshot());
    return subscribeToasts(update);
  }, []);

  // Bottom-anchored stacks render newest-first (closest to the edge).
  const ordered = position.startsWith('bottom') ? toasts.toReversed() : [...toasts];

  return (
    <Teleport
      disabled={!teleport}
      to="body"
    >
      <div
        aria-label={ariaLabel}
        classNames={[styles['base-toast-container'], styles[`base-toast-container--${position}`], sizeStyles[`base-size--${size}`]]}
        role="region"
      >
        <TransitionGroup
          name="base-toast"
          enterFromClass={styles['base-toast-enter-from']}
          enterActiveClass={styles['base-toast-enter-active']}
          leaveActiveClass={styles['base-toast-leave-active']}
          leaveToClass={styles['base-toast-leave-to']}
        >
          {ordered.map((toast) => (
            <BaseToast
              key={toast.id}
              dismissible={toast.dismissible}
              message={toast.message}
              title={toast.title}
              variant={toast.variant}
              onDismiss={() => dismissToast(toast.id)}
            />
          ))}
        </TransitionGroup>
      </div>
    </Teleport>
  );
}
