// packages/components/src/components/BaseInView/BaseInView.vue
<script setup lang="ts">
  /**
   * InView — wraps content and uses IntersectionObserver to detect when it
   * enters the viewport. Once visible, content is revealed with a configurable
   * animation. Useful for lazy-loading sections, fade-in cards, etc.
   *
   * Props
   *   threshold    — 0–1 intersection ratio required to trigger (default 0.15)
   *   rootMargin   — IntersectionObserver rootMargin (default '0px')
   *   animation    — reveal animation: 'fade' | 'slide-up' | 'slide-left' | 'slide-right' | 'scale' | 'none'
   *   duration     — CSS transition duration in ms (default 500)
   *   delay        — CSS transition delay in ms (default 0)
   *   once         — if true (default) only triggers once and disconnects the observer
   *   tag          — HTML element to render as the wrapper (default 'div')
   *
   * Slots
   *   default({ inView, hasBeenInView }) — slotted content receives reactive state
   *
   * Events
   *   enter — emitted when the element enters the viewport
   *   leave — emitted when the element leaves the viewport (only when once=false)
   */
  import { computed, onMounted, onUnmounted, ref } from 'vue'

  export type InViewAnimation =
    | 'fade'
    | 'slide-up'
    | 'slide-left'
    | 'slide-right'
    | 'scale'
    | 'none'

  const props = withDefaults(
    defineProps<{
      threshold?: number
      rootMargin?: string
      animation?: InViewAnimation
      duration?: number
      delay?: number
      once?: boolean
      tag?: string
    }>(),
    {
      threshold: 0.15,
      rootMargin: '0px',
      animation: 'fade',
      duration: 500,
      delay: 0,
      once: true,
      tag: 'div',
    },
  )

  const emit = defineEmits<{
    enter: []
    leave: []
  }>()

  const wrapperRef = ref<HTMLElement | null>(null)
  const inView = ref(false)
  const hasBeenInView = ref(false)

  // ── Hidden (before reveal) styles per animation ────────────────────────────
  const hiddenStyle = computed<Record<string, string | undefined>>(() => {
    switch (props.animation) {
      case 'fade':
        return { opacity: '0' }
      case 'slide-up':
        return { opacity: '0', transform: 'translateY(24px)' }
      case 'slide-left':
        return { opacity: '0', transform: 'translateX(24px)' }
      case 'slide-right':
        return { opacity: '0', transform: 'translateX(-24px)' }
      case 'scale':
        return { opacity: '0', transform: 'scale(0.92)' }
      default:
        return {}
    }
  })

  // ── Visible (after reveal) styles ─────────────────────────────────────────
  const visibleStyle = computed<Record<string, string | undefined>>(() => {
    if (props.animation === 'none') return {}
    return { opacity: '1', transform: 'none' }
  })

  // ── Combined style applied to the wrapper element ─────────────────────────
  const wrapperStyle = computed<Record<string, string | undefined>>(() => {
    const transition =
      props.animation === 'none'
        ? {}
        : {
            transition: `opacity ${props.duration}ms ease ${props.delay}ms, transform ${props.duration}ms ease ${props.delay}ms`,
          }

    const state = inView.value ? visibleStyle.value : hiddenStyle.value

    return { ...state, ...transition }
  })

  // ── IntersectionObserver ───────────────────────────────────────────────────
  let observer: IntersectionObserver | null = null

  function connect() {
    if (!wrapperRef.value) return
    observer = new IntersectionObserver(
      (entries) => {
        const entry = entries[0]
        if (entry.isIntersecting) {
          inView.value = true
          hasBeenInView.value = true
          emit('enter')
          if (props.once) {
            observer?.disconnect()
            observer = null
          }
        } else {
          if (!props.once) {
            inView.value = false
            emit('leave')
          }
        }
      },
      { threshold: props.threshold, rootMargin: props.rootMargin },
    )
    observer.observe(wrapperRef.value)
  }

  onMounted(connect)
  onUnmounted(() => observer?.disconnect())

  defineExpose({ inView, hasBeenInView })
</script>

<template>
  <component :is="tag" ref="wrapperRef" class="in-view" :style="wrapperStyle">
    <slot :in-view="inView" :has-been-in-view="hasBeenInView" />
  </component>
</template>

// packages/components/src/components/base-in-view/base-in-view.tsx
import {
  classNames,
  Dynamic,
  h,
  useEffect,
  useRef,
  useState,
  type MpElement,
  type MpProperties,
} from '@mission-platform/jsx';

import sizeStyles from '../size.module.scss';

export type InViewAnimation = 'fade' | 'slide-up' | 'slide-left' | 'slide-right' | 'scale' | 'none';
/** Size token — canonical 2xs → 2xl scale. */
export type InViewSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface InViewProperties extends MpProperties {
  /** 0–1 intersection ratio required to trigger. */
  threshold?: number;
  /** `IntersectionObserver` `rootMargin`. */
  rootMargin?: string;
  /** Reveal animation applied once the element enters the viewport. */
  animation?: InViewAnimation;
  /** CSS transition duration in ms. */
  duration?: number;
  /** CSS transition delay in ms. */
  delay?: number;
  /** Trigger only once and disconnect the observer (default `true`). */
  once?: boolean;
  /** Host element tag to render as the wrapper. */
  tag?: string;
  /** Size token controlling the wrapper's font scale. Defaults to `'md'`. */
  size?: InViewSize;
  /** Called when the element enters the viewport. */
  onEnter?: () => void;
  /** Called when the element leaves the viewport (only when `once` is false). */
  onLeave?: () => void;
}

/** Hidden (pre-reveal) style per animation. */
function hiddenStyle(animation: InViewAnimation): Record<string, string> {
  switch (animation) {
    case 'fade': {
      return { opacity: '0' };
    }
    case 'slide-up': {
      return { opacity: '0', transform: 'translateY(24px)' };
    }
    case 'slide-left': {
      return { opacity: '0', transform: 'translateX(24px)' };
    }
    case 'slide-right': {
      return { opacity: '0', transform: 'translateX(-24px)' };
    }
    case 'scale': {
      return { opacity: '0', transform: 'scale(0.92)' };
    }
    default: {
      return {};
    }
  }
}

/** Combined inline style applied to the wrapper for the current state. */
function wrapperStyle(
  animation: InViewAnimation,
  duration: number,
  delay: number,
  inView: boolean,
): Record<string, string> {
  if (animation === 'none') {
    return {};
  }
  const transition = {
    transition: `opacity ${duration}ms ease ${delay}ms, transform ${duration}ms ease ${delay}ms`,
  };
  const state = inView ? { opacity: '1', transform: 'none' } : hiddenStyle(animation);
  return { ...state, ...transition };
}

/**
 * `BaseInView` — wraps content and uses `IntersectionObserver` to reveal it with
 * a configurable animation once it scrolls into view. Authored once in the
 * neutral JSX dialect; the cross-framework state/lifecycle is provided by the
 * neutral hooks (`useState`/`useRef`/`useEffect`), which compile to React hooks
 * or the Vue hook shim via `@mission-platform/vite-plugin-jsx`.
 *
 * Note: unlike the Vue original it does not expose a scoped slot — reveal state
 * is conveyed purely through the wrapper's animated style and the
 * `onEnter`/`onLeave` callbacks, which map cleanly onto both frameworks.
 */
export function BaseInView(properties: Readonly<InViewProperties>): MpElement {
  const {
    threshold = 0.15,
    rootMargin = '0px',
    animation = 'fade',
    duration = 500,
    delay = 0,
    once = true,
    tag = 'div',
    size = 'md',
    onEnter,
    onLeave,
  } = properties;

  const wrapperReference = useRef<HTMLElement | null>(null);
  const [inView, setInView] = useState(false);

  useEffect(() => {
    const element = wrapperReference.current;
    if (element === null || typeof IntersectionObserver === 'undefined') {
      return;
    }
    const observer = new IntersectionObserver(
      (entries) => {
        const entry = entries[0];
        if (entry.isIntersecting) {
          setInView(true);
          onEnter?.();
          if (once) {
            observer.disconnect();
          }
        } else if (!once) {
          setInView(false);
          onLeave?.();
        }
      },
      { threshold, rootMargin },
    );
    observer.observe(element);
    return () => observer.disconnect();
  }, [threshold, rootMargin, once]);

  return (
    <Dynamic
      is={tag}
      ref={wrapperReference}
      className={classNames('in-view', sizeStyles[`base-size--${size}`])}
      style={wrapperStyle(animation, duration, delay, inView)}
    >
      {properties.children}
    </Dynamic>
  );
}
