// packages/components/src/components/base-theme-composer/base-theme-composer.tsx
import { h, Slot, useEffect, useState, type MpElement, type MpProperties } from '@mission-platform/jsx';

import sizeStyles from '../size.module.scss';
import {
  configToCssVariables,
  configToStyleString,
  mergeConfig,
  removeConfigToken,
  setConfigAttribute,
  setConfigToken,
  type ThemeComposerAttribute,
  type ThemeComposerConfig,
} from '../theme-composer-store';


import styles from './base-theme-composer.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type ThemeComposerSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface ThemeComposerProperties extends MpProperties {
  /** Size token controlling the composer's scale. Defaults to `'md'`. */
  size?: ThemeComposerSize;
  /** The composed theme configuration (the controlled value). */
  modelValue?: ThemeComposerConfig;
  /** Apply the composed variables to `document.documentElement` instead of the wrapper. Defaults to `false`. */
  global?: boolean;
  /** Persist the configuration to `localStorage`. Retained for API parity; not applied by the controlled neutral version. Defaults to `false`. */
  persist?: boolean;
  /** `localStorage` key. Retained for API parity; not applied by the controlled neutral version. */
  storageKey?: string;
  /** Fired with the next configuration whenever it changes (the controlled-value callback). */
  onUpdateModelValue?: (config: ThemeComposerConfig) => void;
}

/**
 * `BaseThemeComposer` — composes runtime `--mp-*` design-token overrides (brand
 * colours, text/surface/border colours, fonts, base size/radius, plus a raw
 * token escape hatch) and applies them to its scope. Authored once in the
 * neutral JSX dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * The original Vue SFC shared a reactive store via `provide`/`inject` and `v-model`.
 * The neutral dialect has neither, so this version is a **controlled** component:
 * it holds the configuration in a neutral {@link useState} hook (seeded from
 * `modelValue`), resolves it to CSS custom properties with the pure helpers in
 * `../theme-composer-store`, applies them to its `display: contents` wrapper
 * (`<div>`) — or to `document.documentElement` when `global` — and emits every
 * change through the `onUpdateModelValue` callback prop (the substitute for
 * `v-model`). Its default scoped slot receives `{ config, cssVariables,
 * styleString, setConfig, setAttribute, setToken, removeToken, reset }`.
 *
 * The shared (`provide`/`inject`) store, `localStorage` persistence, and the
 * configurable wrapper tag (`as`) are intentionally reduced: the
 * `modelValue`/`onUpdateModelValue` pair is the single source of truth and the
 * wrapper is a fixed `<div>`.
 */
export function BaseThemeComposer(properties: ThemeComposerProperties): MpElement {
  const { modelValue, global = false, onUpdateModelValue, size = 'md' } = properties;

  const [config, setConfigState] = useState<ThemeComposerConfig>(modelValue ?? {});

  useEffect(() => {
    if (!global || typeof document === 'undefined') {
      return;
    }
    const root = document.documentElement;
    const variables = configToCssVariables(config);
    for (const [name, value] of Object.entries(variables)) {
      root.style.setProperty(name, value);
    }
    if (config.colorScheme) {
      root.style.colorScheme = config.colorScheme;
    }
    return () => {
      for (const name of Object.keys(variables)) {
        root.style.removeProperty(name);
      }
      if (config.colorScheme) {
        root.style.removeProperty('color-scheme');
      }
    };
  }, [config, global]);

  const cssVariables = configToCssVariables(config);
  const styleString = configToStyleString(config);
  const styleObject = {
    ...cssVariables,
    ...(config.colorScheme ? { colorScheme: config.colorScheme } : {}),
  };
  const wrapperStyle = global ? undefined : styleObject;

  const apply = (next: ThemeComposerConfig): void => {
    setConfigState(next);
    onUpdateModelValue?.(next);
  };
  const setConfig = (partial: ThemeComposerConfig): void => apply(mergeConfig(config, partial));
  const setAttribute = <K extends ThemeComposerAttribute>(attribute: K, value: ThemeComposerConfig[K]): void =>
    apply(setConfigAttribute(config, attribute, value));
  const setToken = (key: string, value: string): void => apply(setConfigToken(config, key, value));
  const removeToken = (key: string): void => apply(removeConfigToken(config, key));
  const reset = (): void => apply(modelValue ?? {});

  return (
    <div
      classNames={[styles['base-theme-composer'], sizeStyles[`base-size--${size}`]]}
      style={wrapperStyle}
    >
      <Slot
        config={config}
        cssVariables={cssVariables}
        styleString={styleString}
        setConfig={setConfig}
        setAttribute={setAttribute}
        setToken={setToken}
        removeToken={removeToken}
        reset={reset}
      />
    </div>
  );
}

// packages/components/src/components/base-theme-composer/base-theme-composer.vue
<script lang="ts" setup>
  /**
   * `BaseThemeComposer` — Runtime theme-attribute composer for the Mission
   * Platform UI.
   *
   * Lets consumers configure attributes of the theme (brand/accent colours,
   * text/surface/border/focus colours, font families, base font size, and base
   * corner radius) plus arbitrary raw `--mp-*` token overrides via an escape
   * hatch. It resolves the configuration (see `useThemeComposer`) into `--mp-*`
   * CSS custom properties and either scopes them to its own wrapper element
   * (default) or applies them globally to `document.documentElement` when
   * `global` is set.
   *
   * The composed configuration is exposed through `v-model` and shared with all
   * descendants via `provide`/`inject`, so nested `useThemeComposer` calls read
   * and mutate the same store. The default slot receives the current state and
   * mutators as slot props.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { onScopeDispose, provide, watch } from 'vue';

  import { createThemeComposer, ThemeComposerKey } from '../../composables/use-theme-composer';

  import type { ThemeComposerAttribute, ThemeComposerConfig } from '../../composables/use-theme-composer';

  const props = withDefaults(
    defineProps<{
      /** The composed theme configuration (`v-model`). */
      modelValue?: ThemeComposerConfig;
      /**
       * Apply the composed variables to `document.documentElement` instead of
       * the local wrapper element. Defaults to `false`.
       */
      global?: boolean;
      /** Persist the configuration to `localStorage`. Defaults to `false`. */
      persist?: boolean;
      /** `localStorage` key used to persist the configuration. Defaults to `'mp-theme-composer'`. */
      storageKey?: string;
      /** Tag used for the scoping wrapper element when `global` is `false`. Defaults to `'div'`. */
      as?: string;
    }>(),
    {
      modelValue: undefined,
      global: false,
      persist: false,
      storageKey: 'mp-theme-composer',
      as: 'div',
    },
  );

  const emit = defineEmits<{
    'update:modelValue': [config: ThemeComposerConfig];
  }>();

  /**
   * Default slot — receives the current theme-composer state and mutators.
   * @slot default
   */
  defineSlots<{
    default?: (props: {
      config: ThemeComposerConfig;
      cssVariables: Record<string, string>;
      styleString: string;
      setConfig: (partial: ThemeComposerConfig) => void;
      setAttribute: <K extends ThemeComposerAttribute>(attribute: K, value: ThemeComposerConfig[K]) => void;
      setToken: (key: string, value: string) => void;
      removeToken: (key: string) => void;
      reset: () => void;
    }) => unknown;
  }>();

  const store = createThemeComposer({
    initialConfig: props.modelValue ?? {},
    global: props.global,
    persist: props.persist,
    storageKey: props.storageKey,
  });

  provide(ThemeComposerKey, store);

  // Keep `v-model` in sync with the store, guarding against feedback loops.
  let syncingFromProp = false;

  watch(
    store.config,
    (value) => {
      if (syncingFromProp) return;
      emit('update:modelValue', value);
    },
    { deep: true },
  );

  watch(
    () => props.modelValue,
    (value) => {
      if (!value || value === store.config.value) return;
      syncingFromProp = true;
      store.replaceConfig(value);
      syncingFromProp = false;
    },
    { deep: true },
  );

  onScopeDispose(() => store.dispose());
</script>

<template>
  <component
    :is="as"
    v-if="!global"
    :style="store.styleString.value"
    class="base-theme-composer"
  >
    <slot
      :config="store.config.value"
      :css-variables="store.cssVariables.value"
      :remove-token="store.removeToken"
      :reset="store.reset"
      :set-attribute="store.setAttribute"
      :set-config="store.setConfig"
      :set-token="store.setToken"
      :style-string="store.styleString.value"
    />
  </component>
  <slot
    v-else
    :config="store.config.value"
    :css-variables="store.cssVariables.value"
    :remove-token="store.removeToken"
    :reset="store.reset"
    :set-attribute="store.setAttribute"
    :set-config="store.setConfig"
    :set-token="store.setToken"
    :style-string="store.styleString.value"
  />
</template>

<style lang="scss" scoped>
  .base-theme-composer {
    display: contents;
  }
</style>
