// packages/components/src/components/base-virtual-log-viewer/base-virtual-log-viewer.tsx
import {
  classNames,
  h,
  useEffect,
  useMemo,
  useRef,
  useState,
  type MpElement,
  type MpProperties,
} from '@mission-platform/jsx';

import { BaseTypography } from '../base-typography';
import sizeStyles from '../size.module.scss';

import styles from './base-virtual-log-viewer.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type VirtualLogViewerSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** Severity of a {@link LogEntry}. */
export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'fatal';

/** A single log line rendered by {@link BaseVirtualLogViewer}. */
export interface LogEntry {
  /** Stable identity for the row. */
  id: string | number;
  /** Severity level. */
  level: LogLevel;
  /** The log message. */
  message: string;
  /** Optional ISO/clock timestamp. */
  timestamp?: string;
}

export interface VirtualLogViewerProperties extends MpProperties {
  /** The full list of log entries. Only the visible window is rendered. */
  entries: LogEntry[];
  /** Size token controlling the viewer's font scale. Defaults to `'md'`. */
  size?: VirtualLogViewerSize;
  /** Fixed row height (px). Defaults to `24`. */
  itemHeight?: number;
  /** Extra rows rendered above/below the viewport. Defaults to `5`. */
  overscan?: number;
  /** Viewport height (px). Defaults to `400`. */
  height?: number;
  /** Show the level column. Defaults to `true`. */
  showLevel?: boolean;
  /** Show the timestamp column. Defaults to `true`. */
  showTimestamp?: boolean;
  /** Auto-scroll to the bottom when new entries arrive. Defaults to `true`. */
  followTail?: boolean;
  /** Case-insensitive substring filter applied to each message. */
  filter?: string;
  /** Fired when a log row is clicked; receives the entry. */
  onSelect?: (entry: LogEntry) => void;
}

/** Level → text colour token. */
const LEVEL_COLORS: Record<LogLevel, string> = {
  debug: 'var(--mp-color-text-secondary)',
  info: 'var(--mp-color-info-default)',
  warn: 'var(--mp-color-warning-default)',
  error: 'var(--mp-color-danger-default)',
  fatal: 'var(--mp-color-danger-emphasis)',
};

/**
 * `BaseVirtualLogViewer` — a high-performance virtual-scrolling log viewer.
 * Authored once in the neutral JSX dialect and compiled straight to React or
 * Vue by `@mission-platform/vite-plugin-jsx`; it renders only the rows within
 * the viewport while a full-height spacer represents the entire (optionally
 * filtered) log. Scroll position uses the neutral hooks, follow-tail is driven
 * by a {@link useEffect} keyed on the entry count, and each row's click fires
 * the `onSelect` callback. Owns its styling through `base-virtual-log-viewer.module.scss`.
 *
 * The original Vue SFC composed `BaseLogViewerRow`/`BaseLogViewerToolbar`
 * sub-components, used the icons package for the per-level glyph, and a `select`
 * emit. The neutral version inlines the row + toolbar, substitutes a colour-coded
 * `●` glyph for the icons (consistent with the other migrated components), and
 * uses the `onSelect` callback prop; the original's manual-scroll follow-tail
 * suppression is dropped.
 */
export function BaseVirtualLogViewer(properties: VirtualLogViewerProperties): MpElement {
  const {
    entries,
    itemHeight = 24,
    overscan = 5,
    height = 400,
    showLevel = true,
    showTimestamp = true,
    followTail = true,
    filter = '',
    size = 'md',
  } = properties;

  const [scrollTop, setScrollTop] = useState(0);
  const containerReference = useRef<HTMLElement | null>(null);

  const filteredEntries = useMemo(() => {
    const query = filter.trim().toLowerCase();
    if (query === '') {
      return entries;
    }
    return entries.filter((entry) => entry.message.toLowerCase().includes(query));
  }, [entries, filter]);

  const totalHeight = useMemo(() => filteredEntries.length * itemHeight, [filteredEntries, itemHeight]);

  const startIndex = useMemo(
    () => Math.max(0, Math.floor(scrollTop / itemHeight) - overscan),
    [scrollTop, itemHeight, overscan],
  );

  const endIndex = useMemo(() => {
    const visibleCount = Math.ceil(height / itemHeight);
    return Math.min(filteredEntries.length - 1, Math.floor(scrollTop / itemHeight) + visibleCount + overscan);
  }, [scrollTop, itemHeight, height, overscan, filteredEntries]);

  const offsetY = useMemo(() => startIndex * itemHeight, [startIndex, itemHeight]);

  const visibleRows = useMemo(
    () =>
      filteredEntries.slice(startIndex, endIndex + 1).map((entry, offset) => ({ entry, index: startIndex + offset })),
    [filteredEntries, startIndex, endIndex],
  );

  useEffect(() => {
    const element = containerReference.current;
    if (element === null) {
      return;
    }
    const handleScroll = (event: Event): void => {
      setScrollTop((event.target as HTMLElement).scrollTop);
    };
    element.addEventListener('scroll', handleScroll, { passive: true });
    return () => element.removeEventListener('scroll', handleScroll);
  }, []);

  // Follow-tail: scroll to the bottom when the entry count changes.
  useEffect(() => {
    if (!followTail) {
      return;
    }
    const element = containerReference.current;
    if (element === null || typeof requestAnimationFrame === 'undefined') {
      return;
    }
    const frame = requestAnimationFrame(() => {
      element.scrollTop = element.scrollHeight;
    });
    return () => cancelAnimationFrame(frame);
  }, [entries.length, followTail]);

  const toolbar = filter
    ? h(
        'div',
        { class: classNames(styles['log-viewer__toolbar']) },
        h(
          'span',
          { class: classNames(styles['log-viewer__filter-badge']) },
          `${filteredEntries.length} / ${entries.length} matching "${filter}"`,
        ),
      )
    : undefined;

  return (
    <div
      classNames={[styles['log-viewer'], sizeStyles[`base-size--${size}`]]}
      style={{ height: `${height}px` }}
    >
      {toolbar}
      <div
        ref={containerReference}
        classNames={[styles['log-viewer__scroll']]}
        style={{ height: filter ? `calc(${height}px - 32px)` : `${height}px`, overflowY: 'auto', position: 'relative' }}
      >
        <div
          aria-hidden="true"
          style={{ height: `${totalHeight}px`, position: 'relative', pointerEvents: 'none' }}
        />
        <div
          role="log"
          aria-live="polite"
          aria-atomic="false"
          style={{ position: 'absolute', top: `${offsetY}px`, left: '0', right: '0' }}
        >
          {visibleRows.map(({ entry, index }) => (
            <button
              key={entry.id}
              type="button"
              classNames={[styles['log-viewer__row'], styles[`log-viewer__row--${entry.level}`]]}
              style={{ height: `${itemHeight}px`, boxSizing: 'border-box' }}
              aria-label={`Log entry ${index + 1}: ${entry.level} — ${entry.message}`}
              onClick={() => properties.onSelect?.(entry)}
            >
              <BaseTypography
                as="span"
                variant="code"
                color="tertiary"
                classNames={[styles['log-viewer__line-no']]}
              >
                {index + 1}
              </BaseTypography>
              {showTimestamp && entry.timestamp ? (
                <BaseTypography
                  as="span"
                  variant="code"
                  color="tertiary"
                  classNames={[styles['log-viewer__timestamp']]}
                >
                  {entry.timestamp}
                </BaseTypography>
              ) : undefined}
              {showLevel ? (
                <span
                  classNames={[styles['log-viewer__level']]}
                  style={{ color: LEVEL_COLORS[entry.level] }}
                >
                  <span aria-hidden="true">●</span>
                  <BaseTypography
                    as="span"
                    variant="code"
                    color="inherit"
                    classNames={[styles['log-viewer__level-label']]}
                  >
                    {entry.level.toUpperCase()}
                  </BaseTypography>
                </span>
              ) : undefined}
              <BaseTypography
                as="span"
                variant="code"
                color="inherit"
                classNames={[styles['log-viewer__message']]}
              >
                {entry.message}
              </BaseTypography>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// packages/components/src/components/base-virtual-log-viewer/base-virtual-log-viewer.vue
<script lang="ts" setup>
  /**
   * VirtualLogViewer — a high-performance virtual-scrolling log viewer.
   *
   * Renders only the visible log rows while maintaining a full-height scrollbar
   * that represents the entire log. Supports log levels, timestamps, filtering,
   * and auto-scroll-to-bottom on new entries.
   *
   * Props
   *   entries      — array of LogEntry items
   *   itemHeight   — fixed row height in pixels (default 24)
   *   overscan     — extra rows above/below viewport (default 5)
   *   height       — viewport height in pixels (default 400)
   *   showLevel    — show the level badge column (default true)
   *   showTimestamp — show the timestamp column (default true)
   *   followTail   — auto-scroll to bottom when new entries arrive (default true)
   *   filter       — case-insensitive substring filter applied to message
   *
   * Events
   *   select(entry) — emitted when a log row is clicked
   */
  import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue';

  import BaseLogViewerRow from './base-log-viewer-row.vue';
  import BaseLogViewerToolbar from './base-log-viewer-toolbar.vue';

  export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'fatal';

  export interface LogEntry {
    id: string | number;
    level: LogLevel;
    message: string;
    timestamp?: string;
    [key: string]: unknown;
  }

  const props = withDefaults(
    defineProps<{
      entries: LogEntry[];
      itemHeight?: number;
      overscan?: number;
      height?: number;
      showLevel?: boolean;
      showTimestamp?: boolean;
      followTail?: boolean;
      filter?: string;
    }>(),
    {
      itemHeight: 24,
      overscan: 5,
      height: 400,
      showLevel: true,
      showTimestamp: true,
      followTail: true,
      filter: '',
    },
  );

  const emit = defineEmits<{
    select: [entry: LogEntry];
  }>();

  // ─── Filtering ────────────────────────────────────────────────────────────────

  const filteredEntries = computed(() => {
    const q = props.filter.trim().toLowerCase();
    if (!q) return props.entries;
    return props.entries.filter((e) => e.message.toLowerCase().includes(q));
  });

  // ─── Virtual scroll ───────────────────────────────────────────────────────────

  const scrollTop = ref(0);
  const containerRef = ref<HTMLElement | null>(null);
  let userScrolled = false;

  const totalHeight = computed(() => filteredEntries.value.length * props.itemHeight);

  const startIndex = computed(() => {
    const raw = Math.floor(scrollTop.value / props.itemHeight) - props.overscan;
    return Math.max(0, raw);
  });

  const endIndex = computed(() => {
    const visibleCount = Math.ceil(props.height / props.itemHeight);
    const raw = Math.floor(scrollTop.value / props.itemHeight) + visibleCount + props.overscan;
    return Math.min(filteredEntries.value.length - 1, raw);
  });

  const visibleRows = computed(() =>
    filteredEntries.value.slice(startIndex.value, endIndex.value + 1).map((entry, i) => ({
      entry,
      index: startIndex.value + i,
    })),
  );

  const offsetY = computed(() => startIndex.value * props.itemHeight);

  function handleScroll(e: Event) {
    const el = e.target as HTMLElement;
    scrollTop.value = el.scrollTop;
    // Detect manual upward scroll — disable follow-tail
    const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < props.itemHeight * 2;
    userScrolled = !atBottom;
  }

  // ─── Follow tail ──────────────────────────────────────────────────────────────

  async function scrollToBottom() {
    await nextTick();
    if (containerRef.value) {
      containerRef.value.scrollTop = containerRef.value.scrollHeight;
    }
  }

  watch(
    () => props.entries.length,
    () => {
      if (props.followTail && !userScrolled) scrollToBottom();
    },
  );

  onMounted(() => {
    containerRef.value?.addEventListener('scroll', handleScroll, { passive: true });
    if (props.followTail) scrollToBottom();
  });

  onUnmounted(() => {
    containerRef.value?.removeEventListener('scroll', handleScroll);
  });
</script>

<template>
  <div
    :style="{ height: `${height}px` }"
    class="log-viewer"
  >
    <!-- Toolbar: filter status -->
    <BaseLogViewerToolbar
      v-if="filter"
      :filtered-count="filteredEntries.length"
      :total-count="entries.length"
    />

    <!-- Scroll container -->
    <div
      ref="containerRef"
      :style="{
        height: filter ? `calc(${height}px - 32px)` : `${height}px`,
        overflowY: 'auto',
        position: 'relative',
      }"
      class="log-viewer__scroll"
    >
      <!-- Full-height spacer -->
      <div
        :style="{ height: `${totalHeight}px`, position: 'relative', pointerEvents: 'none' }"
        aria-hidden="true"
      />

      <!-- Visible slice -->
      <div
        :style="{
          position: 'absolute',
          top: `${offsetY}px`,
          left: 0,
          right: 0,
        }"
        aria-atomic="false"
        aria-live="polite"
        role="log"
      >
        <BaseLogViewerRow
          v-for="{ entry, index } in visibleRows"
          :key="entry.id"
          :entry="entry"
          :index="index"
          :item-height="itemHeight"
          :show-level="showLevel"
          :show-timestamp="showTimestamp"
          @select="emit('select', entry)"
        />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
  @layer mp.components {
    .log-viewer {
      display: flex;
      flex-direction: column;
      background: var(--mp-color-bg-sunken);
      border: 1px solid var(--mp-color-border-default);
      border-radius: var(--mp-radius-md);
      overflow: hidden;

      &__toolbar {
        display: flex;
        align-items: center;
        gap: var(--mp-spacing-2);
        height: 32px;
        padding: 0 var(--mp-spacing-4);
        border-bottom: 1px solid var(--mp-color-border-strong);
        background: var(--mp-color-bg-surface);
        flex-shrink: 0;
      }

      &__filter-badge {
        font-family: var(--mp-font-family-sans);
        font-size: var(--mp-font-size-xs);
        font-weight: var(--mp-font-weight-semibold);
        color: var(--mp-color-text-secondary);
        letter-spacing: 0.04em;
        text-transform: uppercase;
      }

      &__scroll {
        flex: 1;
      }

      &__row {
        display: flex;
        align-items: center;
        gap: var(--mp-spacing-2);
        width: 100%;
        padding: 0 var(--mp-spacing-3);
        margin: 0;
        font: inherit;
        color: inherit;
        text-align: left;
        cursor: default;
        outline: none;
        background: none;
        border: 0;
        border-bottom: 1px solid transparent;
        transition: background-color 80ms ease;

        &--warn {
          background: color-mix(in srgb, var(--mp-color-warning-default) 6%, transparent);
        }

        &--error,
        &--fatal {
          background: color-mix(in srgb, var(--mp-color-danger-default) 8%, transparent);
        }

        &:focus-visible {
          outline: none;
          box-shadow: var(--mp-shadow-focus-primary);
        }

        &:hover {
          background-color: var(--mp-color-bg-raised);
        }
      }

      &__line-no {
        min-width: 44px;
        text-align: right;
        flex-shrink: 0;
        padding-right: var(--mp-spacing-2);
        border-right: 1px solid var(--mp-color-border-default);
      }

      &__timestamp {
        flex-shrink: 0;
        min-width: 140px;
      }

      &__level {
        display: flex;
        align-items: center;
        gap: var(--mp-spacing-1);
        flex-shrink: 0;
        min-width: 72px;
      }

      &__level-label {
        font-weight: var(--mp-font-weight-semibold);
        letter-spacing: 0.06em;
        text-transform: uppercase;
      }

      &__message {
        flex: 1;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
    }
  }
</style>
