// packages/components/src/components/base-switch/base-switch.tsx
import { h, useId, type MpElement, type MpProperties } from '@mission-platform/jsx';

import { BaseTypography } from '../base-typography';

import styles from './base-switch.module.scss';

/** Size token controlling the track/thumb dimensions (canonical `2xs … 2xl` scale). */
export type SwitchSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface SwitchProperties extends MpProperties {
  /**
   * On/off state (controlled via `modelValue` + `onUpdateModelValue`). Defaults to `false`.
   * @model onUpdateModelValue
   */
  modelValue?: boolean;
  /** Visible label text. */
  label?: string;
  /** Accessible label used when no visible `label` is provided. */
  ariaLabel?: string;
  /** Helper text shown below the control. */
  hint?: string;
  /** Error message shown below the control (replaces the hint). */
  error?: string;
  /** Track/thumb size. Defaults to `'md'`. */
  size?: SwitchSize;
  /** Disable the control. */
  disabled?: boolean;
  /** Explicit id; auto-generated when omitted. */
  id?: string;
  /** Fired with the next on/off value (the controlled `v-model` update). */
  onUpdateModelValue?: (value: boolean) => void;
  /** Fired with the native `change` event. */
  onChange?: (event: Event) => void;
}

/**
 * `BaseSwitch` — toggle switch authored once in the neutral JSX dialect and
 * compiled straight to React or Vue by `@mission-platform/vite-plugin-jsx`.
 *
 * A `role="switch"` checkbox styled as a sliding track/thumb across the
 * canonical `2xs … 2xl` size scale. It owns its styling through the co-located
 * CSS Module `base-switch.module.scss` and composes the neutral
 * {@link BaseTypography} for the label/hint/error text.
 *
 * Substitutions from the original Vue SFC: the `useId` composable maps straight
 * to the framework-native `useId` hook, and the `v-model` +
 * `change` emit become the established `onUpdateModelValue`/`onChange` callback
 * props.
 */
export function BaseSwitch(properties: Readonly<SwitchProperties>): MpElement {
  const { modelValue = false, label, ariaLabel, hint, error, size = 'md', disabled = false } = properties;

  const generatedId = useId();
  const resolvedId = properties.id ?? generatedId;
  const describedBy = error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined;

  const handleChange = (event: Event): void => {
    const target = event.target as HTMLInputElement;
    properties.onUpdateModelValue?.(target.checked);
    properties.onChange?.(event);
  };

  return (
    <div
      className={[
        styles['base-switch'],
        styles[`base-switch--${size}`],
        {
          [styles['base-switch--error']]: !!error,
          [styles['base-switch--disabled']]: disabled,
        },
      ]}
    >
      <label className={styles['base-switch__row']}>
        <span className={styles['base-switch__track-wrapper']}>
          <input
            id={resolvedId}
            aria-checked={modelValue}
            aria-describedby={describedBy}
            aria-invalid={error ? 'true' : undefined}
            aria-label={label ? undefined : ariaLabel}
            checked={modelValue}
            className={styles['base-switch__input']}
            disabled={disabled}
            role="switch"
            type="checkbox"
            onChange={handleChange}
          />
          <span
            aria-hidden="true"
            className={styles['base-switch__track']}
          >
            <span className={styles['base-switch__thumb']} />
          </span>
        </span>
        {label ? (
          <span className={styles['base-switch__label']}>
            <BaseTypography
              as="span"
              color="primary"
              variant="body-md"
            >
              {label}
            </BaseTypography>
          </span>
        ) : undefined}
      </label>
      {error ? (
        <p
          id={`${resolvedId}-error`}
          className={styles['base-switch__error']}
          role="alert"
        >
          <BaseTypography
            as="span"
            color="inherit"
            variant="caption"
          >
            {error}
          </BaseTypography>
        </p>
      ) : hint ? (
        <p
          id={`${resolvedId}-hint`}
          className={styles['base-switch__hint']}
        >
          <BaseTypography
            as="span"
            color="secondary"
            variant="caption"
          >
            {hint}
          </BaseTypography>
        </p>
      ) : undefined}
    </div>
  );
}

// packages/components/src/components/BaseSwitch/BaseSwitch.vue
<script lang="ts" setup>
  import { useId } from '../../composables/use-id';
  import BaseTypography from '../BaseTypography/BaseTypography.vue';

  export type SwitchSize = 'sm' | 'md' | 'lg';

  const props = withDefaults(
    defineProps<{
      modelValue?: boolean;
      label?: string;
      ariaLabel?: string;
      hint?: string;
      error?: string;
      size?: SwitchSize;
      disabled?: boolean;
      id?: string;
    }>(),
    {
      modelValue: false,
      label: undefined,
      ariaLabel: undefined,
      hint: undefined,
      error: undefined,
      size: 'md',
      disabled: false,
      id: undefined,
    },
  );

  const emit = defineEmits<{
    'update:modelValue': [value: boolean];
    change: [event: Event];
  }>();

  const { id: resolvedId } = useId(props.id);

  function handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    emit('update:modelValue', target.checked);
    emit('change', event);
  }
</script>

<template>
  <div
    :class="[
      'base-switch',
      `base-switch--${size}`,
      { 'base-switch--error': !!error, 'base-switch--disabled': disabled },
    ]"
  >
    <label class="base-switch__row">
      <span class="base-switch__track-wrapper">
        <input
          :id="resolvedId"
          :aria-checked="modelValue"
          :aria-describedby="error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined"
          :aria-invalid="!!error || undefined"
          :aria-label="!label ? ariaLabel : undefined"
          :checked="modelValue"
          :disabled="disabled"
          class="base-switch__input"
          role="switch"
          type="checkbox"
          @change="handleChange"
        />
        <span
          aria-hidden="true"
          class="base-switch__track"
        >
          <span class="base-switch__thumb" />
        </span>
      </span>
      <span
        v-if="label"
        class="base-switch__label"
      >
        <BaseTypography
          as="span"
          color="primary"
          variant="body-md"
        >
          {{ label }}
        </BaseTypography>
      </span>
    </label>
    <BaseTypography
      v-if="error"
      :id="`${resolvedId}-error`"
      as="p"
      class="base-switch__error"
      color="inherit"
      role="alert"
      variant="caption"
    >
      {{ error }}
    </BaseTypography>
    <BaseTypography
      v-else-if="hint"
      :id="`${resolvedId}-hint`"
      as="p"
      class="base-switch__hint"
      color="secondary"
      variant="caption"
    >
      {{ hint }}
    </BaseTypography>
  </div>
</template>

<style lang="scss" scoped>
  .base-switch {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-1);

    &__row {
      display: inline-flex;
      align-items: center;
      gap: var(--mp-spacing-2);
      cursor: pointer;
    }

    &__track-wrapper {
      position: relative;
      display: flex;
      align-items: center;
      flex-shrink: 0;
    }

    /* Sizes */
    &--sm {
      --thumb-translate: 16px;

      .base-switch__track {
        width: 32px;
        height: 18px;
        padding: 2px;
      }

      .base-switch__thumb {
        width: 14px;
        height: 14px;
      }

      /* label typography handled by BaseTypography */
    }

    &--md {
      --thumb-translate: 20px;

      .base-switch__track {
        width: 40px;
        height: 22px;
        padding: 2px;
      }

      .base-switch__thumb {
        width: 18px;
        height: 18px;
      }
    }

    &--lg {
      --thumb-translate: 26px;

      .base-switch__track {
        width: 52px;
        height: 28px;
        padding: 3px;
      }

      .base-switch__thumb {
        width: 22px;
        height: 22px;
      }
    }

    &__label {
      /* typography handled by BaseTypography */
    }

    /* States */
    &--error {
      .base-switch__track {
        outline: 1px solid var(--mp-color-danger-default);
      }
    }

    &__input {
      position: absolute;
      opacity: 0;
      width: 100%;
      height: 100%;
      margin: 0;
      cursor: pointer;

      &:focus-visible ~ .base-switch__track {
        outline: 2px solid var(--mp-color-border-focus);
        outline-offset: 2px;
      }

      &:checked ~ .base-switch__track {
        background-color: var(--mp-color-primary-default);

        .base-switch__thumb {
          transform: translateX(var(--thumb-translate));
        }
      }
    }

    &__track {
      display: flex;
      align-items: center;
      background-color: var(--mp-color-border-default);
      border-radius: var(--mp-radius-full);
      transition: background-color 200ms ease;
      pointer-events: none;
    }

    &__thumb {
      display: block;
      background-color: var(--mp-color-text-on-primary);
      border-radius: 50%;
      box-shadow: var(--mp-shadow-sm);
      transition: transform 200ms ease;
      flex-shrink: 0;
    }

    &--disabled {
      opacity: 0.5;
      pointer-events: none;

      .base-switch__row {
        cursor: not-allowed;
      }
    }

    &__error {
      color: var(--mp-color-danger-text);
      margin: 0;
    }

    &__hint {
      margin: 0;
    }
  }
</style>
