// packages/components/src/components/base-grid/base-grid.tsx
import { classNames, Dynamic, h, type MpElement, type MpProperties } from '@mission-platform/jsx';

import sizeStyles from '../size.module.scss';
import spacingStyles from '../spacing.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type GridSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
/** Named gap scale; each step resolves to a `--mp-spacing-*` design token. */
export type GridGap = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
/** Item-placement keywords for both the inline (`justify`) and block (`align`) axes. */
export type GridAlignment = 'start' | 'center' | 'end' | 'stretch';
/** Named `padding`/`margin` scale; each step maps to a named `--mp-spacing-*` design token. */
export type SpacingScale = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** Maps each {@link GridGap} step onto a `--mp-spacing-*` token. */
const GAP_SPACING: Record<GridGap, string> = {
  '2xs': 'var(--mp-spacing-1)',
  xs: 'var(--mp-spacing-2)',
  sm: 'var(--mp-spacing-3)',
  md: 'var(--mp-spacing-4)',
  lg: 'var(--mp-spacing-6)',
  xl: 'var(--mp-spacing-8)',
  '2xl': 'var(--mp-spacing-12)',
};

export interface GridProperties extends MpProperties {
  /** Number of rows (m) in the grid. */
  rows?: number;
  /** Number of columns (n) in the grid. */
  cols?: number;
  /**
   * Minimum column width (any CSS length). When set, the grid switches to a
   * responsive `auto-fit` track list (`repeat(auto-fit, minmax(<minColumnWidth>, 1fr))`)
   * and `cols` is ignored — columns wrap to fit the available inline space.
   */
  minColumnWidth?: string;
  /** Gap between cells (named `2xs … 2xl` scale). Sets both the row and column gaps. */
  gap?: GridGap;
  /** Row gap (named `2xs … 2xl` scale). Overrides `gap` on the block axis. */
  rowGap?: GridGap;
  /** Column gap (named `2xs … 2xl` scale). Overrides `gap` on the inline axis. */
  columnGap?: GridGap;
  /** Inline-axis placement of each cell's content (`justify-items`). */
  justify?: GridAlignment;
  /** Block-axis placement of each cell's content (`align-items`). */
  align?: GridAlignment;
  /** The HTML tag the grid container renders as. */
  tag?: string;
  /** Outer margin (named `2xs … 2xl` scale), mapped to a `--mp-spacing-*` token. */
  margin?: SpacingScale;
  /** Inner padding (named `2xs … 2xl` scale), mapped to a `--mp-spacing-*` token. */
  padding?: SpacingScale;
  /** Size token controlling the grid's font scale. Defaults to `'md'`. */
  size?: GridSize;
}

/**
 * `BaseGrid` — a CSS Grid layout primitive that arranges its content into a
 * grid of `rows` (m) by `cols` (n) with a configurable `gap` (overridable per
 * axis via `rowGap` / `columnGap`). Authored once in the neutral JSX dialect
 * and compiled straight to React or Vue by `@mission-platform/vite-plugin-jsx`.
 *
 * Children supplied through the default slot flow into the grid cells in source
 * order and may span multiple tracks with the standard `grid-column` /
 * `grid-row` `span` CSS. Unlike the Vue original it does not expose the scoped
 * `cell` slot — that fully-populated mode maps onto Vue's scoped slots, which
 * the neutral dialect does not model.
 *
 * It emits a BEM class plus the computed grid inline style; the demo styling
 * lives in the co-located `base-grid.module.scss` (imported by
 * `base-grid.stories.tsx`).
 */
export function BaseGrid(properties: Readonly<GridProperties>): MpElement {
  const {
    rows = 1,
    cols = 1,
    minColumnWidth,
    gap = 'md',
    rowGap,
    columnGap,
    justify = 'stretch',
    align = 'stretch',
    tag = 'div',
    padding,
    margin,
    size = 'md',
  } = properties;

  const rowCount = Math.max(1, Math.floor(rows));
  const columnCount = Math.max(1, Math.floor(cols));

  // When `minColumnWidth` is supplied, fit as many equal-width columns of at
  // least that width as the inline space allows (responsive `auto-fit`);
  // otherwise lay out a fixed `cols`-wide track list.
  const gridTemplateColumns =
    minColumnWidth === undefined
      ? `repeat(${columnCount}, minmax(0, 1fr))`
      : `repeat(auto-fit, minmax(min(${minColumnWidth}, 100%), 1fr))`;

  const style: Record<string, string> = {
    display: 'grid',
    width: '100%',
    minWidth: '0',
    gridTemplateColumns,
    gridTemplateRows: `repeat(${rowCount}, minmax(0, auto))`,
    rowGap: GAP_SPACING[rowGap ?? gap],
    columnGap: GAP_SPACING[columnGap ?? gap],
    justifyItems: justify,
    alignItems: align,
  };

  // Optional `padding`/`margin` (named `2xs … 2xl` scale) resolve to the shared
  // token-driven spacing classes rather than inline styles.
  const className = classNames(
    'base-grid',
    padding ? spacingStyles[`base-spacing--padding-${padding}`] : undefined,
    margin ? spacingStyles[`base-spacing--margin-${margin}`] : undefined,
    sizeStyles[`base-size--${size}`],
  );

  return (
    <Dynamic
      classNames={className}
      is={tag}
      style={style}
    >
      {properties.children}
    </Dynamic>
  );
}

// packages/components/src/components/base-grid/base-grid.vue
<script lang="ts" setup>
  /**
   * `BaseGrid` — a CSS Grid layout primitive that arranges its content into a
   * grid of `rows` (m) by `cols` (n).
   *
   * By default it defines `cols` equally-sized columns and `rows` equally-sized
   * rows, with a configurable `gap` between cells (overridable per axis via
   * `rowGap` / `columnGap`). Gaps use the named `2xs … 2xl` scale, each step
   * resolving to a `--mp-spacing-*` design token. Content is supplied through
   * the default slot and flows into the grid cells in source order.
   *
   * For a fully populated grid, use the scoped `cell` slot: it renders one node
   * per cell (`rows * cols` cells) and exposes the zero-based `row`, `column`,
   * and `index` of each cell so consumers can render coordinate-aware content.
   * Children placed via the default slot may span multiple tracks with the
   * standard `grid-column` / `grid-row` `span` CSS (see the stories).
   *
   * The `justify` / `align` props position the content of every cell along the
   * inline (`justify-items`) and block (`align-items`) axes respectively.
   *
   * See the props, emits, and slots tables below (auto-generated from
   * the component's TypeScript declarations) for the full public API,
   * and refer to the linked stories for usage examples.
   */
  import { computed } from 'vue';

  import { type GridGap, type GridAlignment, GRID_GAP_SPACING } from './constants';

  /** Coordinates exposed by the scoped `cell` slot for each grid cell. */
  export interface GridCell {
    /** Zero-based, row-major index of the cell (`0 … rows * cols - 1`). */
    index: number;
    /** Zero-based row of the cell (`0 … rows - 1`). */
    row: number;
    /** Zero-based column of the cell (`0 … cols - 1`). */
    column: number;
  }

  const props = withDefaults(
    defineProps<{
      /** Number of rows (m) in the grid. */
      rows?: number;
      /** Number of columns (n) in the grid. */
      cols?: number;
      /** Gap between cells (named `2xs … 2xl` scale). Sets both the row and column gaps. */
      gap?: GridGap;
      /** Row gap (named `2xs … 2xl` scale). Overrides `gap` on the block axis. */
      rowGap?: GridGap;
      /** Column gap (named `2xs … 2xl` scale). Overrides `gap` on the inline axis. */
      columnGap?: GridGap;
      /** Inline-axis placement of each cell's content (`justify-items`). */
      justify?: GridAlignment;
      /** Block-axis placement of each cell's content (`align-items`). */
      align?: GridAlignment;
      /** The HTML tag the grid container renders as. */
      as?: string;
    }>(),
    {
      rows: 1,
      cols: 1,
      gap: 'md',
      rowGap: undefined,
      columnGap: undefined,
      justify: 'stretch',
      align: 'stretch',
      as: 'div',
    },
  );

  /** Clamped, integral row count (always at least 1). */
  const rowCount = computed(() => Math.max(1, Math.floor(props.rows)));
  /** Clamped, integral column count (always at least 1). */
  const columnCount = computed(() => Math.max(1, Math.floor(props.cols)));

  /** Row-major list of cell coordinates for the scoped `cell` slot. */
  const cells = computed<GridCell[]>(() =>
    Array.from({ length: rowCount.value * columnCount.value }, (_, index) => ({
      index,
      row: Math.floor(index / columnCount.value),
      column: index % columnCount.value,
    })),
  );

  const gridStyle = computed(() => ({
    gridTemplateColumns: `repeat(${columnCount.value}, minmax(0, 1fr))`,
    gridTemplateRows: `repeat(${rowCount.value}, minmax(0, auto))`,
    rowGap: GRID_GAP_SPACING[props.rowGap ?? props.gap],
    columnGap: GRID_GAP_SPACING[props.columnGap ?? props.gap],
    justifyItems: props.justify,
    alignItems: props.align,
  }));
</script>

<template>
  <component
    :is="as"
    :style="gridStyle"
    class="base-grid"
  >
    <template v-if="$slots.cell">
      <slot
        v-for="cell in cells"
        :key="cell.index"
        :column="cell.column"
        :index="cell.index"
        :row="cell.row"
        name="cell"
      />
    </template>
    <slot />
  </component>
</template>

<style lang="scss" scoped>
  .base-grid {
    display: grid;
    width: 100%;
    min-width: 0;
  }
</style>
