// packages/components/src/components/BaseCheckbox/BaseCheckbox.vue
<script lang="ts" setup>
  import { useI18n } from '@mission-platform/i18n';
  import { computed, ref, watch } from 'vue';

  import { useId } from '../../composables/use-id';
  import BaseTypography from '../BaseTypography/BaseTypography.vue';

  const props = withDefaults(
    defineProps<{
      modelValue?: boolean | string[];
      value?: string;
      label?: string;
      labelHidden?: boolean;
      hint?: string;
      error?: string;
      disabled?: boolean;
      required?: boolean;
      indeterminate?: boolean;
      id?: string;
    }>(),
    {
      modelValue: false,
      value: undefined,
      label: undefined,
      labelHidden: false,
      hint: undefined,
      error: undefined,
      disabled: false,
      required: false,
      indeterminate: false,
      id: undefined,
    },
  );

  const emit = defineEmits<{
    'update:modelValue': [value: boolean | string[]];
    change: [event: Event];
  }>();

  const isChecked = computed(() => {
    if (Array.isArray(props.modelValue)) {
      return props.value !== undefined && props.modelValue.includes(props.value);
    }
    return props.modelValue;
  });

  function handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    if (Array.isArray(props.modelValue) && props.value !== undefined) {
      const next = [...props.modelValue];
      if (target.checked) {
        next.push(props.value);
      } else {
        const idx = next.indexOf(props.value);
        if (idx !== -1) next.splice(idx, 1);
      }
      emit('update:modelValue', next);
    } else {
      emit('update:modelValue', target.checked);
    }
    emit('change', event);
  }

  const { t } = useI18n({ useScope: 'local' });
  const { id: resolvedId } = useId(props.id);

  const checkboxRef = ref<HTMLInputElement | null>(null);

  watch(
    () => props.indeterminate,
    (val) => {
      if (checkboxRef.value) checkboxRef.value.indeterminate = val;
    },
    { immediate: true },
  );
</script>

<template>
  <div :class="['base-checkbox', { 'base-checkbox--error': !!error, 'base-checkbox--disabled': disabled }]">
    <label
      :for="resolvedId"
      class="base-checkbox__row"
    >
      <span class="base-checkbox__control-wrapper">
        <input
          :id="resolvedId"
          ref="checkboxRef"
          :aria-describedby="error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined"
          :aria-invalid="!!error || undefined"
          :checked="isChecked"
          :disabled="disabled"
          :required="required"
          :value="value"
          class="base-checkbox__input"
          type="checkbox"
          @change="handleChange"
        />
        <span
          aria-hidden="true"
          class="base-checkbox__box"
        >
          <svg
            v-if="indeterminate"
            class="base-checkbox__icon"
            fill="none"
            viewBox="0 0 12 12"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M2 6h8"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-width="2"
            />
          </svg>
          <svg
            v-else
            class="base-checkbox__icon"
            fill="none"
            viewBox="0 0 12 12"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M2 6l3 3 5-5"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
            />
          </svg>
        </span>
      </span>
      <span
        v-if="label"
        :class="['base-checkbox__label', { 'base-checkbox__label--hidden': labelHidden }]"
      >
        <BaseTypography
          as="span"
          color="primary"
          variant="body-md"
        >
          {{ label }}
        </BaseTypography>
        <span
          v-if="required"
          :title="t('required')"
          aria-hidden="true"
          class="base-checkbox__required"
        >
          *
        </span>
      </span>
    </label>
    <BaseTypography
      v-if="error"
      :id="`${resolvedId}-error`"
      as="p"
      class="base-checkbox__error"
      color="inherit"
      role="alert"
      variant="caption"
    >
      {{ error }}
    </BaseTypography>
    <BaseTypography
      v-else-if="hint"
      :id="`${resolvedId}-hint`"
      as="p"
      class="base-checkbox__hint"
      color="secondary"
      variant="caption"
    >
      {{ hint }}
    </BaseTypography>
  </div>
</template>

<style lang="scss" scoped>
  .base-checkbox {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-1);

    &__row {
      display: inline-flex;
      align-items: center;
      gap: var(--mp-spacing-2);
      cursor: pointer;
    }

    &__control-wrapper {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    &__box {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 18px;
      height: 18px;
      border: 2px solid var(--mp-color-border-default);
      border-radius: var(--mp-radius-sm);
      background-color: var(--mp-color-bg-surface);
      color: transparent;
      transition:
        background-color 150ms ease,
        border-color 150ms ease;
      pointer-events: none;
    }

    &__icon {
      width: 12px;
      height: 12px;
    }

    &__label {
      /* typography handled by BaseTypography */

      &--hidden {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip-path: inset(50%);
        white-space: nowrap;
        border: 0;
      }
    }

    &__required {
      color: var(--mp-color-danger-default);
      margin-left: 2px;
    }

    /* States */
    &--error {
      .base-checkbox__box {
        border-color: var(--mp-color-danger-default);
      }
    }

    &__input {
      position: absolute;
      opacity: 0;
      width: 100%;
      height: 100%;
      margin: 0;
      cursor: pointer;

      &:focus-visible ~ .base-checkbox__box {
        outline: 2px solid var(--mp-color-border-focus);
        outline-offset: 2px;
      }

      &:checked ~ .base-checkbox__box,
      &:indeterminate ~ .base-checkbox__box {
        background-color: var(--mp-color-primary-default);
        border-color: var(--mp-color-primary-default);
        color: var(--mp-color-text-on-primary);
      }
    }

    &--disabled {
      opacity: 0.5;
      pointer-events: none;

      .base-checkbox__row {
        cursor: not-allowed;
      }
    }

    &__error {
      color: var(--mp-color-danger-text);
      margin: 0;
      padding-left: calc(18px + var(--mp-spacing-2));
    }

    &__hint {
      margin: 0;
      padding-left: calc(18px + var(--mp-spacing-2));
    }
  }
</style>

<i18n lang="yaml">
en:
  required: required
</i18n>

// packages/components/src/components/base-checkbox/base-checkbox.tsx
import { h, useEffect, useRef, type MpElement, type MpProperties } from '@mission-platform/jsx';

import { BaseTypography } from '../base-typography';
import { nextFieldId } from '../field-id';
import sizeStyles from '../size.module.scss';

import styles from './base-checkbox.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type CheckboxSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface CheckboxProperties extends MpProperties {
  /**
   * Checked state. A `boolean` for a standalone checkbox, or a `string[]` of
   * selected `value`s when the checkbox participates in a group. Controlled via
   * `modelValue` + `onUpdateModelValue`. Defaults to `false`.
   */
  modelValue?: boolean | string[];
  /** This checkbox's value, used when `modelValue` is a `string[]` group. */
  value?: string;
  /** Visible label text. */
  label?: string;
  /** Visually hide the label (kept for assistive tech). */
  labelHidden?: boolean;
  /** Helper text shown below the control. */
  hint?: string;
  /** Error message shown below the control (replaces the hint). */
  error?: string;
  /** Disable the control. */
  disabled?: boolean;
  /** Mark the field as required (renders a `*` after the label). */
  required?: boolean;
  /** Render the mixed/indeterminate state. */
  indeterminate?: boolean;
  /** Field size. Defaults to `'md'`. */
  size?: CheckboxSize;
  /** Explicit id; auto-generated when omitted. */
  id?: string;
  /** Fired with the next checked value (the controlled `v-model` update). */
  onUpdateModelValue?: (value: boolean | string[]) => void;
  /** Fired with the native `change` event. */
  onChange?: (event: Event) => void;
}

/**
 * `BaseCheckbox` — checkbox control authored once in the neutral JSX dialect and
 * compiled straight to React or Vue by `@mission-platform/vite-plugin-jsx`.
 *
 * Supports both a standalone boolean and a `string[]` group (toggling its
 * `value` in/out of the array). It owns its styling through the co-located CSS
 * Module `base-checkbox.module.scss` and composes the neutral {@link BaseTypography}
 * for the label/hint/error text.
 *
 * Substitutions from the original Vue SFC: the `useId` composable becomes the
 * shared `nextFieldId` helper resolved once in a `useRef`; the indeterminate
 * DOM property is set through a `useRef` + `useEffect` pair (the neutral
 * equivalent of the SFC `watch`); the inline check/indeterminate SVGs become a
 * CSS-coloured `✓`/`−` glyph; the `useI18n` "required" title becomes a plain
 * string; and the `v-model` + `change` emit become the established
 * `onUpdateModelValue`/`onChange` callback props.
 */
export function BaseCheckbox(properties: CheckboxProperties): MpElement {
  const {
    modelValue = false,
    value,
    label,
    labelHidden = false,
    hint,
    error,
    disabled = false,
    required = false,
    indeterminate = false,
    size = 'md',
  } = properties;

  const idReference = useRef<string>(properties.id ?? nextFieldId('mp-checkbox'));
  const resolvedId = idReference.current;
  const inputReference = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (inputReference.current) {
      inputReference.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  const isChecked = Array.isArray(modelValue) ? value !== undefined && modelValue.includes(value) : modelValue;
  const describedBy = error ? `${resolvedId}-error` : hint ? `${resolvedId}-hint` : undefined;

  const handleChange = (event: Event): void => {
    const target = event.target as HTMLInputElement;
    if (Array.isArray(modelValue) && value !== undefined) {
      const next = [...modelValue];
      if (target.checked) {
        next.push(value);
      } else {
        const index = next.indexOf(value);
        if (index !== -1) {
          next.splice(index, 1);
        }
      }
      properties.onUpdateModelValue?.(next);
    } else {
      properties.onUpdateModelValue?.(target.checked);
    }
    properties.onChange?.(event);
  };

  return (
    <div
      classNames={[
        styles['base-checkbox'],
        sizeStyles[`base-size--${size}`],
        {
          [styles['base-checkbox--error']]: !!error,
          [styles['base-checkbox--disabled']]: disabled,
        },
      ]}
    >
      <label
        classNames={styles['base-checkbox__row']}
        for={resolvedId}
      >
        <span classNames={styles['base-checkbox__control-wrapper']}>
          <input
            ref={inputReference}
            id={resolvedId}
            aria-describedby={describedBy}
            aria-invalid={error ? 'true' : undefined}
            checked={isChecked}
            classNames={styles['base-checkbox__input']}
            disabled={disabled}
            required={required}
            type="checkbox"
            value={value}
            onChange={handleChange}
          />
          <span
            aria-hidden="true"
            classNames={styles['base-checkbox__box']}
          >
            <span classNames={styles['base-checkbox__glyph']}>{indeterminate ? '−' : '✓'}</span>
          </span>
        </span>
        {label ? (
          <span
            classNames={[
              styles['base-checkbox__label'],
              {
                [styles['base-checkbox__label--hidden']]: labelHidden,
              },
            ]}
          >
            <BaseTypography
              as="span"
              color="primary"
              variant="body-md"
            >
              {label}
            </BaseTypography>
            {required ? (
              <span
                aria-hidden="true"
                classNames={styles['base-checkbox__required']}
                title="required"
              >
                *
              </span>
            ) : undefined}
          </span>
        ) : undefined}
      </label>
      {error ? (
        <p
          id={`${resolvedId}-error`}
          classNames={styles['base-checkbox__error']}
          role="alert"
        >
          <BaseTypography
            as="span"
            color="inherit"
            variant="caption"
          >
            {error}
          </BaseTypography>
        </p>
      ) : hint ? (
        <p
          id={`${resolvedId}-hint`}
          classNames={styles['base-checkbox__hint']}
        >
          <BaseTypography
            as="span"
            color="secondary"
            variant="caption"
          >
            {hint}
          </BaseTypography>
        </p>
      ) : undefined}
    </div>
  );
}
