// packages/components/src/components/BaseNavbar/BaseNavbar.vue
<script lang="ts" setup>
  import { ref } from 'vue';

  import BaseSidebar from '../BaseSidebar/BaseSidebar.vue';
  import BaseTypography from '../BaseTypography/BaseTypography.vue';

  withDefaults(
    defineProps<{
      brand?: string;
      sticky?: boolean;
      mobileTitle?: string;
    }>(),
    {
      brand: undefined,
      sticky: false,
      mobileTitle: undefined,
    },
  );

  const sidebarOpen = ref(false);
</script>

<template>
  <header :class="['base-navbar', { 'base-navbar--sticky': sticky }]">
    <nav
      aria-label="Main navigation"
      class="base-navbar__container"
    >
      <div class="base-navbar__start">
        <slot name="brand">
          <BaseTypography
            v-if="brand"
            as="span"
            class="base-navbar__brand"
            color="primary"
            variant="h6"
          >
            {{ brand }}
          </BaseTypography>
        </slot>
      </div>
      <div class="base-navbar__center">
        <slot />
      </div>
      <div class="base-navbar__end">
        <slot name="end" />
      </div>

      <!-- Hamburger: only shown on mobile -->
      <button
        :aria-expanded="sidebarOpen"
        :aria-label="sidebarOpen ? 'Close menu' : 'Open menu'"
        class="base-navbar__hamburger"
        type="button"
        @click="sidebarOpen = !sidebarOpen"
      >
        <span class="base-navbar__hamburger-bar" />
        <span class="base-navbar__hamburger-bar" />
        <span class="base-navbar__hamburger-bar" />
      </button>
    </nav>
  </header>

  <!-- Mobile sidebar drawer -->
  <BaseSidebar
    v-model:open="sidebarOpen"
    :title="mobileTitle || brand"
    side="left"
    size="sm"
  >
    <nav
      aria-label="Mobile navigation"
      class="base-navbar__mobile-nav"
    >
      <div class="base-navbar__mobile-nav-items">
        <slot />
      </div>
      <div class="base-navbar__mobile-nav-end">
        <slot name="end" />
      </div>
    </nav>
  </BaseSidebar>
</template>

<style lang="scss" scoped>
  @use '@mission-platform/breakpoints/scss/mixins' as bp;

  .base-navbar {
    background-color: var(--mp-color-bg-surface);
    border-bottom: 1px solid var(--mp-color-border-default);
    z-index: 100;
    padding-left: env(safe-area-inset-left);
    padding-right: env(safe-area-inset-right);

    &--sticky {
      position: sticky;
      top: 0;
    }

    &__container {
      display: flex;
      align-items: center;
      height: var(--mp-size-height-xl);
      padding: 0 var(--mp-spacing-4);
      gap: var(--mp-spacing-3);
      max-width: 100%;

      @include bp.bp-up('sm') {
        padding: 0 var(--mp-spacing-6);
        gap: var(--mp-spacing-4);
      }
    }

    &__start {
      display: flex;
      align-items: center;
      gap: var(--mp-spacing-4);
      flex-shrink: 0;
    }

    &__center {
      display: flex;
      align-items: center;
      gap: var(--mp-spacing-1);
      flex: 1;
    }

    &__end {
      display: flex;
      align-items: center;
      gap: var(--mp-spacing-2);
      flex-shrink: 0;
    }

    &__brand {
      /* typography handled by BaseTypography */
      text-decoration: none;
      letter-spacing: -0.01em;
    }

    &__hamburger {
      display: none;
      flex-direction: column;
      justify-content: center;
      gap: var(--mp-spacing-1);
      width: var(--mp-size-height-md);
      height: var(--mp-size-height-md);
      padding: var(--mp-spacing-2);
      background: none;
      border: none;
      border-radius: var(--mp-radius-md);
      cursor: pointer;
      color: var(--mp-color-text-primary);
      flex-shrink: 0;

      &:hover {
        background-color: var(--mp-color-bg-subtle);
      }

      &:focus-visible {
        outline: none;
        box-shadow: var(--mp-shadow-focus-primary);
      }
    }

    &__hamburger-bar {
      display: block;
      width: 100%;
      height: 2px;
      border-radius: 1px;
      background-color: currentColor;
    }
  }

  .base-navbar__mobile-nav {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-1);
    padding: var(--mp-spacing-2) var(--mp-spacing-3);
    height: 100%;
  }

  .base-navbar__mobile-nav-items {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-1);
    flex: 1;
  }

  .base-navbar__mobile-nav-end {
    display: flex;
    flex-direction: column;
    gap: var(--mp-spacing-2);
    padding-top: var(--mp-spacing-4);
    border-top: 1px solid var(--mp-color-border-default);
  }

  /* On mobile (below sm breakpoint): hide center/end, show hamburger */
  @include bp.bp-down('sm') {
    .base-navbar {
      &__center,
      &__end {
        display: none;
      }

      &__hamburger {
        display: flex;
      }
    }
  }
</style>

// packages/components/src/components/base-navbar/base-navbar.tsx
import { h, Slot, useState, type MpElement, type MpProperties } from '@mission-platform/jsx';

import { BaseDrawer } from '../base-drawer';
import { BaseTypography } from '../base-typography';
import sizeStyles from '../size.module.scss';

import styles from './base-navbar.module.scss';

/** Size token — canonical 2xs → 2xl scale. */
export type NavbarSize = '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

/** Alignment of the default-slot (centre) navigation items. */
export type NavbarAlign = 'start' | 'center' | 'end';

export interface NavbarProperties extends MpProperties {
  /** Size token controlling the navbar's scale. Defaults to `'md'`. */
  size?: NavbarSize;
  /** Brand text shown in the start region (overridable via the `brand` slot). */
  brand?: string;
  /** Stick the navbar to the top of the viewport on scroll. */
  sticky?: boolean;
  /** Title for the mobile navigation drawer (defaults to `brand`). */
  mobileTitle?: string;
  /** Alignment of the default-slot (centre) navigation items. Defaults to `'start'`. */
  align?: NavbarAlign;
}

/**
 * `BaseNavbar` — the top application navigation bar authored once in the neutral
 * JSX dialect and compiled straight to React or Vue by
 * `@mission-platform/vite-plugin-jsx`.
 *
 * It lays out a `brand` slot, the centred default slot (navigation items), and
 * an `end` slot, collapsing on mobile (below the `sm` breakpoint, via CSS) to a
 * hamburger button that toggles a {@link BaseDrawer} mirroring the default +
 * `end` slots. The open state is held locally with the neutral `useState` hook.
 *
 * It composes the write-once {@link BaseDrawer} and {@link BaseTypography}, owns
 * its styling through the co-located `base-navbar.module.scss`, and returns its
 * header + drawer under a single `display: contents` host (the neutral dialect
 * has no multi-root fragment return).
 */
export function BaseNavbar(properties: NavbarProperties): MpElement {
  const { brand, sticky = false, mobileTitle, align = 'start', size = 'md' } = properties;

  const [sidebarOpen, setSidebarOpen] = useState(false);

  const header = (
    <header classNames={[styles['base-navbar'], sizeStyles[`base-size--${size}`], { [styles['base-navbar--sticky']]: sticky }]}>
      <nav
        aria-label="Main navigation"
        classNames={styles['base-navbar__container']}
      >
        <div classNames={styles['base-navbar__start']}>
          <Slot name="brand">
            {brand ? (
              <BaseTypography
                as="span"
                variant="h6"
                color="primary"
              >
                {brand}
              </BaseTypography>
            ) : undefined}
          </Slot>
        </div>
        <div classNames={[styles['base-navbar__center'], styles[`base-navbar__center--${align}`]]}>
          <Slot />
        </div>
        <div classNames={styles['base-navbar__end']}>
          <Slot name="end" />
        </div>
        <button
          type="button"
          classNames={styles['base-navbar__hamburger']}
          aria-expanded={sidebarOpen}
          aria-label={sidebarOpen ? 'Close menu' : 'Open menu'}
          onClick={() => setSidebarOpen(!sidebarOpen)}
        >
          <span classNames={styles['base-navbar__hamburger-bar']} />
          <span classNames={styles['base-navbar__hamburger-bar']} />
          <span classNames={styles['base-navbar__hamburger-bar']} />
        </button>
      </nav>
    </header>
  );

  const drawer = (
    <BaseDrawer
      open={sidebarOpen}
      title={mobileTitle ?? brand}
      placement="start"
      size="sm"
      onOpenChange={(next: boolean) => setSidebarOpen(next)}
    >
      <nav
        aria-label="Mobile navigation"
        classNames={styles['base-navbar__mobile-nav']}
      >
        <div classNames={styles['base-navbar__mobile-nav-items']}>
          <Slot />
        </div>
        <div classNames={styles['base-navbar__mobile-nav-end']}>
          <Slot name="end" />
        </div>
      </nav>
    </BaseDrawer>
  );

  return h('div', { class: styles['base-navbar-host'] }, header, drawer);
}
